import { ScreenText } from "../components/ScreenText"
import { useEffect,useState } from 'react'
import { Link } from 'react-router-dom'
import { supabase } from '../lib/supabase'
import { loadTenantData } from '../lib/tenant'
import { defaultAppearance,themePresets,appFonts,appearanceVars,type Appearance,type FontName } from '../lib/appearance'
export function AppearancePage(){
 const [location,setLocation]=useState('');const [draft,setDraft]=useState<Appearance>(defaultAppearance);const [version,setVersion]=useState(0);const [busy,setBusy]=useState(true);const [error,setError]=useState('');const [notice,setNotice]=useState('')
 useEffect(()=>{let live=true;void(async()=>{try{const t=await loadTenantData();const loc=t.locations[0]?.id;if(!loc)throw new Error('No active location.');const r=await supabase.rpc('app_appearance_get',{p_location_id:loc});if(r.error)throw r.error;if(live){setLocation(loc);setDraft({...defaultAppearance,...r.data.config});setVersion(r.data.version)}}catch(e){if(live)setError(String((e as Error).message))}finally{if(live)setBusy(false)}})();return()=>{live=false}},[])
 async function save(){setBusy(true);setError('');setNotice('');try{const r=await supabase.rpc('app_appearance_save',{p_location_id:location,p_config:draft,p_version:version});if(r.error)throw r.error;setVersion(r.data.version);window.dispatchEvent(new Event('app-appearance-changed'));setNotice('Appearance saved for this location. Staff will receive it when they open the app or within one minute.')}catch(e){setError(String((e as Error).message))}finally{setBusy(false)}}
 return <section className="appearance-page"><Link to="/closeout"><ScreenText id="AppearancePage.89412119744c72b5">← Closeout</ScreenText></Link><p className="eyebrow"><ScreenText id="AppearancePage.1e4bd93d88a48f32">General manager only</ScreenText></p><h1><ScreenText id="AppearancePage.c690e5e8a4cfcb60">App Appearance</ScreenText></h1><p><ScreenText id="AppearancePage.54f37cceeacf18ab">Choose your location’s colors and font. Preview below before saving.</ScreenText></p>{error && <p role="alert">{error}</p>}{notice && <p role="status">{notice}</p>}<fieldset disabled={busy || !location}><legend><ScreenText id="AppearancePage.08f96f13013e39cf">Theme</ScreenText></legend><div className="appearance-presets">{Object.entries(themePresets).map(([name,preset])=><button type="button" key={name} onClick={()=>setDraft(preset)}>{name}</button>)}</div><div className="appearance-colors">{(['background','card','text','muted','accent','accentText','border'] as const).map(key=><label key={key}>{key==='accentText'?'Button text':key[0].toUpperCase()+key.slice(1)}<input type="color" value={draft[key]} onChange={e=>setDraft(v=>({...v,[key]:e.target.value}))}/></label>)}</div><label><ScreenText id="AppearancePage.532f6e8b9b0615c6">App font</ScreenText><select value={draft.font} onChange={e=>setDraft(v=>({...v,font:e.target.value as FontName}))}>{Object.entries(appFonts).map(([key,f])=><option key={key} value={key}>{f.label}</option>)}</select></label><button type="button" className="primary-button" onClick={()=>void save()}>{busy?'Saving…':'Save appearance'}</button></fieldset><section className="appearance-preview" style={appearanceVars(draft)}><h2><ScreenText id="AppearancePage.c9f28a730f834a65">Today’s pre-shift</ScreenText></h2><article><h3><ScreenText id="AppearancePage.8921d28a100b7379">Ready for service ✨</ScreenText></h3><p><ScreenText id="AppearancePage.d8d35c13c9717996">White cards, clear text, and colors that match your team.</ScreenText></p><p className="preview-muted"><ScreenText id="AppearancePage.3c01dd19dac9e467">Preview of secondary text</ScreenText></p><button type="button"><ScreenText id="AppearancePage.e060ed19992ad5d6">Take the quiz</ScreenText></button></article></section></section>
}
