import { ScreenText } from "../components/ScreenText"
import { useEffect, useId, useRef, useState } from 'react'
import type { PropsWithChildren } from 'react'
import { Link } from 'react-router-dom'
import { supabase } from '../lib/supabase'
import { loadTenantData } from '../lib/tenant'
import { emptyRecipe,parseCocktails,recipeKey,type RecipeData } from '../lib/cocktailImport'
import './TrainingPage.css'
type Recipe={id:string;version:number;data:RecipeData}
const defaults=['Classic Cocktails',"JusTini's Signatures",'Pre-Fall Cocktails','Holiday Cocktails','Shots & Other Builds']
const sample=`Name: Cocktail name\nCategory: JusTini's Signatures\nIngredients:\nPaste exact quantities and ingredients here\nMethod: Paste the build instructions here\nGlassware: Glass name\nGarnish: Garnish details\n---\nName: Next cocktail\nIngredients:\nPaste the next recipe here`
function Dialog({busy,onClose,children}:PropsWithChildren<{busy:boolean;onClose:()=>void}>){const ref=useRef<HTMLDialogElement>(null),close=useRef(onClose),locked=useRef(busy);close.current=onClose;locked.current=busy;useEffect(()=>{const d=ref.current;if(!d)return;d.showModal();const cancel=(e:Event)=>{e.preventDefault();if(!locked.current)close.current()};d.addEventListener('cancel',cancel);return()=>{d.removeEventListener('cancel',cancel);d.close()}},[]);return <dialog ref={ref} className="training-dialog" aria-labelledby="training-dialog-title"><button type="button" className="training-close" disabled={busy} onClick={onClose} aria-label="Close recipe window">×</button>{children}</dialog>}
function Fields({value,onChange,categories,disabled=false}:{value:RecipeData;onChange:(r:RecipeData)=>void;categories:string[];disabled?:boolean}){const listId=useId();return <fieldset disabled={disabled}><label><ScreenText id="CocktailTrainingPage.954aa1ceafa5e440">Cocktail name</ScreenText><input maxLength={160} value={value.name} onChange={e=>onChange({...value,name:e.target.value})}/></label><label><ScreenText id="CocktailTrainingPage.ec91ec64e56c47d3">Category</ScreenText><input list={listId} maxLength={80} value={value.category} onChange={e=>onChange({...value,category:e.target.value})}/></label><datalist id={listId}>{categories.map(c=><option key={c}>{c}</option>)}</datalist>{([['build','Ingredients and measurements'],['method','Build / preparation'],['finish','Glassware, rim and garnish'],['notes','Notes']] as const).map(([key,label])=><label key={key}>{label}<textarea maxLength={12000} rows={key==='build'?6:3} value={value[key]} onChange={e=>onChange({...value,[key]:e.target.value})}/></label>)}</fieldset>}
export function CocktailTrainingPage(){
 const [location,setLocation]=useState(''),[recipes,setRecipes]=useState<Recipe[]>([]),[gm,setGm]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[success,setSuccess]=useState('')
 const [category,setCategory]=useState('All'),[search,setSearch]=useState(''),[mode,setMode]=useState<'view'|'edit'|'bulk'|null>(null),[selected,setSelected]=useState<Recipe|null>(null),[draft,setDraft]=useState<RecipeData>(emptyRecipe()),[busy,setBusy]=useState(false)
 const [paste,setPaste]=useState(''),[bulkCategory,setBulkCategory]=useState("JusTini's Signatures"),[preview,setPreview]=useState<RecipeData[]>([]),[modalError,setModalError]=useState(''),saving=useRef(false)
 async function reload(id=location){const r=await supabase.rpc('training_cocktails_load',{p_location_id:id});if(r.error)throw r.error;setRecipes(r.data??[])}
 useEffect(()=>{let live=true;void(async()=>{try{const t=await loadTenantData();if(!live)return;const id=t.locations[0]?.id;if(!id)throw Error('No active location.');setLocation(id);const [r,a]=await Promise.all([supabase.rpc('training_cocktails_load',{p_location_id:id}),supabase.rpc('closeout_is_gm',{p_location_id:id})]);if(!live)return;if(r.error)throw r.error;setRecipes(r.data??[]);setGm(!a.error&&a.data===true);if(a.error)setError(a.error.message)}catch(e){if(live)setError(String((e as Error).message??e))}finally{if(live)setLoading(false)}})();return()=>{live=false}},[])
 const categories=Array.from(new Set([...defaults,...recipes.map(r=>r.data.category)]))
 const norm=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[’']/g,'')
 const visible=recipes.filter(r=>(category==='All'||r.data.category===category)&&norm(r.data.name).includes(norm(search)))
 function close(){if(!busy){setMode(null);setModalError('')}}
 async function save(rows:RecipeData[],edit?:Recipe|null){if(saving.current)return;setModalError('');if(rows.some(r=>!r.name.trim()||!r.category.trim())){setModalError('Every recipe needs a name and category.');return}const names=rows.map(r=>recipeKey(r.name));if(new Set(names).size!==names.length){setModalError('Remove duplicate names in this batch.');return}const conflict=rows.find(r=>recipes.some(x=>x.id!==edit?.id&&recipeKey(x.data.name)===recipeKey(r.name)));if(conflict){setModalError('Already saved: '+conflict.name+'. Open that recipe and choose Edit.');return}saving.current=true;setBusy(true);try{const r=await supabase.rpc('training_cocktails_save',{p_location_id:location,p_recipes:rows.map(data=>({id:edit?.id??null,version:edit?.version??null,data}))});if(r.error)throw r.error;setMode(null);setSuccess(rows.length===1?'Recipe saved.':rows.length+' recipes saved.');setError('');setPaste('');setPreview([]);try{await reload()}catch{setError('Recipes saved. Could not refresh the list; use Refresh recipes.')}}catch(e){setModalError(String((e as Error).message??e))}finally{saving.current=false;setBusy(false)}}
 return <section className="page training-page"><Link to="/training"><ScreenText id="CocktailTrainingPage.9961ffcf77724e8c">← Training guides</ScreenText></Link><h1><ScreenText id="CocktailTrainingPage.fe36bab043706cc1">Cocktails</ScreenText></h1><p><ScreenText id="CocktailTrainingPage.f4bcc08158decc22">Recipes and builds</ScreenText></p>{error&&<p role="alert">{error}</p>}{success&&<p role="status">{success}</p>}{loading&&<p role="status"><ScreenText id="CocktailTrainingPage.d66fe1289f7128be">Loading recipes…</ScreenText></p>}<div className="training-actions">{gm&&<><button disabled={busy} onClick={()=>{setSelected(null);setDraft(emptyRecipe(category==='All'?undefined:category));setModalError('');setMode('edit')}}><ScreenText id="CocktailTrainingPage.64dc003d5e5dd579">Add cocktail</ScreenText></button><button disabled={busy} onClick={()=>{setModalError('');setMode('bulk')}}><ScreenText id="CocktailTrainingPage.ab3da913221ff8f0">Paste recipes</ScreenText></button></>}<button disabled={loading||busy||!location} onClick={()=>{setError('');void reload().catch(e=>setError(String((e as Error).message??e)))}}><ScreenText id="CocktailTrainingPage.2a9b39a80601fed7">Refresh recipes</ScreenText></button></div>
 <label><ScreenText id="CocktailTrainingPage.9fa3ce0fbc67fdea">Search cocktail name</ScreenText><input type="search" placeholder="Search a cocktail…" value={search} onChange={e=>setSearch(e.target.value)}/></label><div className="training-categories" aria-label="Cocktail categories">{['All',...categories].map(c=><button key={c} aria-pressed={category===c} onClick={()=>setCategory(c)}>{c} ({recipes.filter(r=>c==='All'||r.data.category===c).length})</button>)}</div>
 {!loading&&!visible.length&&<p><ScreenText id="CocktailTrainingPage.d389c2c62835d060">No cocktails found in this category.</ScreenText></p>}<div className="training-grid">{visible.map(r=><button className="training-recipe" key={r.id} onClick={()=>{setSelected(r);setModalError('');setMode('view')}}><strong>{r.data.name}</strong><span>{r.data.category}</span>{!r.data.build.trim()&&<small><ScreenText id="CocktailTrainingPage.a5b31cce7888b438">Measurements not yet entered</ScreenText></small>}</button>)}</div>
 {mode&&<Dialog busy={busy} onClose={close}>{modalError&&<p role="alert">{modalError}</p>}{mode==='view'&&selected&&<><h2 id="training-dialog-title">{selected.data.name}</h2><p>{selected.data.category}</p>{([['build','Ingredients and measurements'],['method','Build / preparation'],['finish','Glassware, rim and garnish'],['notes','Notes']] as const).map(([key,label])=><section key={key}><h3>{label}</h3><p className="training-text">{selected.data[key]||'Not entered in the stored recipe.'}</p></section>)}{gm&&<button className="primary-button" onClick={()=>{setDraft({...selected.data});setMode('edit')}}><ScreenText id="CocktailTrainingPage.0d2ae959b04d52a5">Edit recipe</ScreenText></button>}</>}
 {mode==='edit'&&<><h2 id="training-dialog-title">{selected?'Edit recipe':'Add cocktail'}</h2><Fields value={draft} onChange={setDraft} categories={categories} disabled={busy}/><button className="primary-button" disabled={busy} onClick={()=>void save([draft],selected)}>{busy?'Saving…':'Save recipe'}</button></>}
 {mode==='bulk'&&<><h2 id="training-dialog-title"><ScreenText id="CocktailTrainingPage.d1981becc69fc2ed">Paste cocktail recipes</ScreenText></h2><p><ScreenText id="CocktailTrainingPage.f9211cd1e012ff6f">Start each recipe with Name: or separate recipes with --- on its own line. Include Ingredients:, Method:, Glassware:, Garnish: and optional Notes:. Review and edit the preview before saving.</ScreenText></p><details><summary><ScreenText id="CocktailTrainingPage.78213954a1ec84f7">See paste format</ScreenText></summary><pre>{sample}</pre></details><label><ScreenText id="CocktailTrainingPage.7d9fecb17b338274">Default category</ScreenText><input disabled={busy} value={bulkCategory} onChange={e=>{setBulkCategory(e.target.value);setPreview([])}}/></label><label><ScreenText id="CocktailTrainingPage.eb810ed6ae653881">Paste recipes</ScreenText><textarea rows={10} maxLength={500000} disabled={busy} value={paste} onChange={e=>{setPaste(e.target.value);setPreview([])}}/></label><button disabled={busy} onClick={()=>{try{setPreview(parseCocktails(paste,bulkCategory));setModalError('')}catch(e){setPreview([]);setModalError(String((e as Error).message))}}}><ScreenText id="CocktailTrainingPage.303cf347409ef820">Preview recipes</ScreenText></button>{preview.length>0&&<><h3>{preview.length}<ScreenText id="CocktailTrainingPage.95967a9d9903820f"> recipes to add</ScreenText></h3>{preview.map((r,i)=><details key={i} open={preview.length===1}><summary>{i+1}. {r.name} · {r.category}</summary><Fields value={r} onChange={next=>setPreview(v=>v.map((x,j)=>j===i?next:x))} categories={categories} disabled={busy}/><button disabled={busy} onClick={()=>setPreview(v=>v.filter((_,j)=>j!==i))}><ScreenText id="CocktailTrainingPage.3f9a032b5a6fb886">Remove from import</ScreenText></button></details>)}<button className="primary-button" disabled={busy} onClick={()=>void save(preview)}>{busy?'Saving…':'Save '+preview.length+' recipes'}</button></>}</>}
 </Dialog>}
 </section>
}
