import { useCallback, useEffect, useRef, useState } from 'react'
import { Link } from 'react-router-dom'
import QRCode from 'qrcode'
import { supabase } from '../lib/supabase'
import { loadTenantData } from '../lib/tenant'
import './GuestFeedback.css'
type Entry={id:string;category:string;message:string;visit_date:string|null;guest_name:string;email:string;phone:string;wants_reply:boolean;created_at:string;status:string;version:number}
export function GuestFeedbackInbox(){
 const [loc,setLoc]=useState(''),[key,setKey]=useState(''),[name,setName]=useState('JusTini’s'),[rows,setRows]=useState<Entry[]>([]),[qr,setQr]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[more,setMore]=useState(false),[filter,setFilter]=useState('all')
 const generation=useRef(0),saving=useRef(false)
 useEffect(()=>{let live=true;void loadTenantData().then(t=>{const l=t.locations[0];if(!l)throw Error('No active location found.');if(live){setLoc(l.id);setName(l.name)}}).catch(e=>{if(live){setError(e.message);setLoading(false)}});return()=>{live=false}},[])
 const load=useCallback(async(cursor?:Entry)=>{if(!loc)return;const seq=++generation.current;setLoading(true);setError('');try{const r=await supabase.rpc('guest_feedback_inbox',{p_location_id:loc,p_before:cursor?.created_at??null,p_before_id:cursor?.id??null});if(r.error)throw r.error;if(seq!==generation.current)return;setKey(r.data.key);const batch=r.data.rows as Entry[];setRows(prev=>cursor?[...prev,...batch.filter(x=>!prev.some(p=>p.id===x.id))]:batch);setMore(batch.length===100)}catch(e){if(seq===generation.current)setError((e as Error).message)}finally{if(seq===generation.current)setLoading(false)}},[loc])
 useEffect(()=>{void load();return()=>{generation.current++}},[load])
 const url=key?`https://justinis-nola.vercel.app/guest-feedback/${key}`:''
 useEffect(()=>{let live=true;setQr('');if(url)void QRCode.toDataURL(url,{width:900,margin:4,errorCorrectionLevel:'M'}).then(q=>{if(live)setQr(q)}).catch(e=>{if(live)setError(e.message)});return()=>{live=false}},[url])
 async function change(row:Entry,status:string){if(saving.current)return;saving.current=true;setBusy(true);setError('');try{const r=await supabase.rpc('guest_feedback_status',{p_location_id:loc,p_id:row.id,p_version:row.version,p_status:status});if(r.error)throw r.error;setRows(v=>v.map(x=>x.id===row.id?{...x,status,version:x.version+1}:x))}catch(e){setError((e as Error).message)}finally{saving.current=false;setBusy(false)}}
 function print(){const w=window.open('','_blank');if(!w){setError('Allow the print window to open, then try again.');return}w.document.title='Guest feedback QR sign';w.document.body.style.cssText='font-family:Arial,sans-serif;text-align:center;padding:40px;color:#422c21';const h=w.document.createElement('h1');h.textContent=name;const title=w.document.createElement('h2');title.textContent='We’d love to hear from you';const p=w.document.createElement('p');p.textContent='Scan to share comments, concerns, suggestions or compliments.';const img=w.document.createElement('img');img.alt='Guest feedback QR code';img.style.width='min(80vw,450px)';img.onload=()=>{w.focus();w.print()};img.src=qr;const note=w.document.createElement('p');note.textContent='No account needed. Contact details are optional.';const link=w.document.createElement('p');link.textContent=url;link.style.overflowWrap='anywhere';w.document.body.append(h,title,p,img,note,link)}
 const shown=rows.filter(r=>filter==='all'||r.status===filter)
 return <section className="page guest-feedback-inbox"><Link to="/settings">← Settings</Link><h1>Guest feedback</h1><p>Review guest comments, concerns, suggestions and compliments. Only managers can view submissions.</p>{error&&<p role="alert">{error}</p>}{url&&<section className="gf-qr" aria-label="Guest feedback QR code">{qr&&<img src={qr} alt="Scan to share guest feedback"/>}<div><h2>Guest feedback QR code</h2><p><a href={url} target="_blank" rel="noreferrer">Open guest form</a></p><label>Guest form link<input readOnly value={url} onFocus={e=>e.target.select()}/></label><div className="gf-actions"><button type="button" disabled={!qr} onClick={print}>Print QR sign</button>{qr&&<a href={qr} download="justinis-guest-feedback-qr.png">Download QR code</a>}</div></div></section>}<div className="gf-actions"><label>Show<select disabled={busy} value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All feedback</option><option value="new">New</option><option value="reviewed">Reviewed</option><option value="resolved">Resolved</option></select></label><button type="button" disabled={busy||loading} onClick={()=>void load()}>Refresh inbox</button></div>{loading&&<p role="status">Loading feedback…</p>}{!loading&&!shown.length&&<p>No {filter==='all'?'':filter+' '}feedback in the loaded submissions.</p>}{shown.map(r=><article className="gf-entry" key={r.id}><h2>{r.category.charAt(0).toUpperCase()+r.category.slice(1)} · {r.guest_name||'Name not provided'}</h2><p>Submitted {new Date(r.created_at).toLocaleString('en-US',{timeZone:'America/Chicago'})} Central{r.visit_date?` · Visit: ${r.visit_date}`:''}</p><p className="gf-message">{r.message}</p>{r.email&&<p>Email: {r.email}</p>}{r.phone&&<p>Phone: {r.phone}</p>}<p>{r.wants_reply?'Guest requested follow-up.':'No follow-up requested.'}</p><label>Status<select disabled={busy||loading} value={r.status} onChange={e=>void change(r,e.target.value)}><option value="new">New</option><option value="reviewed">Reviewed</option><option value="resolved">Resolved</option></select></label></article>)}{more&&<button disabled={loading||busy} type="button" onClick={()=>void load(rows[rows.length-1])}>Load older feedback</button>}</section>
}
