import { useEffect, useRef, useState } from 'react'
import { supabase } from '../lib/supabase'
import './GuestFeedback.css'
export function GuestFeedbackPage({publicKey}:{publicKey:string}) {
 const [location,setLocation]=useState('JusTini’s'),[ready,setReady]=useState(false),[error,setError]=useState(''),[sent,setSent]=useState(false),[busy,setBusy]=useState(false)
 const [category,setCategory]=useState('comment'),[message,setMessage]=useState(''),[date,setDate]=useState(''),[name,setName]=useState(''),[email,setEmail]=useState(''),[phone,setPhone]=useState(''),[reply,setReply]=useState(false),[website,setWebsite]=useState('')
 const request=useRef(''),saving=useRef(false)
 useEffect(()=>{let live=true;void(async()=>{try{if(!/^[0-9a-f-]{36}$/i.test(publicKey))throw Error('This feedback link is invalid. Please speak with a manager.');const r=await supabase.rpc('guest_feedback_config',{p_key:publicKey});if(r.error)throw r.error;if(!r.data?.enabled)throw Error('This feedback form is unavailable. Please speak with a manager.');if(live){setLocation(r.data.name);setReady(true)}}catch(e){if(live)setError((e as Error).message)}})();return()=>{live=false}},[publicKey])
 async function submit(e:React.FormEvent){e.preventDefault();if(saving.current)return;if(reply&&!email.trim()&&!phone.trim()){setError('Add an email address or phone number so we can reply.');return}saving.current=true;setBusy(true);setError('');try{request.current ||= crypto.randomUUID();const r=await supabase.rpc('guest_feedback_submit',{p_key:publicKey,p_request_id:request.current,p_content:{category,message,visit_date:date||null,name,email,phone,wants_reply:reply},p_website:website});if(r.error)throw r.error;setSent(true)}catch(e){setError((e as Error).message)}finally{saving.current=false;setBusy(false)}}
 return <main className="guest-feedback-form"><p className="eyebrow">{location}</p><h1>Comments, concerns &amp; feedback</h1>{sent?<section role="status"><h2>Thank you for sharing.</h2><p>Your feedback has been sent to our management team.</p>{reply&&<p>You requested a follow-up using the contact details you provided.</p>}</section>:<><p>Tell us about your experience. Your feedback helps us improve.</p><p>You can submit without your name or contact details. For a concern that needs attention during your visit, please speak with a manager.</p>{!ready&&!error&&<p role="status">Loading…</p>}{ready&&<form onSubmit={submit}><fieldset disabled={busy}><label>Feedback type<select value={category} onChange={e=>setCategory(e.target.value)}><option value="comment">Comment</option><option value="concern">Concern</option><option value="suggestion">Suggestion</option><option value="compliment">Compliment</option></select></label><label>Your feedback<textarea required rows={6} maxLength={5000} value={message} onChange={e=>setMessage(e.target.value)}/></label><label>Date of your visit (optional)<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Name (optional)<input autoComplete="name" maxLength={120} value={name} onChange={e=>setName(e.target.value)}/></label><label>Email (optional)<input type="email" autoComplete="email" maxLength={320} value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Phone (optional)<input type="tel" autoComplete="tel" maxLength={40} value={phone} onChange={e=>setPhone(e.target.value)}/></label><label className="gf-check"><input type="checkbox" checked={reply} onChange={e=>setReply(e.target.checked)}/>I would like management to follow up with me.</label><p>Contact details are used to respond to your feedback. This form does not sign you up for marketing.</p><label className="gf-trap" aria-hidden="true">Website<input tabIndex={-1} autoComplete="off" value={website} onChange={e=>setWebsite(e.target.value)}/></label><button className="primary-button" type="submit">{busy?'Sending…':'Send feedback'}</button></fieldset></form>}</>}{error&&<p role="alert">{error}</p>}</main>
}
