import { useEffect, useRef, useState } from 'react'
import { supabase } from '../lib/supabase'
import { loadTenantData } from '../lib/tenant'
import './InventoryPage.css'
type Line={brand:string;size:string;quantity:number}
type Sheet={id:string;submitted_at:string;employee:string;lines:Line[]}
const sizes=['1.75 L','1 L','750 mL','Pint']
const normalize=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[’']/g,'')
export function InventoryPage(){
 const [location,setLocation]=useState(''),[brands,setBrands]=useState<string[]>([]),[history,setHistory]=useState<Sheet[]>([])
 const [search,setSearch]=useState(''),[brand,setBrand]=useState(''),[size,setSize]=useState(''),[quantity,setQuantity]=useState('1'),[lines,setLines]=useState<Line[]>([])
 const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState('')
 const request=useRef<string|null>(null),saving=useRef(false)
 async function load(id:string){const r=await supabase.rpc('inventory_disposal_load',{p_location_id:id});if(r.error)throw r.error;setBrands(r.data?.brands??[]);setHistory(r.data?.history??[])}
 useEffect(()=>{let live=true;void(async()=>{try{const t=await loadTenantData();if(!live)return;const id=t.locations[0]?.id;if(!id)throw Error('No active location.');setLocation(id);const r=await supabase.rpc('inventory_disposal_load',{p_location_id:id});if(!live)return;if(r.error)throw r.error;setBrands(r.data?.brands??[]);setHistory(r.data?.history??[])}catch(e){if(live)setError(String((e as Error).message??e))}finally{if(live)setLoading(false)}})();return()=>{live=false}},[])
 function add(){setError('');const q=Number(quantity);if(!brands.includes(brand)||!sizes.includes(size)||!Number.isInteger(q)||q<1||q>10000){setError('Select a brand and size, then enter a whole-bottle quantity from 1 to 10000.');return}const old=lines.find(l=>l.brand===brand&&l.size===size);if(old&&old.quantity+q>10000){setError('Combined quantity exceeds 10000.');return}if(!old&&lines.length>=100){setError('Submit this sheet before adding more than 100 rows.');return}setLines(v=>old?v.map(l=>l.brand===brand&&l.size===size?{...l,quantity:l.quantity+q}:l):[...v,{brand,size,quantity:q}]);request.current=null;setBrand('');setSearch('');setSize('');setQuantity('1');setSuccess('')}
 async function submit(){if(saving.current||!lines.length)return;saving.current=true;setBusy(true);setError('');setSuccess('');request.current??=crypto.randomUUID();try{const r=await supabase.rpc('inventory_disposal_submit',{p_location_id:location,p_request_id:request.current,p_lines:lines});if(r.error)throw r.error;setLines([]);setBrand('');setSearch('');setSize('');setQuantity('1');request.current=null;setSuccess('Disposal sheet submitted.');try{await load(location)}catch{setError('Sheet saved. History could not refresh; use Refresh history.')}}catch(e){setError(String((e as Error).message??e))}finally{saving.current=false;setBusy(false)}}
 const matches=brands.filter(b=>normalize(b).includes(normalize(search)))
 return <section className="page inventory-page"><p className="eyebrow">Inventory</p><h1>Disposal count sheet</h1><p>Count disposed bottles by brand and size. Add each row, then submit the sheet.</p>{loading&&<p role="status">Loading bottle list…</p>}{error&&<p role="alert">{error}</p>}{success&&<p role="status">{success}</p>}
 {!loading&&brands.length>0&&<><fieldset disabled={busy} className="inventory-card"><legend>Add bottles</legend><label>Search brand<input type="search" value={search} placeholder="Search Hennessy, Tito’s…" onChange={e=>{setSearch(e.target.value);setBrand('')}}/></label><div className="inventory-matches" aria-label="Matching brands">{matches.slice(0,30).map(b=><button type="button" key={b} aria-pressed={brand===b} onClick={()=>setBrand(b)}>{b}</button>)}{!matches.length&&<p>No matching brand.</p>}{matches.length>30&&<p>Showing 30 of {matches.length}. Type more to narrow the list.</p>}</div><p><strong>Selected:</strong> {brand||'Choose a brand above'}</p><div className="inventory-inputs"><label>Bottle size<select value={size} onChange={e=>setSize(e.target.value)}><option value="">Choose size</option>{sizes.map(s=><option key={s}>{s}</option>)}</select></label><label>Number of bottles<input type="number" inputMode="numeric" min="1" max="10000" step="1" value={quantity} onChange={e=>setQuantity(e.target.value)}/></label></div><button type="button" className="primary-button" onClick={add}>Add to sheet</button></fieldset>
 <section className="inventory-card"><h2>This disposal sheet · {lines.reduce((n,l)=>n+l.quantity,0)} bottles</h2>{!lines.length&&<p>No bottles added yet.</p>}{lines.map((l,i)=><div className="inventory-row" key={l.brand+':'+l.size}><strong>{l.brand}<small>{l.size}</small></strong><label>Quantity<input disabled={busy} type="number" inputMode="numeric" min="1" max="10000" step="1" value={l.quantity||''} onChange={e=>{request.current=null;setLines(v=>v.map((x,j)=>j===i?{...x,quantity:Number(e.target.value)}:x))}}/></label><button type="button" disabled={busy} aria-label={'Remove '+l.brand+' '+l.size} onClick={()=>{request.current=null;setLines(v=>v.filter((_,j)=>j!==i))}}>Remove</button></div>)}<button className="primary-button" disabled={busy||!lines.length||lines.some(l=>!Number.isInteger(l.quantity)||l.quantity<1||l.quantity>10000)} onClick={()=>void submit()}>{busy?'Submitting…':'Submit disposal sheet'}</button></section></>}
 <section className="inventory-card"><h2>Disposal history</h2><p>Latest 50 submissions. Staff see their own sheets; managers see the team’s.</p><button disabled={busy||loading||!location} onClick={()=>{setError('');void load(location).catch(e=>setError(String((e as Error).message??e)))}}>Refresh history</button>{!loading&&!history.length&&<p>No disposal sheets submitted yet.</p>}{history.map(h=><details key={h.id}><summary>{new Date(h.submitted_at).toLocaleString('en-US',{timeZone:'America/Chicago',month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'})} CT · {h.employee} · {h.lines.reduce((n,l)=>n+l.quantity,0)} bottles</summary>{h.lines.map(l=><p key={l.brand+':'+l.size}>{l.brand} · {l.size} · {l.quantity} bottles</p>)}</details>)}</section></section>
}
