// page-designer-instrumented
import { PageWord, PageInput, PageOption } from "../components/PageDesign"
import { IncomingInventory } from '../components/IncomingInventory'
import { ScreenText } from "../components/ScreenText"
import { useEffect, useRef, useState } from 'react'
import { supabase } from '../lib/supabase'
import { loadTenantData } from '../lib/tenant'
import './InventoryPage.css'
type Line={brand:string;size:string;quantity:number}
type Sheet={id:string;submitted_at:string;employee:string;lines:Line[]}
const sizes=['1.75 L','1 L','750 mL','Pint']
const normalize=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[’']/g,'')
export function InventoryPage(){
 const [inventoryView,setInventoryView]=useState<'disposal'|'incoming'>('disposal')
 const [location,setLocation]=useState(''),[brands,setBrands]=useState<string[]>([]),[history,setHistory]=useState<Sheet[]>([])
 const [search,setSearch]=useState(''),[brand,setBrand]=useState(''),[size,setSize]=useState(''),[quantity,setQuantity]=useState('1'),[lines,setLines]=useState<Line[]>([])
 const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState('')
 const request=useRef<string|null>(null),saving=useRef(false)
 async function load(id:string){const r=await supabase.rpc('inventory_disposal_load',{p_location_id:id});if(r.error)throw r.error;setBrands(r.data?.brands??[]);setHistory(r.data?.history??[])}
 useEffect(()=>{let live=true;void(async()=>{try{const t=await loadTenantData();if(!live)return;const id=t.locations[0]?.id;if(!id)throw Error('No active location.');setLocation(id);const r=await supabase.rpc('inventory_disposal_load',{p_location_id:id});if(!live)return;if(r.error)throw r.error;setBrands(r.data?.brands??[]);setHistory(r.data?.history??[])}catch(e){if(live)setError(String((e as Error).message??e))}finally{if(live)setLoading(false)}})();return()=>{live=false}},[])
 async function addBrand(){if(saving.current)return;setError('');setSuccess('');const value=search.trim();if(!value||value.length>120){setError('Enter a brand name from 1 to 120 characters.');return}saving.current=true;setBusy(true);try{const result=await supabase.rpc('inventory_add_brand',{p_location_id:location,p_brand:value});if(result.error)throw result.error;const saved=String(result.data);setBrands(v=>Array.from(new Set([...v,saved])).sort((a,b)=>a.localeCompare(b)));setBrand(saved);setSearch(saved);setSuccess('Brand ready: '+saved+'. Choose its bottle size and quantity.')}catch(e){setError(String((e as Error).message??e))}finally{saving.current=false;setBusy(false)}}
 function add(){setError('');const q=Number(quantity);if(!brands.includes(brand)||!sizes.includes(size)||!Number.isInteger(q)||q<1||q>10000){setError('Select a brand and size, then enter a whole-bottle quantity from 1 to 10000.');return}const old=lines.find(l=>l.brand===brand&&l.size===size);if(old&&old.quantity+q>10000){setError('Combined quantity exceeds 10000.');return}if(!old&&lines.length>=100){setError('Submit this sheet before adding more than 100 rows.');return}setLines(v=>old?v.map(l=>l.brand===brand&&l.size===size?{...l,quantity:l.quantity+q}:l):[...v,{brand,size,quantity:q}]);request.current=null;setBrand('');setSearch('');setSize('');setQuantity('1');setSuccess('')}
 async function submit(){if(saving.current||!lines.length)return;saving.current=true;setBusy(true);setError('');setSuccess('');request.current??=crypto.randomUUID();try{const r=await supabase.rpc('inventory_disposal_submit',{p_location_id:location,p_request_id:request.current,p_lines:lines});if(r.error)throw r.error;setLines([]);setBrand('');setSearch('');setSize('');setQuantity('1');request.current=null;setSuccess('Disposal sheet submitted.');try{await load(location)}catch{setError('Sheet saved. History could not refresh; use Refresh history.')}}catch(e){setError(String((e as Error).message??e))}finally{saving.current=false;setBusy(false)}}
 const matches=brands.filter(b=>normalize(b).includes(normalize(search)))
 return <><nav data-design-block="copy.8a39622f6fa51722.1" className="inventory-tabs page" aria-label="Inventory views"><button data-design-block="copy.1a5790e683f9e0ce.1" type="button" aria-pressed={inventoryView==='disposal'} onClick={()=>{if(inventoryView!=='incoming'||window.confirm('Leave incoming receipts? Unsaved edits will be lost.'))setInventoryView('disposal')}}><PageWord id="copy.6c779b9b75858d56.1">Disposal</PageWord></button><button data-design-block="copy.a48f5aa3827ed6b4.1" type="button" aria-pressed={inventoryView==='incoming'} onClick={()=>setInventoryView('incoming')}><PageWord id="copy.9e71549f0f7ace6d.1">Incoming receipts &amp; report</PageWord></button></nav>{inventoryView==='incoming'?<div data-design-block="copy.a53d485432bce981.1" className="page"><IncomingInventory locationId={location} brands={brands}/></div>:<section data-design-block="copy.51cd521a492edc4f.1" className="page inventory-page"><p data-design-block="copy.286b4e98a09ecabd.1" className="eyebrow"><ScreenText id="InventoryPage.f1388b1e9e607a7f">Inventory</ScreenText></p><h1 data-design-block="copy.8247a74b0502cc67.1"><ScreenText id="InventoryPage.877871e7737c481b">Disposal count sheet</ScreenText></h1><p data-design-block="copy.59cf20c5bab3f134.1"><ScreenText id="InventoryPage.e56348a60ab39eae">Count disposed bottles by brand and size. Add each row, then submit the sheet.</ScreenText></p>{loading&&<p data-design-block="copy.3adacc56dfb3129a.1" role="status"><ScreenText id="InventoryPage.c136c4415c67a5bd">Loading bottle list…</ScreenText></p>}{error&&<p data-design-block="copy.9ccd15062aa3537e.1" role="alert">{error}</p>}{success&&<p data-design-block="copy.3adacc56dfb3129a.2" role="status">{success}</p>}
 {!loading&&brands.length>0&&<><fieldset data-design-block="copy.52da262b68052eba.1" disabled={busy} className="inventory-card"><legend><ScreenText id="InventoryPage.5e7b14563da8af72">Add bottles</ScreenText></legend><label data-design-block="copy.0ed611ec15f74c6c.1"><ScreenText id="InventoryPage.8f8837fa6222b9dc">Search brand</ScreenText><PageInput designId="copy.62ec6185c280b9f4.1" type="search" value={search} placeholder="Search Hennessy, Tito’s…" onChange={e=>{setSearch(e.target.value);setBrand('')}}/></label><button data-design-block="copy.f3e74a40b4d08ea4.1" type="button" disabled={busy||!search.trim()||search.trim().length>120} onClick={()=>void addBrand()}><ScreenText id="InventoryPage.61345857e8f7eb6a">Add new brand: </ScreenText>{search.trim()||'type a name above'}</button><p data-design-block="copy.303fbd476850cbf7.1" className="muted"><ScreenText id="InventoryPage.4947e0894fa46886">New brands are saved for everyone. Existing names are reused automatically.</ScreenText></p><div data-design-block="copy.94fff43e70d2f8a3.1" className="inventory-matches" aria-label="Matching brands">{matches.slice(0,30).map(b=><button data-design-block="copy.4c2408addbd354be.1" type="button" key={b} aria-pressed={brand===b} onClick={()=>setBrand(b)}>{b}</button>)}{!matches.length&&<p data-design-block="copy.59cf20c5bab3f134.2"><ScreenText id="InventoryPage.f60bc09db782540c">No matching brand.</ScreenText></p>}{matches.length>30&&<p data-design-block="copy.59cf20c5bab3f134.3"><ScreenText id="InventoryPage.133b445ffb0c1316">Showing 30 of </ScreenText>{matches.length}<ScreenText id="InventoryPage.1bd1b34a136f9b40">. Type more to narrow the list.</ScreenText></p>}</div><p data-design-block="copy.59cf20c5bab3f134.4"><strong><ScreenText id="InventoryPage.6ad2b3a42ad2c574">Selected:</ScreenText></strong> {brand||'Choose a brand above'}</p><div data-design-block="copy.7d507e339ddc75e6.1" className="inventory-inputs"><label data-design-block="copy.0ed611ec15f74c6c.2"><ScreenText id="InventoryPage.df6341ce22682293">Bottle size</ScreenText><select value={size} onChange={e=>setSize(e.target.value)}><PageOption designId="copy.439bc8ec2542cc91.1" value=""><ScreenText plain id="InventoryPage.4e7a1f4d1ed94ebd">Choose size</ScreenText></PageOption>{sizes.map(s=><option key={s}>{s}</option>)}</select></label><label data-design-block="copy.0ed611ec15f74c6c.3"><ScreenText id="InventoryPage.996a62ac5c0e7f18">Number of bottles</ScreenText><input type="number" inputMode="numeric" min="1" max="10000" step="1" value={quantity} onChange={e=>setQuantity(e.target.value)}/></label></div><button data-design-block="copy.763057c509bfc7e5.1" type="button" className="primary-button" onClick={add}><ScreenText id="InventoryPage.3463d996700a8348">Add to sheet</ScreenText></button></fieldset>
 <section data-design-block="copy.4b3db96f23207d1a.1" className="inventory-card"><h2 data-design-block="copy.add66cc0ed1c800d.1"><ScreenText id="InventoryPage.b6f753efd8ebd9b0">This disposal sheet · </ScreenText>{lines.reduce((n,l)=>n+l.quantity,0)}<ScreenText id="InventoryPage.cde29e195cdb94ac"> bottles</ScreenText></h2>{!lines.length&&<p data-design-block="copy.59cf20c5bab3f134.5"><ScreenText id="InventoryPage.4e41b8ae6fc10242">No bottles added yet.</ScreenText></p>}{lines.map((l,i)=><div data-design-block="copy.d78fa0f1aeb8d81e.1" className="inventory-row" key={l.brand+':'+l.size}><strong>{l.brand}<small>{l.size}</small></strong><label data-design-block="copy.0ed611ec15f74c6c.4"><ScreenText id="InventoryPage.954bc5456284109a">Quantity</ScreenText><input disabled={busy} type="number" inputMode="numeric" min="1" max="10000" step="1" value={l.quantity||''} onChange={e=>{request.current=null;setLines(v=>v.map((x,j)=>j===i?{...x,quantity:Number(e.target.value)}:x))}}/></label><button data-design-block="copy.fd6c8347024978b7.1" type="button" disabled={busy} aria-label={'Remove '+l.brand+' '+l.size} onClick={()=>{request.current=null;setLines(v=>v.filter((_,j)=>j!==i))}}><ScreenText id="InventoryPage.db55c8214ffd0a15">Remove</ScreenText></button></div>)}<button data-design-block="copy.dc17555293cc593f.1" className="primary-button" disabled={busy||!lines.length||lines.some(l=>!Number.isInteger(l.quantity)||l.quantity<1||l.quantity>10000)} onClick={()=>void submit()}>{busy?<PageWord id="copy.0b088f6119b70817.1">{"Submitting…"}</PageWord>:<PageWord id="copy.aaf4a8580b5ba83d.1">{"Submit disposal sheet"}</PageWord>}</button></section></>}
 <section data-design-block="copy.4b3db96f23207d1a.2" className="inventory-card"><h2 data-design-block="copy.add66cc0ed1c800d.2"><ScreenText id="InventoryPage.9d0554f279f2d151">Disposal history</ScreenText></h2><p data-design-block="copy.59cf20c5bab3f134.6"><ScreenText id="InventoryPage.c0e09aabe6f9ff69">Latest 50 submissions. Staff see their own sheets; managers see the team’s.</ScreenText></p><button data-design-block="copy.d1b74f2e155eaf98.1" disabled={busy||loading||!location} onClick={()=>{setError('');void load(location).catch(e=>setError(String((e as Error).message??e)))}}><ScreenText id="InventoryPage.3c5028af23e122e5">Refresh history</ScreenText></button>{!loading&&!history.length&&<p data-design-block="copy.59cf20c5bab3f134.7"><ScreenText id="InventoryPage.88fd4f1e2a9b807b">No disposal sheets submitted yet.</ScreenText></p>}{history.map(h=><details key={h.id}><summary>{new Date(h.submitted_at).toLocaleString('en-US',{timeZone:'America/Chicago',month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'})}<ScreenText id="InventoryPage.54fb228b545587eb"> CT · </ScreenText>{h.employee}<PageWord id="copy.5c03d32ef80c2cbb.1">· </PageWord>{h.lines.reduce((n,l)=>n+l.quantity,0)}<ScreenText id="InventoryPage.613175b626e8fce1"> bottles</ScreenText></summary>{h.lines.map(l=><p data-design-block="copy.e1d8bc8650426c18.1" key={l.brand+':'+l.size}>{l.brand}<PageWord id="copy.5c03d32ef80c2cbb.2">· </PageWord>{l.size}<PageWord id="copy.5c03d32ef80c2cbb.3">· </PageWord>{l.quantity}<ScreenText id="InventoryPage.4985eb7e89b7fe1d"> bottles</ScreenText></p>)}</details>)}</section></section>}</>
}

