// page-designer-instrumented
import { PageWord } from "../components/PageDesign"
import type { GeneratedQuiz } from '../lib/generatedQuiz'
import { ScreenText } from "../components/ScreenText"
import { QuizUpload } from '../components/QuizUpload'
import { QuizRequiredStaff } from '../components/QuizRequiredStaff'
import { submissionLabel } from '../lib/submissionTime'
import { PublishedQuizzes } from '../components/PublishedQuizzes'
import type { PublishedQuiz } from '../components/PublishedQuizzes'
import { QuizQuestionBank } from '../components/QuizQuestionBank'
import { useEffect, useRef, useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { supabase } from '../lib/supabase'
import { loadTenantData } from '../lib/tenant'
import { quizToday, quizTomorrow, quizError } from './QuizzesPage'
import type { Quiz, Question, QuizResult } from './QuizzesPage'
import './QuizzesPage.css'
import './QuizWorkspace.css'
type Submission={user_id:string;name:string;submitted_at:string;result:QuizResult}
type DraftQuestion=Question&{editorKey:string}
const draftQuestion=(q:Question):DraftQuestion=>({...q,options:[...q.options],editorKey:crypto.randomUUID()})
const emptyQuestion=():DraftQuestion=>draftQuestion({prompt:'',category:'Guest service',options:['','','',''],correct:0,explanation:''})
export function QuizBuilderPage({publishedView=false,initialDate,generatedDraft}:{publishedView?:boolean;initialDate?:string;generatedDraft?:GeneratedQuiz}) {
 const [params]=useSearchParams()
 const [location,setLocation]=useState('')
 const [date,setDate]=useState(()=>{const d=initialDate??params.get('date')??'';return publishedView?(/^\d{4}-\d{2}-\d{2}$/.test(d) && d<=quizToday()?d:quizToday()):(/^\d{4}-\d{2}-\d{2}$/.test(d)&&d>=quizTomorrow()?d:quizTomorrow())})
 const [title,setTitle]=useState('Daily Pre-Shift Quiz')
 const [instructions,setInstructions]=useState('Read the pre-shift before answering. Choose one answer for each question.')
 const [questions,setQuestions]=useState<DraftQuestion[]>([])
 const [version,setVersion]=useState(0)
 const [quizId,setQuizId]=useState('')
 const [published,setPublished]=useState(false)
 const [results,setResults]=useState<Submission[]>([])
 const [busy,setBusy]=useState(true)
 const [dirty,setDirty]=useState(false)
 const [error,setError]=useState('')
 const [message,setMessage]=useState('')
 const [listRefresh,setListRefresh]=useState(0)
 const [editorReload,setEditorReload]=useState(0)
 const [addMenu,setAddMenu]=useState(false),[bankOpen,setBankOpen]=useState(false)
 const [generated,setGenerated]=useState<GeneratedQuiz|null>(null)
 const [loadFailed,setLoadFailed]=useState(false)
 useEffect(()=>{if(generatedDraft?.location===location&&generatedDraft.date===date)setGenerated(generatedDraft);else setGenerated(null)},[generatedDraft,location,date])
 function importGenerated(append:boolean){if(!generated||loadFailed)return;if(append&&questions.length+generated.questions.length>50){setError('A quiz can contain up to 50 questions.');return}if(!append&&questions.length&&!window.confirm('Replace the current questions with generated questions? This stays unsaved until you save or publish.'))return;setQuestions(v=>append?[...v,...generated.questions.map(draftQuestion)]:generated.questions.map(draftQuestion));if(!append)setTitle(generated.title);setDirty(true);setRemoved(null);setGenerated(null);setMessage('Generated questions added. Review the answers, edit, or add bank questions before saving or publishing.')}
 const [removed,setRemoved]=useState<{question:DraftQuestion;index:number}|null>(null)
 const chooser=useRef<HTMLDivElement>(null),bankPanel=useRef<HTMLDivElement>(null)
 function chooseAdd(){setAddMenu(true);requestAnimationFrame(()=>chooser.current?.scrollIntoView({behavior:'smooth',block:'center'}))}
 function writeQuestion(){const q=emptyQuestion();setQuestions(v=>v.length<50?[...v,q]:v);setDirty(true);setAddMenu(false);requestAnimationFrame(()=>{const field=document.getElementById('quiz-question-'+q.editorKey);field?.scrollIntoView({behavior:'smooth',block:'center'});field?.focus()})}
 function browseBank(){setBankOpen(true);setAddMenu(false);requestAnimationFrame(()=>bankPanel.current?.scrollIntoView({behavior:'smooth',block:'start'}))}
 function removeQuestion(q:DraftQuestion,index:number){setQuestions(v=>v.filter(x=>x.editorKey!==q.editorKey));setRemoved({question:q,index});setDirty(true);setMessage('Question removed. Save the quiz to keep this change.')}
 function undoRemove(){if(!removed||questions.length>=50)return;const item=removed;setQuestions(v=>{const next=[...v];next.splice(Math.min(item.index,next.length),0,item.question);return next});setRemoved(null);setDirty(true);setMessage('Question restored.')}

 function apply(q:Quiz|null){setQuizId(q?.id ?? '');setTitle(q?.title ?? 'Daily Pre-Shift Quiz');setInstructions(q?.instructions ?? 'Read the pre-shift before answering. Choose one answer for each question.');setQuestions((q?.questions ?? []).map(draftQuestion));setRemoved(null);setAddMenu(false);setBankOpen(false);setVersion(q?.version ?? 0);setPublished(q?.published ?? false);setDirty(false)}
 useEffect(()=>{let live=true;void loadTenantData().then(t=>{if(!t.locations[0])throw new Error('No active location.');if(live)setLocation(t.locations[0].id)}).catch(e=>{if(live){setError(quizError(e));setBusy(false)}});return()=>{live=false}},[])
 useEffect(()=>{if(!location)return;let live=true;setBusy(true);setLoadFailed(false);setError('');setMessage('');apply(null);setResults([]);void supabase.rpc('quiz_manager_load',{p_location_id:location,p_date:date}).then(({data,error})=>{if(!live)return;if(error){setLoadFailed(true);setError(error.message)}else{apply(data.quiz);setResults(data.results)}setBusy(false)});return()=>{live=false}},[location,date,editorReload])
 function update(i:number,patch:Partial<Question>){setQuestions(q=>q.map((x,n)=>n===i?{...x,...patch}:x));setDirty(true)}
 function move(i:number,delta:number){setQuestions(q=>{const next=[...q];[next[i],next[i+delta]]=[next[i+delta],next[i]];return next});setDirty(true)}
 async function save(publish:boolean){if(!publishedView && date<quizTomorrow()){setError('Choose a future date. Manage today’s quiz from the main Quizzes page.');return}setBusy(true);setError('');setMessage('');try{
  const {data,error}=await supabase.rpc('quiz_manager_save',{p_location_id:location,p_date:date,p_title:title,p_instructions:instructions,p_questions:questions.map(({editorKey,...question})=>question),p_publish:publish,p_version:version});if(error)throw error;apply(data);setListRefresh(v=>v+1);setMessage(publish?(publishedView?'Published changes saved.':'Quiz scheduled. Staff can open it on its quiz date.'):'Draft saved. Staff cannot see it.')
 }catch(e){setError(quizError(e))}finally{setBusy(false)}}
 function openPublished(nextDate:string){if(dirty && !window.confirm('Discard unsaved edits and open this published quiz?'))return;setDate(nextDate);setEditorReload(v=>v+1)}
 async function removePublished(q:PublishedQuiz){
  if(!window.confirm('Remove "'+q.title+'" ('+q.quiz_date+') from staff access? Submissions will be preserved and the quiz saved as a draft.'+(q.quiz_date===date && dirty?' Unsaved edits to this quiz will be discarded.':'')))return
  setBusy(true);setError('');setMessage('')
  try{const {error}=await supabase.rpc('quiz_manager_remove',{p_location_id:location,p_quiz_id:q.id,p_version:q.version});if(error)throw error;setListRefresh(v=>v+1);if(q.quiz_date===date)setEditorReload(v=>v+1);else setMessage('Quiz removed from staff access. Its draft and submissions are preserved.')}
  catch(e){setError(quizError(e))}finally{setBusy(false)}
 }
 return <section data-design-block="copy.f39580c9aab2971b.1" className="mod-page quiz-page quiz-workspace">{!generatedDraft&&<Link to="/quizzes"><ScreenText id="QuizBuilderPage.32eaee06d35ddfd4">← Daily Quizzes</ScreenText></Link>}<p data-design-block="copy.21358c24ddf899aa.1" className="eyebrow"><ScreenText id="QuizBuilderPage.0af9d71bf594c489">Manager only</ScreenText></p><h1 data-design-block="copy.9f47d107c65115b0.1">{generatedDraft?<PageWord id="copy.6c951ad6313a989e.1">{"Review Pre-Shift Quiz"}</PageWord>:publishedView?<PageWord id="copy.7abbf576d16e350f.1">{"Manage Published Quiz"}</PageWord>:<PageWord id="copy.b5c6536c9b262505.1">{"Build Future Quizzes"}</PageWord>}</h1>
 {!publishedView && !generatedDraft && <PublishedQuizzes future location={location} refresh={listRefresh} disabled={busy || !location} onEdit={openPublished} onRemove={removePublished} />}
 <label data-design-block="copy.8fdec42675f04be7.1"><ScreenText id="QuizBuilderPage.991e62629f7eca0d">Quiz date</ScreenText><input type="date" min={publishedView?undefined:quizTomorrow()} max={publishedView?quizToday():undefined} value={date} disabled={busy||!!generatedDraft} onChange={e=>{if(!e.target.value || (!publishedView && e.target.value<quizTomorrow()) || (publishedView && e.target.value>quizToday()) || (dirty && !window.confirm('Discard unsaved edits and open another date?')))return;setDate(e.target.value)}} /></label>
 <p data-design-block="copy.4b1d0894fdd167e3.1">{published?(publishedView?<PageWord id="copy.36e0ddf7d4bfafbc.1">{"Published"}</PageWord>:<PageWord id="copy.c6b226e24d7146e1.1">{"Scheduled"}</PageWord>):<PageWord id="copy.5db2d5271f2bf8ff.1">{"Draft"}</PageWord>}{dirty?<PageWord id="copy.f8723e5dd96575be.1">{" · Unsaved changes"}</PageWord>:<PageWord id="copy.e71f644adc6685f7.1">{""}</PageWord>}</p>
 {results.length>0 && <p data-design-block="copy.4b1d0894fdd167e3.2"><ScreenText id="QuizBuilderPage.dd808b7daad09bdf">Existing scores and submitted answers are preserved. Edits apply to staff who have not submitted. Staff who already submitted cannot retake this quiz.</ScreenText></p>}
 {error && <p data-design-block="copy.2573020f29ce20d3.1" role="alert">{error}</p>}{message && <p data-design-block="copy.d3d2b58e8fea89db.1" role="status">{message}</p>}{busy && <p data-design-block="copy.4b1d0894fdd167e3.3"><ScreenText id="QuizBuilderPage.24102437495319ff">Loading…</ScreenText></p>}
 <div data-design-block="copy.abbac5e4fd73ea0d.1">{generated&&<article data-design-block="copy.36458728857aec54.1" className="mod-review"><h2 data-design-block="copy.c86fd29e94d26d29.1"><PageWord id="copy.4442964364fd16e2.1">Generated from your pre-shift · </PageWord>{generated.date}</h2><p data-design-block="copy.4b1d0894fdd167e3.4">{generated.questions.length}<PageWord id="copy.4d03e828c5650b30.1">questions ready. Nothing has been saved or published.</PageWord></p>{generated.warnings.map((w,i)=><p data-design-block="copy.65df9010e0d4a005.1" key={i}>{w}</p>)}<div data-design-block="copy.6825e010cc4f0660.1" className="quiz-actions"><button data-design-block="copy.25ce259fab272a9c.1" type="button" disabled={busy||loadFailed||!location||questions.length+generated.questions.length>50} onClick={()=>importGenerated(true)}><PageWord id="copy.59a8c4261b51a832.1">Add generated questions</PageWord></button><button data-design-block="copy.a29ee1645ceee791.1" type="button" disabled={busy||loadFailed||!location} onClick={()=>importGenerated(false)}>{questions.length?<PageWord id="copy.3dc74c46f7540667.1">{"Replace current questions"}</PageWord>:<PageWord id="copy.d14abe7062adb344.1">{"Use generated questions"}</PageWord>}</button><button data-design-block="copy.88dc1b5194e3366d.1" type="button" onClick={()=>setGenerated(null)}><PageWord id="copy.f30c835121ca1d47.1">Discard generated questions</PageWord></button></div></article>}</div>
 <QuizUpload disabled={busy || !location} date={date} onApply={(upload,append)=>{if(append && questions.length+upload.questions.length>50){setMessage('Choose fewer questions. A quiz can contain up to 50.');return false}if(!append && questions.length && !window.confirm('Replace the current questions? Saved submissions stay unchanged.'))return false;setQuestions(v=>append?[...v,...upload.questions.map(draftQuestion)]:upload.questions.map(draftQuestion));setRemoved(null);if(!append){if(upload.title)setTitle(upload.title);if(upload.instructions)setInstructions(upload.instructions)}setDirty(true);setMessage('Questions loaded. Review and edit them below, then save or publish.');return true}} />
 <div data-design-block="copy.6ffb4744922a032d.1" ref={bankPanel}><QuizQuestionBank location={location} open={bankOpen} onOpenChange={setBankOpen} disabled={busy || !location} questions={questions} onAdd={items=>{setQuestions(v=>[...v,...items.map(draftQuestion)].slice(0,50));setDirty(true);setMessage(`${items.length} questions added from the bank. Save the quiz to keep them.`)}} /></div>
 <fieldset data-design-block="copy.ee32535b9c575791.1" disabled={busy || !location || loadFailed} className="quiz-editor">
 <details className="quiz-settings"><summary><ScreenText id="QuizBuilderPage.a2bfec93d4dd8f87">Quiz title and instructions</ScreenText></summary>
 <label data-design-block="copy.8fdec42675f04be7.2"><ScreenText id="QuizBuilderPage.2e0e8391cff492df">Title</ScreenText><input maxLength={200} value={title} onChange={e=>{setTitle(e.target.value);setDirty(true)}} /></label>
 <label data-design-block="copy.8fdec42675f04be7.3"><ScreenText id="QuizBuilderPage.3b9de671dedb8bb7">Instructions</ScreenText><textarea maxLength={4000} value={instructions} onChange={e=>{setInstructions(e.target.value);setDirty(true)}} /></label>
 </details>
 <div data-design-block="copy.deaf213c5ec827f2.1" className="quiz-list-heading"><h2 data-design-block="copy.c86fd29e94d26d29.2"><ScreenText id="QuizBuilderPage.01405b24586d6e78">Questions (</ScreenText>{questions.length}<PageWord id="copy.701fd532ee49d653.1">/50)</PageWord></h2><p data-design-block="copy.4b1d0894fdd167e3.5"><ScreenText id="QuizBuilderPage.eeabc641c78873eb">Add an existing question from the bank or write a new one. Open “Edit answers” to change the choices.</ScreenText></p><button data-design-block="copy.66979413089889e4.1" type="button" disabled={questions.length>=50} onClick={chooseAdd}><ScreenText id="QuizBuilderPage.c7f27a70beb66909">＋ Add question</ScreenText></button></div>
 <div data-design-block="copy.ad359e7aa31c487f.1" ref={chooser}>{addMenu&&<div data-design-block="copy.0f06e801aab4af83.1" className="mod-review" role="group" aria-label="Add a question"><h3 data-design-block="copy.6b8e8b1755d489dd.1"><ScreenText id="QuizBuilderPage.c084cf0fef6aff70">How would you like to add a question?</ScreenText></h3><div data-design-block="copy.6825e010cc4f0660.2" className="quiz-actions"><button data-design-block="copy.a819638dfa11eafc.1" type="button" disabled={questions.length>=50} onClick={writeQuestion}><ScreenText id="QuizBuilderPage.7fe9caf718563d6c">Write a question</ScreenText></button><button data-design-block="copy.0c1fc27b93ebc1ca.1" type="button" disabled={questions.length>=50} onClick={browseBank}><ScreenText id="QuizBuilderPage.c88824809acf0691">Choose from the bank</ScreenText></button><button data-design-block="copy.ec6b7ae8296d3a07.1" type="button" onClick={()=>setAddMenu(false)}><ScreenText id="QuizBuilderPage.ce7ffdd48895e09d">Cancel</ScreenText></button></div></div>}</div>
 {removed&&<div data-design-block="copy.9cf53117987d9a53.1" role="status" className="mod-review"><p data-design-block="copy.4b1d0894fdd167e3.6"><ScreenText id="QuizBuilderPage.bdd1413802ee2488">Removed: </ScreenText>{removed.question.prompt||'Blank question'}</p><button data-design-block="copy.4815a05e0a930726.1" type="button" disabled={questions.length>=50} onClick={undoRemove}><ScreenText id="QuizBuilderPage.b4ce5fa24d0e4d4b">Undo remove</ScreenText></button></div>}
 {questions.length===0 && <p data-design-block="copy.e14018af5aaceaf2.1" className="quiz-empty"><ScreenText id="QuizBuilderPage.a1d605c39123a595">Start with a new question or add questions from the bank.</ScreenText></p>}
 {questions.map((q,i)=><article data-design-block="copy.becb5ee4555c182f.1" className="mod-review quiz-edit-card" key={q.editorKey}><h3 data-design-block="copy.6b8e8b1755d489dd.2"><ScreenText id="QuizBuilderPage.0de4316cd9c3cc86">Question </ScreenText>{i+1}</h3>
 <label data-design-block="copy.8fdec42675f04be7.4"><ScreenText id="QuizBuilderPage.cb7f5ae7726ad176">Category</ScreenText><input list="quiz-categories" maxLength={100} value={q.category} onChange={e=>update(i,{category:e.target.value})} /></label>
 <label data-design-block="copy.8fdec42675f04be7.5"><ScreenText id="QuizBuilderPage.9c7affd46893b801">Question</ScreenText><textarea id={'quiz-question-'+q.editorKey} maxLength={2000} value={q.prompt} onChange={e=>update(i,{prompt:e.target.value})} /></label>
 <details className="quiz-answer-panel"><summary><ScreenText id="QuizBuilderPage.f837d06ddc8b2780">Edit answers · </ScreenText>{q.options.filter(o=>o.trim()).length}<ScreenText id="QuizBuilderPage.b78e8e03614c0ab6"> choices</ScreenText>{q.options[q.correct]?.trim()?<PageWord id="copy.fd9eb27dfb25b9ab.1">{" · Answer selected"}</PageWord>:<PageWord id="copy.442a5c7a75a7e0ab.1">{" · Add answers"}</PageWord>}</summary>
 {q.options.map((option,n)=><div data-design-block="copy.7b3ade91fd794d53.1" className="quiz-option-editor" key={n}><label data-design-block="copy.8fdec42675f04be7.6"><ScreenText id="QuizBuilderPage.d29585b1f43a2f3e">Choice </ScreenText>{n+1}<input maxLength={1000} value={option} onChange={e=>update(i,{options:q.options.map((o,j)=>j===n?e.target.value:o)})} /></label>
 <label data-design-block="copy.d7642c6e2948c4f1.1" className="quiz-choice"><input type="radio" name={`correct-${q.editorKey}`} checked={q.correct===n} onChange={()=>update(i,{correct:n})} /><ScreenText id="QuizBuilderPage.79c0c149b771ac44">Correct answer</ScreenText></label>
 {q.options.length>2 && <button data-design-block="copy.4644204e77dad0c9.1" type="button" onClick={()=>update(i,{options:q.options.filter((_,j)=>j!==n),correct:q.correct===n?0:q.correct>n?q.correct-1:q.correct})}><ScreenText id="QuizBuilderPage.2ebcf179b77222f6">Remove choice</ScreenText></button>}
 </div>)}
 <div data-design-block="copy.6825e010cc4f0660.3" className="quiz-actions">{q.options.length<6 && <button data-design-block="copy.9a4a9a1b5b36326a.1" type="button" onClick={()=>update(i,{options:[...q.options,'']})}><ScreenText id="QuizBuilderPage.b6f477dab4c93dd2">Add choice</ScreenText></button>}
 <button data-design-block="copy.0234331cd926226f.1" type="button" onClick={()=>{if(window.confirm('Replace the choices with True and False?'))update(i,{options:['True','False'],correct:0})}}><ScreenText id="QuizBuilderPage.ef7fcc190b9529a8">Use True / False</ScreenText></button></div>
 <label data-design-block="copy.8fdec42675f04be7.7"><ScreenText id="QuizBuilderPage.b20aaa2b9784234c">Explanation shown after submission (optional)</ScreenText><textarea maxLength={2000} value={q.explanation} onChange={e=>update(i,{explanation:e.target.value})} /></label>
 </details>
 <div data-design-block="copy.80a348170bfd87f8.1" className="quiz-actions quiz-question-tools"><button data-design-block="copy.4e5e2594be0ce1f4.1" type="button" disabled={i===0} onClick={()=>move(i,-1)}><ScreenText id="QuizBuilderPage.3024bd24cc3c0304">Move up</ScreenText></button><button data-design-block="copy.6d92e9e06657c10f.1" type="button" disabled={i===questions.length-1} onClick={()=>move(i,1)}><ScreenText id="QuizBuilderPage.da6c338bb09def6d">Move down</ScreenText></button><button data-design-block="copy.0e67c27b3c29d4bc.1" type="button" onClick={()=>removeQuestion(q,i)}><ScreenText id="QuizBuilderPage.13589e4bff7afdc0">Remove question</ScreenText></button></div>
 </article>)}
 <datalist id="quiz-categories">{['Guest service','Menu knowledge','Cocktails','Specials','Cash handling','Reservations','Teamwork','Policies'].map(c=><option value={c} key={c} />)}</datalist>
 <div data-design-block="copy.6825e010cc4f0660.4" className="quiz-actions"><button data-design-block="copy.66979413089889e4.2" type="button" disabled={questions.length>=50} onClick={chooseAdd}><ScreenText id="QuizBuilderPage.c399b5dd0f5cf572">Add question</ScreenText></button><button data-design-block="copy.d45573cbc0f81512.1" type="button" onClick={()=>void save(false)}><ScreenText id="QuizBuilderPage.ff4083555dca251c">Save Draft</ScreenText>{published?<PageWord id="copy.695b7d0ea4a26044.1">{" / Unpublish"}</PageWord>:<PageWord id="copy.e71f644adc6685f7.2">{""}</PageWord>}</button><button data-design-block="copy.603a65899dd9b900.1" type="button" className="primary-button" onClick={()=>{if(window.confirm(results.length>0?'Publish these changes? Existing scores stay unchanged; staff who have not submitted will receive the updated quiz.':'Publish this quiz for staff?'))void save(true)}}>{publishedView?<PageWord id="copy.6657cc2605099a18.1">{"Publish Changes"}</PageWord>:<PageWord id="copy.f7928d733a907e54.1">{"Schedule Quiz"}</PageWord>}</button></div>
 </fieldset>
 {published && quizId && <QuizRequiredStaff location={location} quizId={quizId} />}
 {publishedView && <article data-design-block="copy.36458728857aec54.2" className="mod-review"><h2 data-design-block="copy.c86fd29e94d26d29.3"><ScreenText id="QuizBuilderPage.b5d5bbd0d71a6552">Team scores (</ScreenText>{results.length}<ScreenText id="QuizBuilderPage.28769235af8d9c69"> submitted)</ScreenText></h2>{results.length===0?<p data-design-block="copy.4b1d0894fdd167e3.7"><ScreenText id="QuizBuilderPage.491aff72d66fda3a">No submissions yet.</ScreenText></p>:results.map(r=><details key={r.user_id}><summary>{r.name}<PageWord id="copy.2886bbb827144b31.1">: </PageWord>{r.result.score}<PageWord id="copy.1d60f5ff99e002c8.1">/</PageWord>{r.result.total}<PageWord id="copy.2c17ba2bf629e805.1">(</PageWord>{r.result.percent}<PageWord id="copy.261ff916d1611e9d.1">%)</PageWord></summary><p data-design-block="copy.4b1d0894fdd167e3.8"><ScreenText id="QuizBuilderPage.3f2276a819431068">Submitted: </ScreenText>{submissionLabel(r.submitted_at)}</p>{r.result.questions.map((q,i)=><p data-design-block="copy.65df9010e0d4a005.2" key={i}>{i+1}<PageWord id="copy.46b0b38dd7439603.1">. </PageWord>{q.prompt}<PageWord id="copy.32aade12d6ac2cdb.1">— </PageWord>{q.selected}<PageWord id="copy.2c17ba2bf629e805.2">(</PageWord>{q.correct?<PageWord id="copy.cdbc12f79ee66b51.1">{"correct"}</PageWord>:<PageWord id="copy.ac39e1ee774ca896.1">{"incorrect"}</PageWord>}<PageWord id="copy.fda5fc6ff8d14001.1">)</PageWord></p>)}</details>)}</article>}
 </section>
}



