import { ScreenText } from "../components/ScreenText"
import { useEffect,useState } from 'react'
import { Link } from 'react-router-dom'
import { loadTenantData } from '../lib/tenant'
import { supabase } from '../lib/supabase'
import { loadSalesTargets } from '../lib/loadSalesTargets'
import { calculateTargets,salesMoney,shiftGroup,shiftHours,type TargetInputs,type TargetGroup,type SalesShift } from '../lib/salesTargets'
import './SalesTargetsPage.css'
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Chicago',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())
const weekdays=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday']
const yesterday=()=>{const d=new Date(today()+'T12:00:00Z');d.setUTCDate(d.getUTCDate()-1);return d.toISOString().slice(0,10)}
const windowStart=(end:string)=>{const d=new Date(end+'T12:00:00Z');d.setUTCDate(d.getUTCDate()-41);return d.toISOString().slice(0,10)}
export function SalesTargetsPage(){
 const [location,setLocation]=useState(''),[date,setDate]=useState(today),[inputs,setInputs]=useState<TargetInputs|null>(null),[shifts,setShifts]=useState<SalesShift[]>([]),[history,setHistory]=useState<Record<string,string>>({}),[through,setThrough]=useState(yesterday),[error,setError]=useState(''),[message,setMessage]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[refresh,setRefresh]=useState(0),[scheduleError,setScheduleError]=useState(''),[dirty,setDirty]=useState(false)
 useEffect(()=>{let live=true;void loadTenantData().then(t=>{if(!t.locations[0])throw Error('No active location found.');if(live)setLocation(t.locations[0].id)}).catch(e=>{if(live){setError(String(e.message??e));setLoading(false)}});return()=>{live=false}},[])
 useEffect(()=>{if(!location)return;let live=true;setLoading(true);setInputs(null);setShifts([]);setError('');setScheduleError('');setMessage('');setDirty(false)
 void(async()=>{const r=await supabase.rpc('sales_target_inputs',{p_location_id:location,p_date:date});if(r.error)throw r.error;if(!live)return;setInputs(r.data);setHistory(Object.fromEntries((r.data.weekday_totals??[]).map((h:{weekday:number;total:number|null})=>[String(h.weekday),h.total==null?'':String(h.total)])));setThrough(r.data.weekday_totals?.[0]?.through_date??yesterday());try{const d=await loadSalesTargets(location,date);if(live){setShifts(d.shifts);setInputs(v=>v?{...v,locked_day:d.inputs.locked_day}:v)}}catch(e){if(live)setScheduleError(String((e as Error).message))}})().catch(e=>{if(live)setError(String(e.message??e))}).finally(()=>{if(live)setLoading(false)});return()=>{live=false}},[location,date,refresh])
 function patch(change:Partial<TargetInputs>){setInputs(v=>v?{...v,...change}:v);setDirty(true);setMessage('')}
 async function save(){if(!inputs||saving)return;setSaving(true);setError('');setMessage('');try{
 if(!through||through>=today()||through>=date)throw Error('Choose a completed six-week period ending before the target date.');
 const records=weekdays.map((_,weekday)=>({weekday,total:history[String(weekday)]?.trim()?Number(history[String(weekday)]):null}));if(records.some(r=>r.total!=null&&(!Number.isFinite(r.total)||r.total<0)))throw Error('Enter valid six-week totals, or leave missing weekdays blank.');
 const r=await supabase.rpc('sales_target_save_weekday_totals',{p_location_id:location,p_date:date,p_through:through,p_version:inputs.settings.version,p_bar_percent:inputs.settings.bar_percent,p_growth_percent:inputs.settings.growth_percent,p_role_groups:inputs.settings.role_groups,p_totals:records,p_overrides:inputs.overrides});if(r.error)throw r.error;
 const saved=await supabase.rpc('sales_target_inputs',{p_location_id:location,p_date:date});if(saved.error)throw saved.error;setInputs(saved.data);setHistory(Object.fromEntries((saved.data.weekday_totals??[]).map((h:{weekday:number;total:number|null})=>[String(h.weekday),h.total==null?'':String(h.total)])));setDirty(false);setMessage('Sales target inputs saved. Pre-Shift will use these values when it loads or refreshes targets.');
 }catch(e){setError(String((e as Error).message))}finally{setSaving(false)}}
 const effective=inputs?{...inputs,history:[],weekday_totals:weekdays.flatMap((_,weekday)=>history[String(weekday)]?.trim()?[{weekday,total:Number(history[String(weekday)]),through_date:through}]:[])}:null
 const result=effective?calculateTargets(date,effective,shifts):null,locked=loading||saving
 return <section className="page sales-target-page"><Link to="/settings"><ScreenText id="SalesTargetsPage.ad38ada26e3e5960">← Settings</ScreenText></Link><h1><ScreenText id="SalesTargetsPage.80824852a0f51869">Sales target setup</ScreenText></h1><p><ScreenText id="SalesTargetsPage.5633c1a02ead3c1e">Enter one combined net sales total per weekday for the past six weeks. For example, add all six Tuesdays and enter that total once. The system divides it by six. Blank means missing; 0 means a confirmed zero total.</ScreenText></p>
 <label><ScreenText id="SalesTargetsPage.fed6ba6c4a47b680">Target date</ScreenText><input type="date" value={date} disabled={locked} onChange={e=>{if(!e.target.value)return;if(dirty&&!window.confirm('Discard unsaved sales target changes?'))return;setDate(e.target.value)}}/></label><button type="button" disabled={locked} onClick={()=>{if(!dirty||window.confirm('Discard changes and reload?'))setRefresh(v=>v+1)}}><ScreenText id="SalesTargetsPage.63b224b233660386">Reload schedule &amp; inputs</ScreenText></button>
 {loading&&<p role="status"><ScreenText id="SalesTargetsPage.2636b0a0386e6314">Loading sales target setup…</ScreenText></p>}{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}{inputs&&<fieldset disabled={locked}><legend><ScreenText id="SalesTargetsPage.a41eae4c48ebead8">Calculation settings</ScreenText></legend><div className="sales-target-fields"><label><ScreenText id="SalesTargetsPage.625759988defaa78">Bar share (%)</ScreenText><input type="number" min="0" max="100" step="0.1" value={inputs.settings.bar_percent} onChange={e=>patch({settings:{...inputs.settings,bar_percent:Number(e.target.value)}})}/><small><ScreenText id="SalesTargetsPage.b6d1353b02fa9a28">Floor receives </ScreenText>{100-inputs.settings.bar_percent}%.</small></label><label><ScreenText id="SalesTargetsPage.14385b3ceb4d794c">Growth adjustment (%)</ScreenText><input type="number" min="-100" max="300" step="0.1" value={inputs.settings.growth_percent} onChange={e=>patch({settings:{...inputs.settings,growth_percent:Number(e.target.value)}})}/></label></div>
 {inputs.locked_day&&<p role="status">Targets for this date were locked when the first closeout was submitted. Changes to inputs affect unlocked dates; this preview uses the saved targets.</p>}<h2>Six-week totals by weekday</h2><label>Six-week period ending<input type="date" value={through} max={yesterday()} onChange={e=>{if(e.target.value){setThrough(e.target.value);setDirty(true)}}}/></label><p>{windowStart(through)} through {through} · six occurrences of each weekday.</p><div className="sales-history-grid">{weekdays.map((name,weekday)=><label key={name}>{name} · six-week total<input aria-label={name+' six-week net sales total'} type="number" min="0" max="9999999999.99" step="0.01" placeholder="Missing" value={history[String(weekday)]??''} onChange={e=>{setHistory(v=>({...v,[String(weekday)]:e.target.value}));setDirty(true);setMessage('')}}/><small>Daily average: {history[String(weekday)]?.trim()?salesMoney(Number(history[String(weekday)])/6):'—'}</small></label>)}</div>

 <h2><ScreenText id="SalesTargetsPage.61acfaebfea6432c">Schedule allocation</ScreenText></h2><p><ScreenText id="SalesTargetsPage.e10154948e563be3">Each pool is divided by scheduled hours. Choose how each role contributes; managers, hosts and other roles start excluded. For shifts ending at Close or Business decline, enter expected hours.</ScreenText></p>{scheduleError&&<p role="alert">{scheduleError}</p>}
 <div className="sales-target-fields">{[...new Set(shifts.map(s=>s.role))].map(role=><label key={role}>{role}<select value={inputs.settings.role_groups[role.trim().toLowerCase()]??(/\bbartender\b/i.test(role)?'bar':/\bserver\b/i.test(role)?'floor':'exclude')} onChange={e=>patch({settings:{...inputs.settings,role_groups:{...inputs.settings.role_groups,[role.trim().toLowerCase()]:e.target.value as TargetGroup}}})}><option value="bar"><ScreenText id="SalesTargetsPage.2400a43d03dccfc6">Bar</ScreenText></option><option value="floor"><ScreenText id="SalesTargetsPage.a522337dd74f7886">Floor</ScreenText></option><option value="exclude"><ScreenText id="SalesTargetsPage.de2b4bcfb25283d9">Exclude</ScreenText></option></select></label>)}</div>
 {shifts.map(s=><div className="sales-shift-row" key={s.id}><strong>{s.name} · {s.role}</strong><label><ScreenText id="SalesTargetsPage.1c6f02f3deab79b4">Allocation</ScreenText><select value={shiftGroup(s,inputs)} onChange={e=>patch({overrides:{...inputs.overrides,[s.id]:{...inputs.overrides[s.id],group:e.target.value as TargetGroup}}})}><option value="bar"><ScreenText id="SalesTargetsPage.492e3a0778b6e6f5">Bar</ScreenText></option><option value="floor"><ScreenText id="SalesTargetsPage.9050adf5d55781c1">Floor</ScreenText></option><option value="exclude"><ScreenText id="SalesTargetsPage.ce6da94b2cb65c41">Exclude</ScreenText></option></select></label><label><ScreenText id="SalesTargetsPage.e16dbdc559e88947">Expected hours</ScreenText><input type="number" step="0.01" min="0.01" max="24" placeholder={shiftHours(s,{...inputs,overrides:{}})?.toFixed(2)??'Required if included'} value={inputs.overrides[s.id]?.hours??''} onChange={e=>patch({overrides:{...inputs.overrides,[s.id]:{group:shiftGroup(s,inputs),hours:e.target.value===''?null:Number(e.target.value)}}})}/></label></div>)}
 {result&&<section><h2><ScreenText id="SalesTargetsPage.adc49d124b9b029a">Target preview</ScreenText>{dirty?' · Unsaved changes':''}</h2><p><ScreenText id="SalesTargetsPage.0d97c739462f93ba">Six-week weekday total ÷ 6: </ScreenText>{salesMoney(result.average)}<ScreenText id="SalesTargetsPage.b5fdca9800f3dbfa"> · Team goal: </ScreenText><strong>{salesMoney(result.total)}</strong></p><p><ScreenText id="SalesTargetsPage.85324e671581449a">Bar </ScreenText>{salesMoney(result.bar)}<ScreenText id="SalesTargetsPage.3eb4b7c2664b3b68"> · Floor </ScreenText>{salesMoney(result.floor)}</p>{result.issues.map(i=><p key={i} role="alert">{i}</p>)}{result.ready&&!scheduleError&&<div className="sales-target-table"><table><thead><tr><th><ScreenText id="SalesTargetsPage.1ce2d1acb9720273">Employee</ScreenText></th><th><ScreenText id="SalesTargetsPage.3e47e31eb21cfa65">Pool</ScreenText></th><th><ScreenText id="SalesTargetsPage.e1be69da2a7c4dbe">Hours</ScreenText></th><th><ScreenText id="SalesTargetsPage.22a899213932833c">Target</ScreenText></th></tr></thead><tbody>{result.rows.map(r=><tr key={r.group+':'+r.key}><td>{r.name}</td><td>{r.group}</td><td>{r.hours.toFixed(2)}</td><td>{salesMoney(r.target)}</td></tr>)}</tbody></table></div>}</section>}
 <button type="button" disabled={locked||!dirty} onClick={()=>void save()}>{saving?'Saving…':'Save sales target inputs'}</button><p><Link to="/preshift"><ScreenText id="SalesTargetsPage.4864400a9cf8ebc5">Open Pre-Shift →</ScreenText></Link></p></fieldset>}</section>
}

