import { useEffect,useState } from 'react'
import { Link } from 'react-router-dom'
import { loadTenantData } from '../lib/tenant'
import { supabase } from '../lib/supabase'
import { loadSalesTargets } from '../lib/loadSalesTargets'
import { calculateTargets,precedingDays,salesMoney,shiftGroup,shiftHours,type TargetInputs,type TargetGroup,type SalesShift } from '../lib/salesTargets'
import './SalesTargetsPage.css'
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Chicago',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())
const label=(date:string)=>new Intl.DateTimeFormat('en-US',{timeZone:'UTC',weekday:'short',month:'short',day:'numeric'}).format(new Date(date+'T12:00:00Z'))
export function SalesTargetsPage(){
 const [location,setLocation]=useState(''),[date,setDate]=useState(today),[inputs,setInputs]=useState<TargetInputs|null>(null),[shifts,setShifts]=useState<SalesShift[]>([]),[history,setHistory]=useState<Record<string,string>>({}),[error,setError]=useState(''),[message,setMessage]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[refresh,setRefresh]=useState(0),[scheduleError,setScheduleError]=useState(''),[dirty,setDirty]=useState(false)
 useEffect(()=>{let live=true;void loadTenantData().then(t=>{if(!t.locations[0])throw Error('No active location found.');if(live)setLocation(t.locations[0].id)}).catch(e=>{if(live){setError(String(e.message??e));setLoading(false)}});return()=>{live=false}},[])
 useEffect(()=>{if(!location)return;let live=true;setLoading(true);setInputs(null);setShifts([]);setError('');setScheduleError('');setMessage('');setDirty(false)
 void(async()=>{const r=await supabase.rpc('sales_target_inputs',{p_location_id:location,p_date:date});if(r.error)throw r.error;if(!live)return;setInputs(r.data);setHistory(Object.fromEntries((r.data.history as TargetInputs['history']).map(h=>[h.date,String(h.amount)])));try{const d=await loadSalesTargets(location,date);if(live)setShifts(d.shifts)}catch(e){if(live)setScheduleError(String((e as Error).message))}})().catch(e=>{if(live)setError(String(e.message??e))}).finally(()=>{if(live)setLoading(false)});return()=>{live=false}},[location,date,refresh])
 function patch(change:Partial<TargetInputs>){setInputs(v=>v?{...v,...change}:v);setDirty(true);setMessage('')}
 async function save(){if(!inputs||saving)return;setSaving(true);setError('');setMessage('');try{
 const days=precedingDays(date).filter(d=>d<today());const records=days.map(d=>({date:d,amount:history[d]?.trim()?Number(history[d]):null}));if(records.some(r=>r.amount!=null&&(!Number.isFinite(r.amount)||r.amount<0)))throw Error('Enter valid net sales amounts, or leave missing days blank.');
 const r=await supabase.rpc('sales_target_save_inputs',{p_location_id:location,p_date:date,p_version:inputs.settings.version,p_bar_percent:inputs.settings.bar_percent,p_growth_percent:inputs.settings.growth_percent,p_role_groups:inputs.settings.role_groups,p_history:records,p_overrides:inputs.overrides});if(r.error)throw r.error;
 const saved=await supabase.rpc('sales_target_inputs',{p_location_id:location,p_date:date});if(saved.error)throw saved.error;setInputs(saved.data);setHistory(Object.fromEntries((saved.data.history as TargetInputs['history']).map(h=>[h.date,String(h.amount)])));setDirty(false);setMessage('Sales target inputs saved. Pre-Shift will use these values when it loads or refreshes targets.');
 }catch(e){setError(String((e as Error).message))}finally{setSaving(false)}}
 const effective=inputs?{...inputs,history:precedingDays(date).filter(d=>history[d]?.trim()).map(d=>({date:d,amount:Number(history[d])}))}:null
 const result=effective?calculateTargets(date,effective,shifts):null,locked=loading||saving
 return <section className="page sales-target-page"><Link to="/settings">← Settings</Link><h1>Sales target setup</h1><p>Enter total restaurant net sales for each past date. Blank means missing; enter 0 for a confirmed zero-sales day. The goal uses the six previous matching weekdays.</p>
 <label>Target date<input type="date" value={date} disabled={locked} onChange={e=>{if(!e.target.value)return;if(dirty&&!window.confirm('Discard unsaved sales target changes?'))return;setDate(e.target.value)}}/></label><button type="button" disabled={locked} onClick={()=>{if(!dirty||window.confirm('Discard changes and reload?'))setRefresh(v=>v+1)}}>Reload schedule &amp; inputs</button>
 {loading&&<p role="status">Loading sales target setup…</p>}{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}{inputs&&<fieldset disabled={locked}><legend>Calculation settings</legend><div className="sales-target-fields"><label>Bar share (%)<input type="number" min="0" max="100" step="0.1" value={inputs.settings.bar_percent} onChange={e=>patch({settings:{...inputs.settings,bar_percent:Number(e.target.value)}})}/><small>Floor receives {100-inputs.settings.bar_percent}%.</small></label><label>Growth adjustment (%)<input type="number" min="-100" max="300" step="0.1" value={inputs.settings.growth_percent} onChange={e=>patch({settings:{...inputs.settings,growth_percent:Number(e.target.value)}})}/></label></div>
 <h2>Past six weeks · Daily net sales</h2><div className="sales-history-grid">{precedingDays(date).map(d=><label key={d}>{label(d)}<input aria-label={`Net sales ${d}`} type="number" min="0" max="9999999999.99" step="0.01" disabled={d>=today()} placeholder={d>=today()?'Future date':'Missing'} value={history[d]??''} onChange={e=>{setHistory(v=>({...v,[d]:e.target.value}));setDirty(true);setMessage('')}}/></label>)}</div>
 <h2>Schedule allocation</h2><p>Each pool is divided by scheduled hours. Choose how each role contributes; managers, hosts and other roles start excluded. For shifts ending at Close or Business decline, enter expected hours.</p>{scheduleError&&<p role="alert">{scheduleError}</p>}
 <div className="sales-target-fields">{[...new Set(shifts.map(s=>s.role))].map(role=><label key={role}>{role}<select value={inputs.settings.role_groups[role.trim().toLowerCase()]??(/\bbartender\b/i.test(role)?'bar':/\bserver\b/i.test(role)?'floor':'exclude')} onChange={e=>patch({settings:{...inputs.settings,role_groups:{...inputs.settings.role_groups,[role.trim().toLowerCase()]:e.target.value as TargetGroup}}})}><option value="bar">Bar</option><option value="floor">Floor</option><option value="exclude">Exclude</option></select></label>)}</div>
 {shifts.map(s=><div className="sales-shift-row" key={s.id}><strong>{s.name} · {s.role}</strong><label>Allocation<select value={shiftGroup(s,inputs)} onChange={e=>patch({overrides:{...inputs.overrides,[s.id]:{...inputs.overrides[s.id],group:e.target.value as TargetGroup}}})}><option value="bar">Bar</option><option value="floor">Floor</option><option value="exclude">Exclude</option></select></label><label>Expected hours<input type="number" step="0.01" min="0.01" max="24" placeholder={shiftHours(s,{...inputs,overrides:{}})?.toFixed(2)??'Required if included'} value={inputs.overrides[s.id]?.hours??''} onChange={e=>patch({overrides:{...inputs.overrides,[s.id]:{group:shiftGroup(s,inputs),hours:e.target.value===''?null:Number(e.target.value)}}})}/></label></div>)}
 {result&&<section><h2>Target preview{dirty?' · Unsaved changes':''}</h2><p>Six-day average: {salesMoney(result.average)} · Team goal: <strong>{salesMoney(result.total)}</strong></p><p>Bar {salesMoney(result.bar)} · Floor {salesMoney(result.floor)}</p>{result.issues.map(i=><p key={i} role="alert">{i}</p>)}{result.ready&&!scheduleError&&<div className="sales-target-table"><table><thead><tr><th>Employee</th><th>Pool</th><th>Hours</th><th>Target</th></tr></thead><tbody>{result.rows.map(r=><tr key={r.group+':'+r.key}><td>{r.name}</td><td>{r.group}</td><td>{r.hours.toFixed(2)}</td><td>{salesMoney(r.target)}</td></tr>)}</tbody></table></div>}</section>}
 <button type="button" disabled={locked||!dirty} onClick={()=>void save()}>{saving?'Saving…':'Save sales target inputs'}</button><p><Link to="/preshift">Open Pre-Shift →</Link></p></fieldset>}</section>
}
