// page-designer-instrumented
import { PageWord, PageInput, PageOption } from "../components/PageDesign"
import { ScreenText } from "../components/ScreenText"
import { useEffect,useState } from 'react'
import { Link } from 'react-router-dom'
import { loadTenantData } from '../lib/tenant'
import { supabase } from '../lib/supabase'
import { loadSalesTargets } from '../lib/loadSalesTargets'
import { calculateTargets,salesMoney,shiftGroup,shiftHours,type TargetInputs,type TargetGroup,type SalesShift } from '../lib/salesTargets'
import './SalesTargetsPage.css'
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Chicago',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())
const weekdays=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday']
const yesterday=()=>{const d=new Date(today()+'T12:00:00Z');d.setUTCDate(d.getUTCDate()-1);return d.toISOString().slice(0,10)}
const windowStart=(end:string)=>{const d=new Date(end+'T12:00:00Z');d.setUTCDate(d.getUTCDate()-41);return d.toISOString().slice(0,10)}
export function SalesTargetsPage(){
 const [location,setLocation]=useState(''),[date,setDate]=useState(today),[inputs,setInputs]=useState<TargetInputs|null>(null),[shifts,setShifts]=useState<SalesShift[]>([]),[history,setHistory]=useState<Record<string,string>>({}),[through,setThrough]=useState(yesterday),[error,setError]=useState(''),[message,setMessage]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[refresh,setRefresh]=useState(0),[scheduleError,setScheduleError]=useState(''),[dirty,setDirty]=useState(false)
 useEffect(()=>{let live=true;void loadTenantData().then(t=>{if(!t.locations[0])throw Error('No active location found.');if(live)setLocation(t.locations[0].id)}).catch(e=>{if(live){setError(String(e.message??e));setLoading(false)}});return()=>{live=false}},[])
 useEffect(()=>{if(!location)return;let live=true;setLoading(true);setInputs(null);setShifts([]);setError('');setScheduleError('');setMessage('');setDirty(false)
 void(async()=>{const r=await supabase.rpc('sales_target_inputs',{p_location_id:location,p_date:date});if(r.error)throw r.error;if(!live)return;setInputs(r.data);setHistory(Object.fromEntries((r.data.weekday_totals??[]).map((h:{weekday:number;total:number|null})=>[String(h.weekday),h.total==null?'':String(h.total)])));setThrough(r.data.weekday_totals?.[0]?.through_date??yesterday());try{const d=await loadSalesTargets(location,date);if(live){setShifts(d.shifts);setInputs(v=>v?{...v,locked_day:d.inputs.locked_day}:v)}}catch(e){if(live)setScheduleError(String((e as Error).message))}})().catch(e=>{if(live)setError(String(e.message??e))}).finally(()=>{if(live)setLoading(false)});return()=>{live=false}},[location,date,refresh])
 function patch(change:Partial<TargetInputs>){setInputs(v=>v?{...v,...change}:v);setDirty(true);setMessage('')}
 async function save(){if(!inputs||saving)return;setSaving(true);setError('');setMessage('');try{
 if(!through||through>=today()||through>=date)throw Error('Choose a completed six-week period ending before the target date.');
 const records=weekdays.map((_,weekday)=>({weekday,total:history[String(weekday)]?.trim()?Number(history[String(weekday)]):null}));if(records.some(r=>r.total!=null&&(!Number.isFinite(r.total)||r.total<0)))throw Error('Enter valid six-week totals, or leave missing weekdays blank.');
 const r=await supabase.rpc('sales_target_save_weekday_totals',{p_location_id:location,p_date:date,p_through:through,p_version:inputs.settings.version,p_bar_percent:inputs.settings.bar_percent,p_growth_percent:inputs.settings.growth_percent,p_role_groups:inputs.settings.role_groups,p_totals:records,p_overrides:inputs.overrides});if(r.error)throw r.error;
 const saved=await supabase.rpc('sales_target_inputs',{p_location_id:location,p_date:date});if(saved.error)throw saved.error;setInputs(saved.data);setHistory(Object.fromEntries((saved.data.weekday_totals??[]).map((h:{weekday:number;total:number|null})=>[String(h.weekday),h.total==null?'':String(h.total)])));setDirty(false);setMessage('Sales target inputs saved. Pre-Shift will use these values when it loads or refreshes targets.');
 }catch(e){setError(String((e as Error).message))}finally{setSaving(false)}}
 const effective=inputs?{...inputs,history:[],weekday_totals:weekdays.flatMap((_,weekday)=>history[String(weekday)]?.trim()?[{weekday,total:Number(history[String(weekday)]),through_date:through}]:[])}:null
 const result=effective?calculateTargets(date,effective,shifts):null,locked=loading||saving
 return <section data-design-block="copy.ae2f7c61d09d06e3.1" className="page sales-target-page"><Link to="/settings"><ScreenText id="SalesTargetsPage.ad38ada26e3e5960">← Settings</ScreenText></Link><h1 data-design-block="copy.c212a7bfc5748bce.1"><ScreenText id="SalesTargetsPage.80824852a0f51869">Sales target setup</ScreenText></h1><p data-design-block="copy.7989bfe05c00ff24.1"><ScreenText id="SalesTargetsPage.5633c1a02ead3c1e">Enter one combined net sales total per weekday for the past six weeks. For example, add all six Tuesdays and enter that total once. The system divides it by six. Blank means missing; 0 means a confirmed zero total.</ScreenText></p>
 <label data-design-block="copy.e63e1b0127ac67c1.1"><ScreenText id="SalesTargetsPage.fed6ba6c4a47b680">Target date</ScreenText><input type="date" value={date} disabled={locked} onChange={e=>{if(!e.target.value)return;if(dirty&&!window.confirm('Discard unsaved sales target changes?'))return;setDate(e.target.value)}}/></label><button data-design-block="copy.465b2d9248557489.1" type="button" disabled={locked} onClick={()=>{if(!dirty||window.confirm('Discard changes and reload?'))setRefresh(v=>v+1)}}><ScreenText id="SalesTargetsPage.63b224b233660386">Reload schedule &amp; inputs</ScreenText></button>
 {loading&&<p data-design-block="copy.f0d79a8fc15ff765.1" role="status"><ScreenText id="SalesTargetsPage.2636b0a0386e6314">Loading sales target setup…</ScreenText></p>}{error&&<p data-design-block="copy.488cd3d148b71a9c.1" role="alert">{error}</p>}{message&&<p data-design-block="copy.f0d79a8fc15ff765.2" role="status">{message}</p>}{inputs&&<fieldset data-design-block="copy.a36531d83468de4f.1" disabled={locked}><legend><ScreenText id="SalesTargetsPage.a41eae4c48ebead8">Calculation settings</ScreenText></legend><div data-design-block="copy.e23dbdd540fa7a70.1" className="sales-target-fields"><label data-design-block="copy.e63e1b0127ac67c1.2"><ScreenText id="SalesTargetsPage.625759988defaa78">Bar share (%)</ScreenText><input type="number" min="0" max="100" step="0.1" value={inputs.settings.bar_percent} onChange={e=>patch({settings:{...inputs.settings,bar_percent:Number(e.target.value)}})}/><small><ScreenText id="SalesTargetsPage.b6d1353b02fa9a28">Floor receives </ScreenText>{100-inputs.settings.bar_percent}<PageWord id="copy.72a1f46a9d8754af.1">%.</PageWord></small></label><label data-design-block="copy.e63e1b0127ac67c1.3"><ScreenText id="SalesTargetsPage.14385b3ceb4d794c">Growth adjustment (%)</ScreenText><input type="number" min="-100" max="300" step="0.1" value={inputs.settings.growth_percent} onChange={e=>patch({settings:{...inputs.settings,growth_percent:Number(e.target.value)}})}/></label></div>
 {inputs.locked_day&&<p data-design-block="copy.f0d79a8fc15ff765.3" role="status"><PageWord id="copy.26828ffa70bcc339.1">Targets for this date were locked when the first closeout was submitted. Changes to inputs affect unlocked dates; this preview uses the saved targets.</PageWord></p>}<h2 data-design-block="copy.4fe515bc49955aae.1"><PageWord id="copy.9e6d2735749adbaa.1">Six-week totals by weekday</PageWord></h2><label data-design-block="copy.e63e1b0127ac67c1.4"><PageWord id="copy.bf8be82cb8892e9d.1">Six-week period ending</PageWord><input type="date" value={through} max={yesterday()} onChange={e=>{if(e.target.value){setThrough(e.target.value);setDirty(true)}}}/></label><p data-design-block="copy.7989bfe05c00ff24.2">{windowStart(through)}<PageWord id="copy.a6e88974b95d3d92.1">through </PageWord>{through}<PageWord id="copy.fd65f15ab953cf52.1">· six occurrences of each weekday.</PageWord></p><div data-design-block="copy.fb94283a94be9a02.1" className="sales-history-grid">{weekdays.map((name,weekday)=><label data-design-block="copy.023a575b45bc689e.1" key={name}>{name}<PageWord id="copy.72a634e4067617b2.1">· six-week total</PageWord><PageInput designId="copy.38497a100a9262a8.1" aria-label={name+' six-week net sales total'} type="number" min="0" max="9999999999.99" step="0.01" placeholder="Missing" value={history[String(weekday)]??''} onChange={e=>{setHistory(v=>({...v,[String(weekday)]:e.target.value}));setDirty(true);setMessage('')}}/><small><PageWord id="copy.96bf9c44bcbb8a14.1">Daily average: </PageWord>{history[String(weekday)]?.trim()?salesMoney(Number(history[String(weekday)])/6):<PageWord id="copy.46189fb8ee4d25e2.1">{"—"}</PageWord>}</small></label>)}</div>

 <h2 data-design-block="copy.4fe515bc49955aae.2"><ScreenText id="SalesTargetsPage.61acfaebfea6432c">Schedule allocation</ScreenText></h2><p data-design-block="copy.7989bfe05c00ff24.3"><ScreenText id="SalesTargetsPage.e10154948e563be3">Each pool is divided by scheduled hours. Choose how each role contributes; managers, hosts and other roles start excluded. For shifts ending at Close or Business decline, enter expected hours.</ScreenText></p>{scheduleError&&<p data-design-block="copy.488cd3d148b71a9c.2" role="alert">{scheduleError}</p>}
 <div data-design-block="copy.e23dbdd540fa7a70.2" className="sales-target-fields">{[...new Set(shifts.map(s=>s.role))].map(role=><label data-design-block="copy.3051e07493d8cb25.1" key={role}>{role}<select value={inputs.settings.role_groups[role.trim().toLowerCase()]??(/\bbartender\b/i.test(role)?'bar':/\bserver\b/i.test(role)?'floor':'exclude')} onChange={e=>patch({settings:{...inputs.settings,role_groups:{...inputs.settings.role_groups,[role.trim().toLowerCase()]:e.target.value as TargetGroup}}})}><PageOption designId="copy.8639ae85347e2493.1" value="bar"><ScreenText plain id="SalesTargetsPage.2400a43d03dccfc6">Bar</ScreenText></PageOption><PageOption designId="copy.d49b052668c95548.1" value="floor"><ScreenText plain id="SalesTargetsPage.a522337dd74f7886">Floor</ScreenText></PageOption><PageOption designId="copy.1039a20e5ef0b221.1" value="exclude"><ScreenText plain id="SalesTargetsPage.de2b4bcfb25283d9">Exclude</ScreenText></PageOption></select></label>)}</div>
 {shifts.map(s=><div data-design-block="copy.6e555bfcf1f15d83.1" className="sales-shift-row" key={s.id}><strong>{s.name}<PageWord id="copy.bda27f8217b7e637.1">· </PageWord>{s.role}</strong><label data-design-block="copy.e63e1b0127ac67c1.5"><ScreenText id="SalesTargetsPage.1c6f02f3deab79b4">Allocation</ScreenText><select value={shiftGroup(s,inputs)} onChange={e=>patch({overrides:{...inputs.overrides,[s.id]:{...inputs.overrides[s.id],group:e.target.value as TargetGroup}}})}><PageOption designId="copy.0a2b47738f495d49.1" value="bar"><ScreenText plain id="SalesTargetsPage.492e3a0778b6e6f5">Bar</ScreenText></PageOption><PageOption designId="copy.fdcb0c0fdc961ec0.1" value="floor"><ScreenText plain id="SalesTargetsPage.9050adf5d55781c1">Floor</ScreenText></PageOption><PageOption designId="copy.ea9603ff63813f8b.1" value="exclude"><ScreenText plain id="SalesTargetsPage.ce6da94b2cb65c41">Exclude</ScreenText></PageOption></select></label><label data-design-block="copy.e63e1b0127ac67c1.6"><ScreenText id="SalesTargetsPage.e16dbdc559e88947">Expected hours</ScreenText><input type="number" step="0.01" min="0.01" max="24" placeholder={shiftHours(s,{...inputs,overrides:{}})?.toFixed(2)??'Required if included'} value={inputs.overrides[s.id]?.hours??''} onChange={e=>patch({overrides:{...inputs.overrides,[s.id]:{group:shiftGroup(s,inputs),hours:e.target.value===''?null:Number(e.target.value)}}})}/></label></div>)}
 {result&&<section data-design-block="copy.a7c2746cd6de9c0d.1"><h2 data-design-block="copy.4fe515bc49955aae.3"><ScreenText id="SalesTargetsPage.adc49d124b9b029a">Target preview</ScreenText>{dirty?<PageWord id="copy.daddc8bc1c39d269.1">{" · Unsaved changes"}</PageWord>:<PageWord id="copy.b28f5abf59a2bc94.1">{""}</PageWord>}</h2><p data-design-block="copy.7989bfe05c00ff24.4"><ScreenText id="SalesTargetsPage.0d97c739462f93ba">Six-week weekday total ÷ 6: </ScreenText>{salesMoney(result.average)}<ScreenText id="SalesTargetsPage.b5fdca9800f3dbfa"> · Team goal: </ScreenText><strong>{salesMoney(result.total)}</strong></p><p data-design-block="copy.7989bfe05c00ff24.5"><ScreenText id="SalesTargetsPage.85324e671581449a">Bar </ScreenText>{salesMoney(result.bar)}<ScreenText id="SalesTargetsPage.3eb4b7c2664b3b68"> · Floor </ScreenText>{salesMoney(result.floor)}</p>{result.issues.map(i=><p data-design-block="copy.6ab8f9253a72e1ba.1" key={i} role="alert">{i}</p>)}{result.ready&&!scheduleError&&<div data-design-block="copy.f265f6933301a3b4.1" className="sales-target-table"><table><thead><tr><th><ScreenText id="SalesTargetsPage.1ce2d1acb9720273">Employee</ScreenText></th><th><ScreenText id="SalesTargetsPage.3e47e31eb21cfa65">Pool</ScreenText></th><th><ScreenText id="SalesTargetsPage.e1be69da2a7c4dbe">Hours</ScreenText></th><th><ScreenText id="SalesTargetsPage.22a899213932833c">Target</ScreenText></th></tr></thead><tbody>{result.rows.map(r=><tr key={r.group+':'+r.key}><td>{r.name}</td><td>{r.group}</td><td>{r.hours.toFixed(2)}</td><td>{salesMoney(r.target)}</td></tr>)}</tbody></table></div>}</section>}
 <button data-design-block="copy.848a6c6d6bfaae9b.1" type="button" disabled={locked||!dirty} onClick={()=>void save()}>{saving?<PageWord id="copy.8929b53ed62f6992.1">{"Saving…"}</PageWord>:<PageWord id="copy.9cc1beba363322a7.1">{"Save sales target inputs"}</PageWord>}</button><p data-design-block="copy.7989bfe05c00ff24.6"><Link to="/preshift"><ScreenText id="SalesTargetsPage.4864400a9cf8ebc5">Open Pre-Shift →</ScreenText></Link></p></fieldset>}</section>
}

