import { useEffect,useRef,useState } from 'react'
import { createPortal } from 'react-dom'
import { Link } from 'react-router-dom'
import catalog from '../lib/screenWordingCatalog.json'
import { supabase } from '../lib/supabase'
import { loadTenantData } from '../lib/tenant'
import { setScreenWording } from '../components/ScreenText'
import { serviceDay } from '../lib/serviceDay'
import type { Config } from '../components/CloseoutConfig'
import '../components/StockBoard.css'
const pages=[['Home','/'],['Floor & Reservations','/floor'],['Staff Closeout','/closeout/staff'],['Manager Closeout','/closeout/manager'],['Closeout Summary','/closeout-summary'],['Cash Summary','/closeout-summary/cash'],['Pre-Shift','/preshift'],['Quizzes','/quizzes'],['Quiz Builder','/quizzes/build'],['Tasks','/tasks'],['Team','/team'],['Points','/rewards'],['Inventory','/inventory'],['Training','/training'],['Cocktail Training','/training/cocktails'],['Sales Targets','/settings/sales-targets'],['Settings','/settings'],['Appearance','/appearance']] as const
export function ScreenWordingPage(){
 const [location,setLocation]=useState(''),[saved,setSaved]=useState<Record<string,string>>({}),[config,setConfig]=useState<Config|null>(null),[page,setPage]=useState('/'),[version,setVersion]=useState(0),[width,setWidth]=useState('100%'),[guestPages,setGuestPages]=useState<[string,string][]>([]),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[edit,setEdit]=useState<{id:string;text:string;original:string;question?:boolean}|null>(null)
 const frame=useRef<HTMLIFrameElement>(null),cleanup=useRef<()=>void>(()=>{})
 useEffect(()=>{let live=true;void(async()=>{try{const t=await loadTenantData(),id=t.locations[0]?.id;if(!id)throw Error('No active location.');const [r,c]=await Promise.all([supabase.rpc('screen_wording_get',{p_location_id:id}),supabase.rpc('closeout_get_config',{p_location_id:id})]);if(r.error)throw r.error;if(c.error)throw c.error;if(live){setLocation(id);setSaved(r.data||{});setConfig(c.data);const extra:[string,string][]=[];const [walk,feedback]=await Promise.allSettled([supabase.rpc('walkin_list',{p_location_id:id,p_day:serviceDay()}),supabase.rpc('guest_feedback_inbox',{p_location_id:id,p_before:null,p_before_id:null})]);if(walk.status==='fulfilled'&&!walk.value.error&&walk.value.data?.key){extra.push(['Guest Walk-in Form','/walk-in/'+walk.value.data.key],['Guest Walk-in Confirmation','/walk-in/'+walk.value.data.key+'?preview-sent=1'])}if(feedback.status==='fulfilled'&&!feedback.value.error&&feedback.value.data?.key)extra.push(['Guest Feedback Form','/guest-feedback/'+feedback.value.data.key]);if(live)setGuestPages(extra)}}catch(e){if(live)setError(String((e as {message?:string}).message??e))}})();return()=>{live=false;cleanup.current()}},[])
 function attach(){cleanup.current();const doc=frame.current?.contentDocument;if(!doc)return
 const style=doc.createElement('style');style.textContent='[data-wording-id],[data-question-id]{outline:1px dashed #9a6a38;cursor:pointer!important;outline-offset:3px} [data-wording-id]:hover,[data-question-id]:hover{background:#ffe1a5!important}';doc.head.appendChild(style)
 const click=(e:Event)=>{e.preventDefault();e.stopImmediatePropagation();const target=e.target as HTMLElement;const text=target.closest<HTMLElement>('[data-wording-id],[data-question-id]');if(text){const qid=text.dataset.questionId;if(qid){const q=config?.questions.find(q=>q.id===qid);if(q)setEdit({id:qid,text:q.label,original:q.label,question:true});return}const id=text.dataset.wordingId!;const row=catalog.find(r=>r.id===id);if(row)setEdit({id,text:saved[id]??row.text,original:row.text});return}const summary=target.closest('summary');if(summary&&summary.parentElement?.tagName==='DETAILS')(summary.parentElement as HTMLDetailsElement).open=!(summary.parentElement as HTMLDetailsElement).open;else setNotice('Click an outlined label or instruction. Use its normal page to edit a post, reservation, employee record, or other saved content.')}
 const prevent=(e:Event)=>{e.preventDefault();e.stopImmediatePropagation()};doc.addEventListener('click',click,true);doc.addEventListener('submit',prevent,true);doc.addEventListener('keydown',prevent,true);doc.addEventListener('change',prevent,true)
 cleanup.current=()=>{style.remove();doc.removeEventListener('click',click,true);doc.removeEventListener('submit',prevent,true);doc.removeEventListener('keydown',prevent,true);doc.removeEventListener('change',prevent,true)}
 }
 useEffect(()=>{attach()},[saved,config])
 async function save(reset=false,remove=false){if(!edit||busy)return;setBusy(true);setError('');try{if(edit.question){if(!config)throw Error('Settings are not loaded.');const questions=config.questions.map(q=>q.id===edit.id?{...q,label:edit.text,active:remove?false:q.active}:q);const r=await supabase.rpc('closeout_save_config',{p_location_id:location,p_version:config.version,p_questions:questions,p_rules:config.rules});if(r.error)throw r.error;setConfig(r.data);setNotice(remove?'Question removed from future forms. Associated automatic point adjustments are disabled.':'Question wording saved.')}else{const r=await supabase.rpc('screen_wording_save',{p_location_id:location,p_key:edit.id,p_text:reset?null:edit.text,p_expected:saved[edit.id]??null});if(r.error)throw r.error;setSaved(r.data||{});setScreenWording(r.data||{});setNotice('Wording saved.')}setEdit(null);setVersion(v=>v+1)}catch(e){setError(String((e as {message?:string}).message??e))}finally{setBusy(false)}}
 const question=config?.questions.find(q=>q.id===edit?.id),codes=question?question.id==='staff_0'||question.id==='staff_1'?['LATE_1_5','LATE_6_14','LATE_15_29','LATE_30_PLUS',...(question.id==='staff_0'?['SALES_TARGET','SALES_110','SALES_125']:[])]:question.id==='staff_3'?['SALES_TARGET','SALES_110','SALES_125']:question.id==='staff_6'?['VOID_OVER_15']:question.id==='staff_7'?['DISCOUNT_OVER_15']:question.id==='staff_11'?['PEER_RECOGNITION']:[]:[]
 return <section className="page"><h1>Edit a Screen</h1><p>Choose a page, then click its outlined wording to edit it. Changes apply to everyone at this location.</p><div className="wording-controls"><label>Page<select value={page} disabled={busy} onChange={e=>{setPage(e.target.value);setEdit(null);setNotice('')}}>{[...pages,...guestPages].map(([name,path])=><option key={path} value={path}>{name}</option>)}</select></label><label>Preview size<select value={width} onChange={e=>setWidth(e.target.value)}><option value="100%">Full width</option><option value="390px">Phone</option><option value="820px">Tablet</option></select></label></div><p className="wording-editor-help">This is an editing preview. Submission and payment actions are blocked. Click a field’s label to edit a closeout question.</p>{error&&!edit&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{location&&<iframe key={page+version} ref={frame} title="Page editing preview" src={page+(page.includes('?')?'&':'?')+'wording-preview=1'} onLoad={attach} className="wording-preview-frame" style={{width,maxWidth:'100%'}} sandbox="allow-same-origin allow-scripts"/>}<p><Link to="/closeout/settings">Manage closeout questions, restore removed questions, and edit point rules →</Link></p>{edit&&createPortal(<div className="wording-edit-panel" role="dialog" aria-modal="true" aria-labelledby="wording-edit-title"><h2 id="wording-edit-title">{edit.question?'Edit closeout question':'Edit wording'}</h2>{error&&<p role="alert">{error}</p>}<label>Wording<textarea autoFocus rows={4} maxLength={edit.question?500:2000} disabled={busy} value={edit.text} onChange={e=>setEdit({...edit,text:e.target.value})}/></label>{codes.length>0&&<><h3>Related automatic points</h3>{config?.rules.filter(r=>codes.includes(r.id)).map(r=><label key={r.id}>{r.reason}<input type="number" min={-1000} max={1000} step={1} value={r.points} disabled={busy} onChange={e=>setConfig(c=>c&&({...c,rules:c.rules.map(x=>x.id===r.id?{...x,points:Number(e.target.value)}:x)}))}/><span><input type="checkbox" checked={r.active} disabled={busy} onChange={e=>setConfig(c=>c&&({...c,rules:c.rules.map(x=>x.id===r.id?{...x,active:e.target.checked}:x)}))}/> Apply this adjustment</span></label>)}</>}<div className="actions"><button disabled={busy||!edit.text.trim()} onClick={()=>void save()}>{busy?'Saving…':'Save'}</button>{edit.question&&question?.audience==='staff'&&<button disabled={busy} onClick={()=>{if(window.confirm('Remove this question from future closeouts? Related automatic points will not apply.'))void save(false,true)}}>Remove question</button>}{!edit.question&&<button disabled={busy} onClick={()=>void save(true)}>Restore default</button>}<button disabled={busy} onClick={()=>{setEdit(null);setVersion(v=>v+1);void supabase.rpc('closeout_get_config',{p_location_id:location}).then(r=>{if(!r.error)setConfig(r.data)})}}>Cancel</button></div></div>,document.body)}</section>
}
