import { useEffect, useState } from 'react'
import catalog from '../lib/screenWordingCatalog.json'
import { supabase } from '../lib/supabase'
import { loadTenantData } from '../lib/tenant'
import { setScreenWording } from '../components/ScreenText'
export function ScreenWordingPage(){
 const [location,setLocation]=useState(''),[saved,setSaved]=useState<Record<string,string>>({}),[page,setPage]=useState('WalkInPage'),[search,setSearch]=useState(''),[edit,setEdit]=useState<{id:string;text:string;original:string}|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('')
 useEffect(()=>{let live=true;void(async()=>{try{const t=await loadTenantData(),id=t.locations[0]?.id;if(!id)throw Error('No active location.');const r=await supabase.rpc('screen_wording_get',{p_location_id:id});if(r.error)throw r.error;if(live){setLocation(id);setSaved(r.data||{})}}catch(e){if(live)setError(String((e as {message?:string}).message??e))}})();return()=>{live=false}},[])
 async function save(reset=false){if(!edit||busy)return;setBusy(true);setError('');setNotice('');try{const r=await supabase.rpc('screen_wording_save',{p_location_id:location,p_key:edit.id,p_text:reset?null:edit.text,p_expected:saved[edit.id]??null});if(r.error)throw r.error;setSaved(r.data||{});setScreenWording(r.data||{});setEdit(null);setNotice(reset?'Default wording restored.':'Wording saved. Open screens refresh within 30 seconds.')}catch(e){setError(String((e as {message?:string}).message??e))}finally{setBusy(false)}}
 const pages=[...new Set(catalog.map(x=>x.page))].sort(),rows=catalog.filter(x=>x.page===page&&(!search||((saved[x.id]??x.text)+' '+x.text).toLowerCase().includes(search.toLowerCase())))
 return <section className="page"><h1>Screen Wording</h1><p>Choose a page or shared component, then edit its labels and instructions. Your changes apply to everyone at this location. Guest check-in wording is public.</p><label>Page<select value={page} onChange={e=>{setPage(e.target.value);setEdit(null)}}>{pages.map(p=><option key={p}>{p.replace(/([a-z])([A-Z])/g,'$1 $2')}</option>)}</select></label><label>Search wording<input value={search} onChange={e=>setSearch(e.target.value)}/></label>{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{rows.map(row=><article key={row.id} style={{padding:12,border:'1px solid var(--border, #d7c2af)',borderRadius:12,marginTop:12}}><p style={{whiteSpace:'pre-wrap'}}>{saved[row.id]??row.text}</p><button type="button" disabled={!location||busy} onClick={()=>setEdit({id:row.id,text:saved[row.id]??row.text,original:row.text})}>Edit wording</button></article>)}{!rows.length&&<p>No matching wording.</p>}{edit&&<dialog open style={{position:'fixed',top:'10vh',margin:'auto',width:'min(90vw, 600px)',maxHeight:'80vh',overflow:'auto',zIndex:1000,padding:24,borderRadius:16,boxShadow:'0 0 0 100vmax #0008'}} aria-labelledby="wording-title"><h2 id="wording-title">Edit wording</h2><p>Default: {edit.original}</p><label>New wording<textarea maxLength={2000} rows={5} value={edit.text} onChange={e=>setEdit({...edit,text:e.target.value})}/></label><h3>Preview</h3><p style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{edit.text}</p><div style={{display:'flex',flexWrap:'wrap',gap:10}}><button disabled={busy||!edit.text.trim()} onClick={()=>void save()}>Save wording</button><button disabled={busy} onClick={()=>void save(true)}>Restore default</button><button disabled={busy} onClick={()=>setEdit(null)}>Cancel</button></div></dialog>}</section>
}
