import { useEffect, useRef, useState } from 'react'
import { supabase } from '../lib/supabase'
import { loadTenantData } from '../lib/tenant'
import { loadLocationTeam, type TeamMember } from '../lib/team'
import { serviceDay, serviceDateLabel } from '../lib/serviceDay'
import { AssignedTaskLists } from '../components/AssignedTaskLists'
import './TasksPage.css'
type Template={id:string;title:string;position:string;phase:string;items:string[];source_note:string;reviewed:boolean;version:number}
const message=(e:unknown)=>String((e as {message?:string})?.message??e)
export function TasksPage(){
 const [location,setLocation]=useState(''),[manager,setManager]=useState(false),[day,setDay]=useState(serviceDay),[templates,setTemplates]=useState<Template[]>([]),[staff,setStaff]=useState<TeamMember[]>([]),[selected,setSelected]=useState(''),[users,setUsers]=useState<string[]>([]),[shift,setShift]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[refresh,setRefresh]=useState(0)
 const [edit,setEdit]=useState<Template|null>(null),[editing,setEditing]=useState(false),[title,setTitle]=useState(''),[position,setPosition]=useState('Server'),[phase,setPhase]=useState('Opening'),[items,setItems]=useState(''),[reviewed,setReviewed]=useState(false)
 const request=useRef<string|null>(null)
 useEffect(()=>{let live=true;void(async()=>{try{const t=await loadTenantData();const loc=t.locations[0]?.id;if(!loc)throw Error('No active location.');const access=await supabase.rpc('staff_tasks_can_manage',{p_location_id:loc});if(access.error)throw access.error;if(live){setLocation(loc);setManager(!!access.data)}}catch(e){if(live)setError(message(e))}})();return()=>{live=false}},[])
 useEffect(()=>{if(!location||!manager)return;let live=true;void Promise.all([supabase.rpc('staff_tasks_templates',{p_location_id:location}),loadLocationTeam(location)]).then(([r,team])=>{if(r.error)throw r.error;if(live){setTemplates(r.data??[]);setStaff(team.filter(m=>m.status==='active'))}}).catch(e=>{if(live)setError(message(e))});return()=>{live=false}},[location,manager,refresh])
 const template=templates.find(t=>t.id===selected)
 function start(t:Template|null){if(editing&&!window.confirm('Discard your unsaved list edits?'))return;setEdit(t);setTitle(t?.title??'');setPosition(t?.position??'Server');setPhase(t?.phase??'Opening');setItems(t?.items.join('\n')??'');setReviewed(t?.reviewed??false);setEditing(true);setError('');setNotice('')}
 async function save(){setBusy(true);setError('');try{const r=await supabase.rpc('staff_tasks_save_template',{p_location_id:location,p_id:edit?.id??null,p_version:edit?.version??null,p_title:title,p_position:position,p_phase:phase,p_items:items.split('\n').map(s=>s.trim()).filter(Boolean),p_reviewed:reviewed});if(r.error)throw r.error;setSelected(r.data);setEditing(false);setRefresh(v=>v+1);setNotice('List saved. Existing daily assignments keep their original tasks.')}catch(e){setError(message(e))}finally{setBusy(false)}}
 async function assign(){if(!template||!users.length||busy)return;setBusy(true);setError('');request.current??=crypto.randomUUID();try{const r=await supabase.rpc('staff_tasks_assign',{p_location_id:location,p_template_id:template.id,p_version:template.version,p_day:day,p_shift:shift,p_users:users,p_request_id:request.current});if(r.error)throw r.error;request.current=null;setUsers([]);setRefresh(v=>v+1);setNotice('Assigned '+template.title+'. Each employee has their own checklist.')}catch(e){setError(message(e))}finally{setBusy(false)}}
 const invalidate=()=>{request.current=null;setNotice('')}
 return <section className="page tasks-page"><p className="eyebrow">Daily responsibilities</p><h1>Task Lists</h1><label>Service day<input type="date" value={day} disabled={busy} onChange={e=>{if(e.target.value){setDay(e.target.value);invalidate()}}}/></label><p className="muted">{serviceDateLabel(day)} · Daily lists stay available in history after the 4 AM rollover.</p>{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{!location&&!error&&<p role="status">Loading tasks…</p>}
 {location&&<><h2>My task lists</h2><AssignedTaskLists location={location} day={day} refresh={refresh}/></>}
 {manager&&<><article className="task-card"><h2>Assign a list</h2><p>Select a position list and one or more employees. Each person checks off their own copy.</p><fieldset disabled={busy||editing}><label>List<select value={selected} onChange={e=>{setSelected(e.target.value);invalidate()}}><option value="">Choose a list</option>{templates.map(t=><option key={t.id} value={t.id}>{t.title}{t.reviewed?'':' · Needs review'}</option>)}</select></label>{template&&<><p className="muted">{template.source_note}</p><details><summary>Preview {template.items.length} tasks</summary><ol>{template.items.map((s,i)=><li key={i}>{s}</li>)}</ol></details><button type="button" onClick={()=>start(template)}>Edit / Review list</button>{!template.reviewed&&<p>Review and save this older list before assigning it.</p>}</>}<label>Shift or area (optional)<input maxLength={100} value={shift} placeholder="Dinner · Main Bar" onChange={e=>{setShift(e.target.value);invalidate()}}/></label><div className="task-staff">{staff.map(m=><label key={m.user_id}><input type="checkbox" checked={users.includes(m.user_id)} onChange={e=>{setUsers(v=>e.target.checked?[...v,m.user_id]:v.filter(u=>u!==m.user_id));invalidate()}}/><span>{m.profile?.preferred_name||m.profile?.full_name||'Team Member'} <small>{m.role.replace(/_/g,' ')}</small></span></label>)}</div><button type="button" disabled={!template?.reviewed||!users.length} onClick={()=>void assign()}>Assign to {users.length} employee{users.length===1?'':'s'}</button><button type="button" onClick={()=>start(null)}>Create a new list</button></fieldset></article>
 {editing&&<article className="task-card"><h2>{edit?'Edit task list':'New task list'}</h2><form onSubmit={e=>{e.preventDefault();void save()}}><fieldset disabled={busy}><label>List title<input required maxLength={200} value={title} onChange={e=>{setTitle(e.target.value);setReviewed(false)}}/></label><label>Position<input required maxLength={100} value={position} onChange={e=>{setPosition(e.target.value);setReviewed(false)}}/></label><label>Phase<select value={phase} onChange={e=>{setPhase(e.target.value);setReviewed(false)}}>{['Opening','Running','Closing','Weekly','Other'].map(p=><option key={p}>{p}</option>)}</select></label><label>Tasks — one per line<textarea required rows={12} maxLength={200000} value={items} onChange={e=>{setItems(e.target.value);setReviewed(false)}}/></label><p>Add, edit, remove or paste tasks here. Each line becomes a checkbox.</p><label className="task-review"><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>I reviewed this list for current operations.</label><button type="submit">Save list</button><button type="button" onClick={()=>{if(window.confirm('Discard these list edits?'))setEditing(false)}}>Cancel</button></fieldset></form></article>}
 <h2>Team progress</h2><AssignedTaskLists location={location} day={day} team refresh={refresh}/></>}
 </section>
}
