import { useEffect, useRef, useState } from 'react'
import { serviceDay } from '../lib/serviceDay'
import { supabase } from '../lib/supabase'
import '../components/WalkinsTeam.css'
export function WalkInPage({publicKey}:{publicKey:string}) {
 const [location,setLocation]=useState(''),[ready,setReady]=useState(false),[error,setError]=useState(''),[sent,setSent]=useState(false),[busy,setBusy]=useState(false)
 const [name,setName]=useState(''),[email,setEmail]=useState(''),[phone,setPhone]=useState(''),[party,setParty]=useState('2'),[opt,setOpt]=useState(false),[website,setWebsite]=useState('')
 const saving=useRef(false),request=useRef('')
 useEffect(()=>{let live=true;void(async()=>{try{if(!/^[0-9a-f-]{36}$/i.test(publicKey))throw Error('This check-in link is invalid. Please see the host.');const r=await supabase.rpc('walkin_config',{p_key:publicKey});if(r.error)throw r.error;if(!r.data?.enabled)throw Error('Check-in is unavailable. Please see the host.');if(live){setLocation(r.data.name);setReady(true);try{if(sessionStorage.getItem('walkin-complete:'+publicKey)===serviceDay())setSent(true)}catch{/* Check-in works even when browser storage is unavailable. */}}}catch(e){if(live)setError(String((e as {message?:string}).message??e))}})();return()=>{live=false}},[publicKey])
 async function submit(e:React.FormEvent){e.preventDefault();if(saving.current)return;saving.current=true;setBusy(true);setError('');try{if(!request.current){const storageKey='walkin-request:'+publicKey+':'+serviceDay();try{request.current=sessionStorage.getItem(storageKey)||crypto.randomUUID();sessionStorage.setItem(storageKey,request.current)}catch{request.current=crypto.randomUUID()}}const r=await supabase.rpc('walkin_submit',{p_key:publicKey,p_request_id:request.current,p_name:name,p_email:email,p_phone:phone,p_party:Number(party),p_opt_in:opt,p_website:website});if(r.error)throw r.error;setSent(true);try{sessionStorage.removeItem('walkin-request:'+publicKey+':'+serviceDay());sessionStorage.setItem('walkin-complete:'+publicKey,serviceDay())}catch{/* Submission already succeeded. */}}catch(e){setError(String((e as {message?:string}).message??e))}finally{saving.current=false;setBusy(false)}}
 return <main className="guest-checkin"><p className="eyebrow">{location||'JusTini’s'}</p><h1>Walk-in check-in</h1>{sent?<section role="status"><h2>You’re checked in!</h2><p>Please check in with the host.</p><p>This check-in is not a reservation.</p></section>:<><p>Check in with the host.</p>{!ready&&!error&&<p>Loading…</p>}{ready&&<form onSubmit={submit}><fieldset disabled={busy}><label>Your name<input required autoComplete="name" maxLength={120} value={name} onChange={e=>setName(e.target.value)}/></label><label>Email<input required type="email" autoComplete="email" maxLength={320} value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Phone number <span className="muted">optional</span><input type="tel" autoComplete="tel" maxLength={40} value={phone} onChange={e=>setPhone(e.target.value)}/></label><label>Number in your party<input required type="number" inputMode="numeric" min={1} max={100} step={1} value={party} onChange={e=>setParty(e.target.value)}/></label><label className="wt-checkbox"><input type="checkbox" checked={opt} onChange={e=>setOpt(e.target.checked)}/>Email me JusTini’s news, events and offers.</label><p className="muted">Your details are used for your visit. Joining the mailing list is optional.</p><label className="wt-honeypot" aria-hidden="true">Website<input tabIndex={-1} autoComplete="off" value={website} onChange={e=>setWebsite(e.target.value)}/></label><button className="primary-button" type="submit">{busy?'Checking you in…':'Check in'}</button></fieldset></form>}</>}{error&&<p role="alert">{error}</p>}</main>
}
