import { useCallback, useEffect, useState } from 'react'
import { supabase } from '../lib/supabase'
import { taskGroups } from '../lib/taskGroups'
import { submissionLabel } from '../lib/submissionTime'
import '../pages/TasksPage.css'
export type TaskRun={id:string;title:string;position:string;phase:string;items:string[];shift_label:string;business_date:string;user_id:string;name:string;version:number;checks:{index:number;at:string}[]}
const errorText=(e:unknown)=>String((e as {message?:string})?.message??e)
export function AssignedTaskLists({location,day,team=false,refresh=0}:{location:string;day:string;team?:boolean;refresh?:number}){
 const [runs,setRuns]=useState<TaskRun[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState('')
 const load=useCallback(async()=>{const r=await supabase.rpc('staff_tasks_day',{p_location_id:location,p_day:day,p_team:team});if(r.error)throw r.error;return (r.data??[]) as TaskRun[]},[location,day,team])
 useEffect(()=>{let live=true,fetching=false;setRuns([]);setLoading(true);setError('');async function update(){if(!location||fetching)return;fetching=true;try{const data=await load();if(live){setRuns(data);setError('')}}catch(e){if(live)setError(errorText(e))}finally{fetching=false;if(live)setLoading(false)}}void update();const visible=()=>{if(document.visibilityState==='visible')void update()};const timer=setInterval(visible,30000);window.addEventListener('focus',visible);document.addEventListener('visibilitychange',visible);return()=>{live=false;clearInterval(timer);window.removeEventListener('focus',visible);document.removeEventListener('visibilitychange',visible)}},[load,location,refresh])
 async function toggle(run:TaskRun,index:number,done:boolean){if(busy)return;setBusy(run.id);setError('');try{const r=await supabase.rpc('staff_tasks_check',{p_location_id:location,p_run_id:run.id,p_item:index,p_done:done,p_version:run.version});if(r.error)throw r.error;setRuns(await load())}catch(e){setError(errorText(e));try{setRuns(await load())}catch{/* Keep the original failure visible. */}}finally{setBusy('')}}
 async function remove(run:TaskRun){if(!window.confirm('Remove '+run.name+' from '+run.title+'? Their recorded check-offs will be retained.'))return;setBusy(run.id);try{const r=await supabase.rpc('staff_tasks_remove_assignee',{p_location_id:location,p_run_id:run.id,p_user_id:run.user_id});if(r.error)throw r.error;setRuns(await load())}catch(e){setError(errorText(e))}finally{setBusy('')}}
 return <div className="assigned-task-lists">{loading&&<p role="status">Loading task groups…</p>}{error&&<p role="alert">{error}</p>}{!loading&&!error&&!runs.length&&<p>No task groups assigned for this day.</p>}{runs.map(run=><article className="task-card" key={run.id+run.user_id}><h3>{run.title}</h3><p>{team?run.name+' · ':''}{run.shift_label||run.phase} · {run.checks.length}/{run.items.length} completed</p>{!team&&<p className="muted">Tap a group to open it, then tap a task or its checkbox to mark it complete.</p>}<progress max={run.items.length} value={run.checks.length} aria-label={run.title+' completion'} />{run.checks.length===run.items.length&&<p className="task-complete">✓ Group complete</p>}<div className="task-groups">{taskGroups(run.items,run.title).map((group,groupIndex)=>{const completed=group.tasks.filter(t=>run.checks.some(c=>c.index===t.index)).length;return <details className="task-group" key={group.title} open={!team&&groupIndex===0}><summary><span>{group.title}</span><strong>{completed}/{group.tasks.length} {completed===group.tasks.length?'✓':''}</strong></summary><div className="task-checkboxes">{group.tasks.map(({text,index})=>{const check=run.checks.find(c=>c.index===index);return <label className={check?'task-done':''} key={index}><input type="checkbox" checked={!!check} disabled={team||!!busy} onChange={e=>void toggle(run,index,e.target.checked)}/><span>{text}{check&&<small>Completed {submissionLabel(check.at)}</small>}</span></label>})}</div></details>})}</div>{team&&<button type="button" disabled={!!busy} onClick={()=>void remove(run)}>Remove assignment</button>}</article>)}</div>
}
