// page-designer-instrumented
import { PageWord, PageOption } from "./PageDesign"
import { ScreenText } from "./ScreenText"
import { ClockTime } from './ClockTime'
import { closeoutHours } from '../lib/closeoutHours'
import { useState } from 'react'
import { supabase } from '../lib/supabase'
import type { Question } from './CloseoutConfig'
export type EditableCloseout={id:string;edit_version?:number;scheduled_start:string|null;clock_in:string|null;clock_out?:string|null;job_role:string;shift_type?:string|null;net_sales:number;sales_target:number;cash_deposit:number;void_count:number;void_value:number;discount_value:number;notes:string|null;custom_answers?:Record<string,string>;question_snapshot?:Question[];zero_sales_confirmed?:boolean;zero_sales_reason?:string|null;completion_points_withheld?:boolean}
const amounts=[['net_sales','Net sales ($)'],['sales_target','Sales target ($)'],['cash_deposit','Cash deposit ($)'],['void_value','Voids ($)'],['discount_value','Discounts ($)'],['void_count','Number of voids']] as const
const roles={server:'Server',main_bartender:'Main Bartender',back_bartender_1:'Back Bartender 1',back_bar_service_bartender:'Back Bar Service Bartender',host:'Host',busser:'Busser',manager:'Manager',assistant_manager:'Assistant Manager',general_manager:'General Manager'}
export function CloseoutCorrectionEditor({closeout,locationId,name,onSaved,onCancel}:{closeout:EditableCloseout;locationId:string;name:string;onSaved:()=>void;onCancel:()=>void}){
 const [values,setValues]=useState(()=>Object.fromEntries(amounts.map(([key])=>[key,String(closeout[key] ?? '')])));const [scheduled,setScheduled]=useState(closeout.scheduled_start?.slice(0,5) ?? '');const [clock,setClock]=useState(closeout.clock_in?.slice(0,5) ?? '')
 const [clockOut,setClockOut]=useState(closeout.clock_out?.slice(0,5) ?? '')
 const [role,setRole]=useState(closeout.job_role);const [shift,setShift]=useState(closeout.shift_type ?? '');const [notes,setNotes]=useState(closeout.notes ?? '');const [answers,setAnswers]=useState(closeout.custom_answers ?? {})
 const [zeroConfirmed,setZeroConfirmed]=useState(closeout.zero_sales_confirmed ?? false);const [zeroReason,setZeroReason]=useState(closeout.zero_sales_reason ?? '')
 const [inaccurate,setInaccurate]=useState(true);const [reason,setReason]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('')
 async function save(){setBusy(true);setError('');try{
  const numbers:Record<string,number>={};for(const [key,label] of amounts){const raw=values[key]?.trim();if(!raw || !/^\d+(\.\d{1,2})?$/.test(raw) || !Number.isFinite(Number(raw)))throw new Error('Enter a valid '+label.toLowerCase()+'.');numbers[key]=Number(raw)}
  if(!Number.isInteger(numbers.void_count))throw new Error('Void count must be a whole number.')
  if(clockOut && closeoutHours(clock,clockOut)===null)throw new Error('Shift length must be greater than zero and no more than 18 hours.')
  const r=await supabase.rpc('closeout_manager_correct',{p_location_id:locationId,p_closeout_id:closeout.id,p_version:closeout.edit_version ?? 1,p_values:{...numbers,scheduled_start:scheduled,clock_in:clock,clock_out:clockOut || null,job_role:role,shift_type:shift,notes:notes.trim() || null,custom_answers:answers,zero_sales_confirmed:zeroConfirmed,zero_sales_reason:zeroReason.trim() || null},p_reason:reason.trim(),p_inaccurate:inaccurate});if(r.error)throw r.error;onSaved()
 }catch(e){setError(String((e as {message?:string})?.message ?? e))}finally{setBusy(false)}}
 return <form data-design-block="copy.698c8f566249e8f6.1" className="closeout-correction card" onSubmit={e=>{e.preventDefault();void save()}}><h3 data-design-block="copy.0f94176919254a5c.1"><ScreenText id="CloseoutCorrectionEditor.c1194181eb44cbe3">Edit / Review: </ScreenText>{name}</h3><p data-design-block="copy.ddec0b280890c344.1"><ScreenText id="CloseoutCorrectionEditor.f50113b995380bfd">Correct the original record. Sales-related points and the recap update automatically.</ScreenText></p><fieldset data-design-block="copy.29820849d6c79155.1" disabled={busy}><div data-design-block="copy.b0591e96049c0ec0.1" className="form-grid">
  <label data-design-block="copy.9edfd17460a3a4d4.1"><ScreenText id="CloseoutCorrectionEditor.c34fac7b67aabdec">Scheduled time</ScreenText><ClockTime required label="Scheduled time" value={scheduled} onChange={setScheduled} /></label><label data-design-block="copy.9edfd17460a3a4d4.2"><ScreenText id="CloseoutCorrectionEditor.dcc4312147f04470">Actual clock-in</ScreenText><ClockTime required label="Clock-in time" value={clock} onChange={setClock} /></label>
  <label data-design-block="copy.9edfd17460a3a4d4.3"><ScreenText id="CloseoutCorrectionEditor.adfae5ab1d496a32">Actual clock-out</ScreenText><ClockTime required={!!closeout.clock_out} label="Clock-out time" value={clockOut} onChange={setClockOut} /><small><ScreenText id="CloseoutCorrectionEditor.9228f576057242d7">Older forms may have no recorded clock-out.</ScreenText></small></label>
  <label data-design-block="copy.9edfd17460a3a4d4.4"><ScreenText id="CloseoutCorrectionEditor.fb8900bc33772b2f">Role worked</ScreenText><select value={role} onChange={e=>setRole(e.target.value)}>{Object.entries(roles).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>
  <label data-design-block="copy.9edfd17460a3a4d4.5"><ScreenText id="CloseoutCorrectionEditor.b6bca714113a1856">Shift</ScreenText><select value={shift} onChange={e=>setShift(e.target.value)}><PageOption designId="copy.5cc2e261925cd46f.1" value=""><ScreenText plain id="CloseoutCorrectionEditor.37d96a6d86fed9b0">Not recorded</ScreenText></PageOption><PageOption designId="copy.69888b6995601837.1" value="AM"><ScreenText plain id="CloseoutCorrectionEditor.17f55620f29a9483">AM</ScreenText></PageOption><PageOption designId="copy.262fe2e80874e35a.1" value="PM"><ScreenText plain id="CloseoutCorrectionEditor.1d898d87bd994294">PM</ScreenText></PageOption><PageOption designId="copy.76e5a4106a86001a.1" value="TO_VOLUME"><ScreenText plain id="CloseoutCorrectionEditor.ac6d102c4ab95530">To volume</ScreenText></PageOption></select></label>
  {amounts.map(([key,label])=><label data-design-block="copy.99b207d9d339e6c1.1" key={key}>{label}<input type="text" inputMode={key==='void_count'?'numeric':'decimal'} required value={values[key]} onChange={e=>{setValues(v=>({...v,[key]:e.target.value}));if(key==='net_sales')setZeroConfirmed(false)}} /></label>)}
 </div>
 {Number(values.net_sales)===0 && <div data-design-block="copy.3cca560705d78c7f.1" className="closeout-warning"><label data-design-block="copy.279cb0bc8704e144.1" className="closeout-check"><input type="checkbox" checked={zeroConfirmed} onChange={e=>setZeroConfirmed(e.target.checked)} /><span><ScreenText id="CloseoutCorrectionEditor.afa1e54e9c3c029c">I verified that $0 sales is accurate.</ScreenText></span></label><label data-design-block="copy.9edfd17460a3a4d4.6"><ScreenText id="CloseoutCorrectionEditor.d5457e12492edb33">Reason for zero sales</ScreenText><textarea rows={2} maxLength={2000} value={zeroReason} onChange={e=>setZeroReason(e.target.value)} /></label><p data-design-block="copy.ddec0b280890c344.2"><ScreenText id="CloseoutCorrectionEditor.8175e11402fcf275">If this is an incorrect zero that still needs correction, leave it unconfirmed and mark the original submission inaccurate below.</ScreenText></p></div>}
 {closeout.question_snapshot?.filter(q=>!q.builtin).map(q=><label data-design-block="copy.c3b0df37b5691dfe.1" key={q.id}>{q.label}{q.type==='yesno'?<select required={q.required} value={answers[q.id] ?? ''} onChange={e=>setAnswers(v=>({...v,[q.id]:e.target.value}))}><PageOption designId="copy.4220016173a1f5d1.1" value=""><ScreenText plain id="CloseoutCorrectionEditor.ccfdd0f89d522c38">Choose an answer</ScreenText></PageOption><PageOption designId="copy.f43b586a7de363bc.1" value="yes"><ScreenText plain id="CloseoutCorrectionEditor.8670cf6f8bcb4c31">Yes</ScreenText></PageOption><PageOption designId="copy.bf48bf1a3a9a46aa.1" value="no"><ScreenText plain id="CloseoutCorrectionEditor.c684d2565fbd1f56">No</ScreenText></PageOption></select>:<textarea required={q.required} rows={2} maxLength={2000} value={answers[q.id] ?? ''} onChange={e=>setAnswers(v=>({...v,[q.id]:e.target.value}))} />}</label>)}
 <label data-design-block="copy.9edfd17460a3a4d4.7"><ScreenText id="CloseoutCorrectionEditor.234447786cf05bff">Notes</ScreenText><textarea rows={2} value={notes} onChange={e=>setNotes(e.target.value)} /></label>
 <label data-design-block="copy.279cb0bc8704e144.2" className="closeout-check"><input type="checkbox" checked={inaccurate || !!closeout.completion_points_withheld} disabled={!!closeout.completion_points_withheld} onChange={e=>setInaccurate(e.target.checked)} /><span><ScreenText id="CloseoutCorrectionEditor.ddd33a17634bc331">The original submission was inaccurate. Withhold its closeout completion bonus.</ScreenText></span></label>
 <p data-design-block="copy.ddec0b280890c344.3"><ScreenText id="CloseoutCorrectionEditor.195b413a6828df65">Correcting the form does not automatically restore this bonus. The GM can restore it from the Points page. Leave this unchecked for a clarification to an otherwise accurate submission.</ScreenText></p>
 <label data-design-block="copy.9edfd17460a3a4d4.8"><ScreenText id="CloseoutCorrectionEditor.1abf9b4fc9a29c70">Correction / review reason</ScreenText><textarea required maxLength={2000} rows={2} value={reason} onChange={e=>setReason(e.target.value)} /></label>
 {error && <p data-design-block="copy.7b1d16b61cd28a8d.1" role="alert">{error}</p>}<div data-design-block="copy.eccfb288a3f306f8.1" className="closeout-actions"><button data-design-block="copy.310451acfdbd3d05.1" className="primary-button" disabled={busy}>{busy?<PageWord id="copy.e0419d42cf12e59d.1">{"Saving…"}</PageWord>:<PageWord id="copy.cfbb74f554fd0ba2.1">{"Save correction / review"}</PageWord>}</button><button data-design-block="copy.1fa67428815fe6c1.1" type="button" disabled={busy} onClick={onCancel}><ScreenText id="CloseoutCorrectionEditor.b72759632737e7c0">Cancel</ScreenText></button></div></fieldset></form>
}

