import { useEffect,useRef,useState } from 'react'
import { Link } from 'react-router-dom'
import { supabase } from '../lib/supabase'
import { salesMoney } from '../lib/salesTargets'
type Detail={id:string;date:string;role:string;shift:string|null;scheduled_start:string|null;clock_in:string|null;clock_out:string|null;net_sales:number;sales_target:number;cash_deposit:number;void_count:number;void_value:number;discount_value:number;notes:string|null;submitted_at:string|null;points_delta:number;questions:{id:string;label:string}[];answers:Record<string,string>;zero_sales_reason:string|null;tables:string[];can_review:boolean}
export function EmployeeCloseoutDetails({locationId,closeoutId,onClose}:{locationId:string;closeoutId:string;onClose:()=>void}){
 const dialog=useRef<HTMLDialogElement>(null),[data,setData]=useState<Detail|null>(null),[error,setError]=useState('')
 useEffect(()=>{const el=dialog.current;el?.showModal();return()=>el?.close()},[])
 useEffect(()=>{let live=true;setData(null);setError('');void supabase.rpc('team_closeout_detail',{p_location_id:locationId,p_closeout_id:closeoutId}).then(r=>{if(!live)return;if(r.error)setError(r.error.message);else setData(r.data)});return()=>{live=false}},[locationId,closeoutId])
 return <dialog ref={dialog} className="wt-dialog" aria-labelledby="closeout-details-heading" onCancel={onClose}><button type="button" className="wt-close" onClick={onClose} aria-label="Close closeout details">×</button><h2 id="closeout-details-heading">Closeout details</h2>{error&&<p role="alert">{error}</p>}{!data&&!error&&<p role="status">Loading closeout…</p>}{data&&<><p>{data.date} · {data.role.replace(/_/g,' ')} · {data.shift||'Shift not recorded'}</p><div className="wt-stats">{[['Net sales',salesMoney(Number(data.net_sales))],['Sales target',salesMoney(Number(data.sales_target))],['Cash deposit',salesMoney(Number(data.cash_deposit))],['Voids',data.void_count+' · '+salesMoney(Number(data.void_value))],['Discounts',salesMoney(Number(data.discount_value))],['Points',String(data.points_delta)]].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><p>Scheduled: {data.scheduled_start||'—'} · Clock in: {data.clock_in||'—'} · Clock out: {data.clock_out||'—'}</p><p>Tables: {data.tables.join(', ')||'Not recorded'}</p>{data.submitted_at&&<p>Submitted: {new Date(data.submitted_at).toLocaleString('en-US',{timeZone:'America/Chicago'})} CT</p>}{data.zero_sales_reason&&<p>Zero-sales reason: {data.zero_sales_reason}</p>}<h3>Notes</h3><p style={{whiteSpace:'pre-wrap'}}>{data.notes||'No notes.'}</p>{data.questions?.map(q=><div key={q.id}><strong>{q.label}</strong><p style={{whiteSpace:'pre-wrap'}}>{data.answers?.[q.id]||'—'}</p></div>)}<Link className="primary-button" to={'/closeout-summary?date='+encodeURIComponent(data.date)+'&closeout='+encodeURIComponent(data.id)}>{data.can_review?'Open closeout to review / edit':'Open closeout'}</Link></>}</dialog>
}
