import { useEffect,useRef,useState } from 'react'
import { createPortal } from 'react-dom'
import { supabase } from '../lib/supabase'
import { salesMoney } from '../lib/salesTargets'
import './IncomingInventory.css'
type Line={item:string;size:string;quantity:string;pack_size:string;unit_cost:string}
type Receipt={user_id:string;id:string;file_path:string;status:string;has_file:boolean;vendor:string;invoice_number:string;received_date:string;receipt_total:number|null;notes:string;lines:{item:string;size:string;quantity:number;pack_size:number;unit_cost:number|null}[];employee:string;extraction:any}
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Chicago',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())
const blank=():Line=>({item:'',size:'',quantity:'',pack_size:'',unit_cost:''})
const editable=(lines:any[])=>lines.map(l=>({item:String(l.item??''),size:String(l.size??''),quantity:l.quantity==null?'':String(l.quantity),pack_size:l.pack_size==null?'':String(l.pack_size),unit_cost:l.unit_cost==null?'':String(l.unit_cost)}))
function ReceiptViewer({url,error,loading,pdf,onClose}:{url:string;error:string;loading:boolean;pdf:boolean;onClose:()=>void}){
 const ref=useRef<HTMLDialogElement>(null),close=useRef(onClose);close.current=onClose
 useEffect(()=>{const d=ref.current;if(!d)return;d.showModal();const cancel=(e:Event)=>{e.preventDefault();close.current()};d.addEventListener('cancel',cancel);return()=>{d.removeEventListener('cancel',cancel);d.close()}},[])
 return createPortal(<dialog ref={ref} className="receipt-viewer" aria-labelledby="receipt-view-title"><header><h2 id="receipt-view-title">Receipt file</h2><button type="button" onClick={onClose}>Close</button></header>{loading&&<p role="status">Loading receipt…</p>}{error&&<p role="alert">{error}</p>}{url&&<><a href={url} target="_blank" rel="noreferrer">Open or download original</a>{pdf?<iframe src={url} title="Original receipt PDF"/>:<img src={url} alt="Uploaded receipt" onError={e=>{e.currentTarget.hidden=true}}/>}<p>Private link expires in 10 minutes.</p></>}</dialog>,document.body)
}
const number=(value:string)=>value.trim()?Number(value):null
export function IncomingInventory({locationId,brands}:{locationId:string;brands:string[]}){
 const [receipts,setReceipts]=useState<Receipt[]>([]),[active,setActive]=useState<Receipt|null>(null),[lines,setLines]=useState<Line[]>([]),[vendor,setVendor]=useState(''),[invoice,setInvoice]=useState(''),[received,setReceived]=useState(today),[total,setTotal]=useState(''),[notes,setNotes]=useState(''),[warnings,setWarnings]=useState<string[]>([]),[reviewed,setReviewed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[start,setStart]=useState(()=>today().slice(0,7)+'-01'),[end,setEnd]=useState(today),[manager,setManager]=useState(false),[viewUrl,setViewUrl]=useState(''),[viewer,setViewer]=useState('')
 const lock=useRef(false),editor=useRef<HTMLFieldSetElement>(null),status=useRef<HTMLDivElement>(null),sourceRequest=useRef(0)
 const [viewOpen,setViewOpen]=useState(false),[viewError,setViewError]=useState(''),[viewBusy,setViewBusy]=useState(false),[viewPdf,setViewPdf]=useState(false)
 function reveal(){requestAnimationFrame(()=>status.current?.scrollIntoView({block:'start',behavior:'smooth'}))}
 useEffect(()=>{if(error||message)reveal()},[error,message])
 useEffect(()=>{if(!active)return;const warn=(event:BeforeUnloadEvent)=>{event.preventDefault();event.returnValue=''};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[active])
 useEffect(()=>{void supabase.auth.getUser().then(r=>setViewer(r.data.user?.id??''))},[])
 async function load(){const r=await supabase.rpc('inventory_receipt_report',{p_location_id:locationId,p_start:start,p_end:end});if(r.error)throw r.error;setReceipts(r.data.receipts);setManager(r.data.manager)}
 useEffect(()=>{if(!locationId)return;let live=true;setReceipts([]);setError('');void supabase.rpc('inventory_receipt_report',{p_location_id:locationId,p_start:start,p_end:end}).then(r=>{if(!live)return;if(r.error)setError(r.error.message);else{setReceipts(r.data.receipts);setManager(r.data.manager)}});return()=>{live=false}},[locationId,start,end])
 function draft(r:Receipt){const x=r.extraction??r;setActive(r);setLines(editable(x.lines??[]));setVendor(x.vendor??'');setInvoice(x.invoice_number??'');setReceived(x.received_date??today());setTotal(x.receipt_total==null?'':String(x.receipt_total));setNotes(r.notes??'');setWarnings(x.warnings??[]);setReviewed(false);setViewUrl('');setError('');setMessage('');requestAnimationFrame(()=>editor.current?.scrollIntoView({block:'start',behavior:'smooth'}))}
 async function upload(file?:File){if(!file||lock.current)return;if(active&&!window.confirm('Replace this draft? Unsaved edits will be lost. The previous receipt remains in drafts.'))return;setError('');setMessage('');if(!['image/jpeg','image/png','image/webp','application/pdf'].includes(file.type)||file.size>10485760){setError('Choose JPG, PNG, WebP or PDF up to 10 MB. Export HEIC photos as JPG.');return}lock.current=true;setBusy(true);try{const r=await supabase.rpc('inventory_receipt_create',{p_location_id:locationId,p_request_id:crypto.randomUUID(),p_mime:file.type});if(r.error)throw r.error;const result=await supabase.storage.from('inventory-receipts').upload(r.data.file_path,file,{contentType:file.type,upsert:false});if(result.error)throw result.error;draft({...r.data,has_file:true});setMessage('Receipt uploaded. Scan it, or enter its items manually.');await load()}catch(e){setError((e as Error).message)}finally{lock.current=false;setBusy(false)}}
 async function scan(){if(!active||lock.current)return;if(lines.length&&!window.confirm('Replace the current item edits with scanned results?'))return;lock.current=true;setBusy(true);setError('');setMessage('Reading receipt…');try{const r=await supabase.functions.invoke('inventory-receipt-scan',{body:{receipt_id:active.id}});if(r.error){let reason=r.error.message;const context=(r.error as any).context;if(context?.json){try{reason=(await context.json()).error??reason}catch{}}throw Error(reason)}if(r.data?.error)throw Error(r.data.error);const x=r.data?.extraction;if(!x||!Array.isArray(x.lines))throw Error('The scan returned no usable result. Check the receipt-scanning deployment and try again.');draft({...active,extraction:x});if(!x.lines.length){setError('No inventory items were read. Try a clearer receipt or add the items manually.');setMessage('')}else setMessage('Scan ready: '+x.lines.length+' item rows. Review every item, pack size and cost before saving.');try{await load()}catch{setError('Scan result is shown below, but the report could not refresh.')} }catch(e){setMessage('');setError((e as Error).message)}finally{lock.current=false;setBusy(false)}}
 function edit(index:number,key:keyof Line,value:string){setLines(v=>v.map((l,i)=>i===index?{...l,[key]:value}:l));setReviewed(false)}
 async function submit(){if(!active||lock.current)return;setError('');if(!reviewed){setError('Confirm that you reviewed the quantities.');return}const values=lines.map(l=>({...l,item:l.item.trim(),size:l.size.trim(),quantity:number(l.quantity),pack_size:number(l.pack_size),unit_cost:number(l.unit_cost)}));if(!values.length||values.some(l=>!l.item||!l.size||l.quantity==null||!Number.isFinite(l.quantity)||l.quantity<=0||l.pack_size==null||!Number.isInteger(l.pack_size)||l.pack_size<1||(l.unit_cost!=null&&(!Number.isFinite(l.unit_cost)||l.unit_cost<0)))){setError('Fill in each item, size/unit, quantity and units per pack. Leave unreadable costs blank.');return}lock.current=true;setBusy(true);try{const r=await supabase.rpc('inventory_receipt_submit',{p_id:active.id,p_values:{vendor,invoice_number:invoice,received_date:received,receipt_total:number(total),notes,lines:values,reviewed:true}});if(r.error)throw r.error;setActive(null);setLines([]);setMessage('Incoming inventory slip saved and linked to the receipt.');try{await load()}catch{setError('Slip saved. Report refresh failed; use Refresh report.')}}catch(e){setError((e as Error).message)}finally{lock.current=false;setBusy(false)}}
 async function source(r:Receipt){const ticket=++sourceRequest.current;setViewOpen(true);setViewUrl('');setViewError('');setViewPdf(r.file_path.toLowerCase().endsWith('.pdf'));setViewBusy(true);try{if(!r.has_file||!r.file_path)throw Error('This draft has no uploaded file. Upload the receipt again.');const x=await supabase.storage.from('inventory-receipts').createSignedUrl(r.file_path,600);if(x.error)throw x.error;if(!x.data?.signedUrl)throw Error('Receipt link was not returned.');if(ticket===sourceRequest.current)setViewUrl(x.data.signedUrl)}catch(e){if(ticket===sourceRequest.current)setViewError((e as Error).message||'Unable to open the receipt.')}finally{if(ticket===sourceRequest.current)setViewBusy(false)}}

 const submitted=receipts.filter(r=>r.status==='submitted'),suggestions=[...new Set([...brands,...submitted.flatMap(r=>r.lines.map(l=>l.item))])].sort(),groups=new Map<string,{item:string;size:string;units:number;cost:number;unknown:boolean}>()
 for(const r of submitted)for(const l of r.lines){const key=l.item.trim().toLowerCase()+'|'+l.size.trim().toLowerCase(),g=groups.get(key)??{item:l.item,size:l.size,units:0,cost:0,unknown:false};g.units+=Number(l.quantity)*Number(l.pack_size);if(l.unit_cost==null)g.unknown=true;else g.cost+=Number(l.quantity)*Number(l.unit_cost);groups.set(key,g)}
 function csv(){const cell=(v:unknown)=>{let s=String(v??'');if(/^[\s]*[=+@-]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"'};const rows:unknown[][]=[['Received date','Vendor','Invoice','Employee','Item','Size/unit','Packs received','Units per pack','Units received','Cost per pack','Line cost','Receipt total']];for(const r of submitted)for(const l of r.lines)rows.push([r.received_date,r.vendor,r.invoice_number,r.employee,l.item,l.size,l.quantity,l.pack_size,Number(l.quantity)*Number(l.pack_size),l.unit_cost,l.unit_cost==null?'':Number(l.quantity)*Number(l.unit_cost),r.receipt_total]);const url=URL.createObjectURL(new Blob(['\uFEFF'+rows.map(row=>row.map(cell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=url;a.download='incoming-inventory-'+start+'-'+end+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 return <section className="incoming-inventory"><h1>Incoming inventory</h1><p>Upload a receipt, review its items, then save a receiving slip. Nothing is posted to the report until you submit it.</p><div ref={status} className="receipt-status">{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}</div>{viewOpen&&<ReceiptViewer url={viewUrl} error={viewError} loading={viewBusy} pdf={viewPdf} onClose={()=>{sourceRequest.current++;setViewOpen(false);setViewUrl('')}}/>}
 <div className="inventory-card receipt-drop" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();void upload(e.dataTransfer.files[0])}}><label>Upload or drop a receipt<input type="file" accept="image/jpeg,image/png,image/webp,application/pdf" disabled={busy||!locationId} onChange={e=>{void upload(e.target.files?.[0]);e.target.value=''}}/></label><label>Take a receipt photo<input type="file" accept="image/*" capture="environment" disabled={busy||!locationId} onChange={e=>{void upload(e.target.files?.[0]);e.target.value=''}}/></label><small>JPG, PNG, WebP or PDF · up to 10 MB · one file per slip. Combine invoice pages into a PDF.</small></div>
 {active&&<fieldset ref={editor} disabled={busy} className="inventory-card receipt-editor"><legend>Review incoming slip</legend><button type="button" disabled={!active.has_file} onClick={()=>void scan()}>{busy?'Working…':'Scan receipt'}</button><button type="button" onClick={()=>void source(active)}>View original</button><p>Scanning uses the configured receipt-reading service. Manual entry works without it.</p>{warnings.map((w,i)=><p className="receipt-warning" key={i}>{w}</p>)}<div className="receipt-fields"><label>Vendor<input value={vendor} onChange={e=>{setVendor(e.target.value);setReviewed(false)}} maxLength={200}/></label><label>Invoice / receipt number<input value={invoice} onChange={e=>{setInvoice(e.target.value);setReviewed(false)}} maxLength={200}/></label><label>Received date<input type="date" max={today()} value={received} onChange={e=>{setReceived(e.target.value);setReviewed(false)}}/></label><label>Receipt total ($), optional<input type="number" min="0" step="0.01" value={total} onChange={e=>{setTotal(e.target.value);setReviewed(false)}}/></label></div><datalist id="receipt-item-list">{suggestions.map(s=><option key={s} value={s}/>)}</datalist><datalist id="receipt-size-list">{['1.75 L','1 L','750 mL','Pint','each','lb','oz'].map(s=><option key={s} value={s}/>)}</datalist><p>For two cases of twelve: quantity = 2, units per pack = 12. Cost per pack means the cost of one case. For individual bottles, units per pack = 1.</p>
 {lines.map((l,i)=><div className="receipt-line" key={i}><strong>Item {i+1}</strong><label>Item / brand<input list="receipt-item-list" value={l.item} onChange={e=>edit(i,'item',e.target.value)} maxLength={200}/></label><label>Bottle size or unit<input list="receipt-size-list" value={l.size} onChange={e=>edit(i,'size',e.target.value)} maxLength={80}/></label><label>Quantity of packs<input type="number" min="0.001" max="10000" step="0.001" value={l.quantity} onChange={e=>edit(i,'quantity',e.target.value)}/></label><label>Units per pack<input type="number" min="1" max="1000" step="1" value={l.pack_size} onChange={e=>edit(i,'pack_size',e.target.value)}/></label><label>Cost per pack ($), optional<input type="number" min="0" max="1000000" step="0.01" value={l.unit_cost} onChange={e=>edit(i,'unit_cost',e.target.value)}/></label><p>{l.quantity&&l.pack_size?Number(l.quantity)*Number(l.pack_size):'—'} units received · line cost {l.quantity&&l.unit_cost?salesMoney(Number(l.quantity)*Number(l.unit_cost)):'not recorded'}</p><button type="button" onClick={()=>{setLines(v=>v.filter((_,j)=>j!==i));setReviewed(false)}}>Remove item</button></div>)}<button type="button" disabled={lines.length>=100} onClick={()=>{setLines(v=>[...v,blank()]);setReviewed(false)}}>Add item</button><label>Notes<textarea maxLength={4000} value={notes} onChange={e=>{setNotes(e.target.value);setReviewed(false)}}/></label><label className="receipt-confirm"><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/><span>I checked the receipt, item names, quantities, pack sizes and costs.</span></label><button type="button" className="primary-button" disabled={!reviewed||!lines.length} onClick={()=>void submit()}>Save incoming inventory slip</button><button type="button" onClick={()=>{if(window.confirm('Close this draft? Unsaved edits will be lost.'))setActive(null)}}>Close draft</button></fieldset>}
 <section className="inventory-card"><h2>Incoming inventory report</h2><p>{manager?'Team receipts':'Your receipts'} · this is a receiving report, not a complete on-hand stock count.</p><div className="receipt-fields"><label>From<input type="date" value={start} disabled={busy} onChange={e=>setStart(e.target.value)}/></label><label>Through<input type="date" value={end} disabled={busy} onChange={e=>setEnd(e.target.value)}/></label></div><button type="button" disabled={busy} onClick={()=>void load().catch(e=>setError(e.message))}>Refresh report</button><button type="button" disabled={!submitted.length||busy} onClick={csv}>Export incoming items CSV</button>{receipts.length>=500&&<p role="alert">Showing the latest 500 receipts. Narrow the date range for a complete report.</p>}<p>{submitted.length} submitted slips · receipt totals {salesMoney(submitted.reduce((n,r)=>n+Number(r.receipt_total??0),0))} ({submitted.filter(r=>r.receipt_total==null).length} totals not recorded)</p>{[...groups.values()].map(g=><p key={g.item+'|'+g.size}><strong>{g.item} · {g.size}</strong> — {g.units} units received · {salesMoney(g.cost)}{g.unknown?' known item cost; some costs missing':' item cost'}</p>)}{!receipts.length&&<p>No receipts in this range.</p>}{receipts.map(r=><details key={r.id}><summary>{r.vendor||'Receipt draft'} · {r.received_date||'Not submitted'} · {r.employee} · {r.status}</summary>{r.invoice_number&&<p>Invoice: {r.invoice_number}</p>}{r.status==='draft'?<button type="button" disabled={busy||r.user_id!==viewer} onClick={()=>{if(!active||window.confirm('Replace the open draft? Unsaved edits will be lost.')){draft(r);setMessage(r.extraction?'Draft resumed. Review the scanned items below.':'Draft resumed. This receipt has no saved scan result yet. Tap Scan receipt or enter items manually.')}}}>Resume draft</button>:<>{r.lines.map((l,i)=><p key={i}>{l.item} · {l.size} · {l.quantity} × {l.pack_size} = {Number(l.quantity)*Number(l.pack_size)} units</p>)}<p>{r.notes}</p></>}<button type="button" disabled={!r.has_file} onClick={()=>void source(r)}>View receipt file</button></details>)}</section></section>
}
