// page-designer-instrumented
import { PageWord, PageOption } from "./PageDesign"
import { ScreenText } from "./ScreenText"
import { useEffect, useState } from 'react'
import { supabase } from '../lib/supabase'
import { submissionLabel } from '../lib/submissionTime'
type Entry={user_id:string;name:string;business_date:string;entry_key:string;description:string;points:number;original_points:number;reason:string|null;updated_at:string|null}
export function PointEntryEditor({location,month,onChanged}:{location:string;month:string;onChanged:()=>void}) {
 const [entries,setEntries]=useState<Entry[]>([]);const [person,setPerson]=useState('');const [selected,setSelected]=useState<Entry|null>(null)
 const [direction,setDirection]=useState('add');const [amount,setAmount]=useState('');const [reason,setReason]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [refresh,setRefresh]=useState(0)
 useEffect(()=>{if(!location)return;let live=true;setBusy(true);setError('');setEntries([]);setSelected(null);void supabase.rpc('points_gm_entries',{p_location_id:location,p_month:month+'-01'}).then(({data,error})=>{if(!live)return;if(error)setError(error.message);else setEntries(data??[]);setBusy(false)});return()=>{live=false}},[location,month,refresh])
 async function save(restore=false){if(!selected)return;const points=(direction==='deduct'?-1:1)*Number(amount);if(!restore && (!amount.trim()||!Number.isInteger(points)||Math.abs(points)>10000)){setError('Enter a whole number from 0 to 10000.');return}if(!reason.trim()){setError('Enter a reason for the edit.');return}setBusy(true);setError('');try{const {error}=await supabase.rpc('points_gm_edit',{p_location_id:location,p_user_id:selected.user_id,p_entry_key:selected.entry_key,p_points:restore?null:points,p_expected:selected.points,p_reason:reason.trim()});if(error)throw error;setSelected(null);setRefresh(v=>v+1);onChanged()}catch(e){setError(String((e as {message?:string}).message??e))}finally{setBusy(false)}}
 const people=[...new Map(entries.map(e=>[e.user_id,e.name])).entries()]
 return <article data-design-block="copy.a5f6086e703b7e2f.1" className="points-card"><h2 data-design-block="copy.7f5b2a9d7519baf6.1"><ScreenText id="PointEntryEditor.e125db0089fa554f">Edit Point Entries · GM Only</ScreenText></h2><p data-design-block="copy.bbcf94b447c5d149.1"><ScreenText id="PointEntryEditor.df72d5e83c0d2ad7">Set the final points for an entry. Changes keep an audit record and update monthly totals.</ScreenText></p>{error&&<p data-design-block="copy.e6f98062d581dc0d.1" role="alert">{error}</p>}<label data-design-block="copy.3b048179043c495e.1"><ScreenText id="PointEntryEditor.bd11e74b6158de3b">Staff member</ScreenText><select value={person} onChange={e=>{setPerson(e.target.value);setSelected(null)}}><PageOption designId="copy.d2290d566a00fbba.1" value=""><ScreenText plain id="PointEntryEditor.5a4578f8f8cfbdae">All staff</ScreenText></PageOption>{people.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label>{busy&&<p data-design-block="copy.ee2a1e88455d11e5.1" role="status"><ScreenText id="PointEntryEditor.ef3d72a1b1d62324">Loading / saving…</ScreenText></p>}
 {selected&&<form data-design-block="copy.7c490aeb109e9ae3.1" onSubmit={e=>{e.preventDefault();void save()}}><h3 data-design-block="copy.5f005a9d919425c2.1">{selected.name}<PageWord id="copy.af2df3ea4396b5e5.1">· </PageWord>{selected.description}</h3><p data-design-block="copy.bbcf94b447c5d149.2"><ScreenText id="PointEntryEditor.03ef2a10c1b156d6">Current: </ScreenText>{selected.points}<ScreenText id="PointEntryEditor.6efe688a9587d889"> · Automatic value: </ScreenText>{selected.original_points}</p><label data-design-block="copy.3b048179043c495e.2"><ScreenText id="PointEntryEditor.c78ae477bc032fd8">Adjustment</ScreenText><select value={direction} onChange={e=>setDirection(e.target.value)}><PageOption designId="copy.6641341c2213829a.1" value="add"><ScreenText plain id="PointEntryEditor.a0ff2c0624fc4bab">Add points</ScreenText></PageOption><PageOption designId="copy.4de4ab8d014fd370.1" value="deduct"><ScreenText plain id="PointEntryEditor.4f3b4e003514961c">Deduct points</ScreenText></PageOption></select></label><label data-design-block="copy.3b048179043c495e.3"><ScreenText id="PointEntryEditor.3a055c2338e55ac2">Points</ScreenText><input required type="text" inputMode="numeric" pattern="[0-9]+" value={amount} onChange={e=>setAmount(e.target.value)} /></label><label data-design-block="copy.3b048179043c495e.4"><ScreenText id="PointEntryEditor.ac37a73a0b87d997">Reason for edit</ScreenText><textarea required maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)} /></label><button data-design-block="copy.ac555539a5c0ddbb.1" disabled={busy}><ScreenText id="PointEntryEditor.69e1ba9436006723">Save entry</ScreenText></button><button data-design-block="copy.c8fb45491777425c.1" type="button" disabled={busy} onClick={()=>void save(true)}><ScreenText id="PointEntryEditor.8e288358f1fe23cc">Restore automatic points</ScreenText></button><button data-design-block="copy.474faf02b41a7d1a.1" type="button" onClick={()=>setSelected(null)}><ScreenText id="PointEntryEditor.ce7ffdd48895e09d">Cancel</ScreenText></button></form>}
 <div data-design-block="copy.3f8bbcea11b4650f.1" className="points-table-wrap"><table className="points-table"><thead><tr><th><ScreenText id="PointEntryEditor.a9578638d07cab74">Date</ScreenText></th><th><ScreenText id="PointEntryEditor.29ae802ee68d2602">Employee</ScreenText></th><th><ScreenText id="PointEntryEditor.c3e7caccd9393ba9">Activity</ScreenText></th><th><ScreenText id="PointEntryEditor.9de7b0a5637966eb">Points</ScreenText></th><th><ScreenText id="PointEntryEditor.ab9cc9ff643e1de0">Edit</ScreenText></th></tr></thead><tbody>{entries.filter(e=>!person||e.user_id===person).map(e=><tr key={e.user_id+e.entry_key}><td>{e.business_date}</td><td>{e.name}</td><td>{e.description}{e.updated_at&&<p data-design-block="copy.bbcf94b447c5d149.3"><ScreenText id="PointEntryEditor.2e25f862da08fd65">Edited </ScreenText>{submissionLabel(e.updated_at)}<PageWord id="copy.af2df3ea4396b5e5.2">· </PageWord>{e.reason}</p>}</td><td>{e.points}</td><td><button data-design-block="copy.1db7fb749b2b5ada.1" type="button" disabled={busy} onClick={()=>{setSelected(e);setDirection(e.points<0?'deduct':'add');setAmount(String(Math.abs(e.points)));setReason('')}}><ScreenText id="PointEntryEditor.62064020755fa14c">Edit points</ScreenText></button></td></tr>)}</tbody></table></div>{!busy&&!entries.length&&<p data-design-block="copy.bbcf94b447c5d149.4"><ScreenText id="PointEntryEditor.63e2c86c00f9c161">No entries this month.</ScreenText></p>}</article>
}
