import { useEffect, useState } from 'react'
import { supabase } from '../lib/supabase'
import { submissionLabel } from '../lib/submissionTime'
type Entry={user_id:string;name:string;business_date:string;entry_key:string;description:string;points:number;original_points:number;reason:string|null;updated_at:string|null}
export function PointEntryEditor({location,month,onChanged}:{location:string;month:string;onChanged:()=>void}) {
 const [entries,setEntries]=useState<Entry[]>([]);const [person,setPerson]=useState('');const [selected,setSelected]=useState<Entry|null>(null)
 const [direction,setDirection]=useState('add');const [amount,setAmount]=useState('');const [reason,setReason]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [refresh,setRefresh]=useState(0)
 useEffect(()=>{if(!location)return;let live=true;setBusy(true);setError('');setEntries([]);setSelected(null);void supabase.rpc('points_gm_entries',{p_location_id:location,p_month:month+'-01'}).then(({data,error})=>{if(!live)return;if(error)setError(error.message);else setEntries(data??[]);setBusy(false)});return()=>{live=false}},[location,month,refresh])
 async function save(restore=false){if(!selected)return;const points=(direction==='deduct'?-1:1)*Number(amount);if(!restore && (!amount.trim()||!Number.isInteger(points)||Math.abs(points)>10000)){setError('Enter a whole number from 0 to 10000.');return}if(!reason.trim()){setError('Enter a reason for the edit.');return}setBusy(true);setError('');try{const {error}=await supabase.rpc('points_gm_edit',{p_location_id:location,p_user_id:selected.user_id,p_entry_key:selected.entry_key,p_points:restore?null:points,p_expected:selected.points,p_reason:reason.trim()});if(error)throw error;setSelected(null);setRefresh(v=>v+1);onChanged()}catch(e){setError(String((e as {message?:string}).message??e))}finally{setBusy(false)}}
 const people=[...new Map(entries.map(e=>[e.user_id,e.name])).entries()]
 return <article className="points-card"><h2>Edit Point Entries · GM Only</h2><p>Set the final points for an entry. Changes keep an audit record and update monthly totals.</p>{error&&<p role="alert">{error}</p>}<label>Staff member<select value={person} onChange={e=>{setPerson(e.target.value);setSelected(null)}}><option value="">All staff</option>{people.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label>{busy&&<p role="status">Loading / saving…</p>}
 {selected&&<form onSubmit={e=>{e.preventDefault();void save()}}><h3>{selected.name} · {selected.description}</h3><p>Current: {selected.points} · Automatic value: {selected.original_points}</p><label>Adjustment<select value={direction} onChange={e=>setDirection(e.target.value)}><option value="add">Add points</option><option value="deduct">Deduct points</option></select></label><label>Points<input required type="text" inputMode="numeric" pattern="[0-9]+" value={amount} onChange={e=>setAmount(e.target.value)} /></label><label>Reason for edit<textarea required maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)} /></label><button disabled={busy}>Save entry</button><button type="button" disabled={busy} onClick={()=>void save(true)}>Restore automatic points</button><button type="button" onClick={()=>setSelected(null)}>Cancel</button></form>}
 <div className="points-table-wrap"><table className="points-table"><thead><tr><th>Date</th><th>Employee</th><th>Activity</th><th>Points</th><th>Edit</th></tr></thead><tbody>{entries.filter(e=>!person||e.user_id===person).map(e=><tr key={e.user_id+e.entry_key}><td>{e.business_date}</td><td>{e.name}</td><td>{e.description}{e.updated_at&&<p>Edited {submissionLabel(e.updated_at)} · {e.reason}</p>}</td><td>{e.points}</td><td><button type="button" disabled={busy} onClick={()=>{setSelected(e);setDirection(e.points<0?'deduct':'add');setAmount(String(Math.abs(e.points)));setReason('')}}>Edit points</button></td></tr>)}</tbody></table></div>{!busy&&!entries.length&&<p>No entries this month.</p>}</article>
}
