import { useEffect, useState } from 'react'
import { supabase } from '../lib/supabase'
import type { SectionEdit } from './PreshiftSections'
import type { MediaAsset } from './PostMedia'
import type { PostColor } from '../lib/postStyle'
import type { FontName } from '../lib/appearance'
export type PostDraft={id:string;version:number;status:string;publish_at:string|null;last_error:string|null;author:string;editable:boolean;content:{title:string;body:string;shift_date:string;pinned:boolean;media:MediaAsset[];presentation:{title:PostColor;text:PostColor;accent:PostColor;titleFont:FontName;textFont:FontName};source:SectionEdit[]|null;sections:SectionEdit[]|null}}
export function PreshiftDrafts({location,refresh,disabled,onEdit,onChange}:{location:string;refresh:number;disabled:boolean;onEdit:(draft:PostDraft)=>void;onChange:()=>void}){
 const [rows,setRows]=useState<PostDraft[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 useEffect(()=>{if(!location)return;let active=true;const load=async()=>{const r=await supabase.rpc('preshift_drafts_list',{p_location_id:location});if(active){if(r.error)setError(r.error.message);else{setRows(r.data);setError('')}}};void load();const timer=setInterval(()=>{if(document.visibilityState==='visible')void load()},15000);return()=>{active=false;clearInterval(timer)}},[location,refresh])
 async function action(d:PostDraft,remove:boolean){if(!window.confirm(remove?'Delete this draft?':'Publish this saved draft now?'))return;setBusy(true);setError('');try{const r=await supabase.rpc(remove?'preshift_draft_delete':'preshift_draft_publish',{p_location_id:location,p_id:d.id,p_version:d.version});if(r.error)throw r.error;onChange()}catch(e){setError(String((e as {message?:string}).message??e))}finally{setBusy(false)}}
 return <details className="feed-card"><summary>Drafts and scheduled posts ({rows.length})</summary>{error&&<p role="alert">{error}</p>}{!rows.length&&!error&&<p>No saved drafts or scheduled posts.</p>}{rows.map(d=><article key={d.id}><h3>{d.content.title||'Untitled draft'}</h3><p>{d.status==='failed'?'Needs review':d.status==='scheduled'?'Scheduled':'Draft'} · {d.author}{d.publish_at&&' · '+new Intl.DateTimeFormat('en-US',{timeZone:'America/Chicago',dateStyle:'medium',timeStyle:'short'}).format(new Date(d.publish_at))+' CT'}</p>{d.last_error&&<p role="alert">Not published: {d.last_error}</p>}{d.editable?<div className="feed-actions"><button type="button" disabled={disabled||busy} onClick={()=>onEdit(d)}>Edit draft</button><button type="button" disabled={disabled||busy} onClick={()=>void action(d,false)}>Publish now</button><button type="button" disabled={disabled||busy} onClick={()=>void action(d,true)}>Delete draft</button></div>:<p>Saved by {d.author}. This author can edit and publish it.</p>}</article>)}</details>
}
