// page-designer-instrumented
import { PageWord, PageInput } from "./PageDesign"
import { ScreenText } from "./ScreenText"
import { useEffect, useState } from 'react'
import { supabase } from '../lib/supabase'
import { PostMedia, type MediaAsset } from './PostMedia'
import { postStyle,postColors,type PostColor } from '../lib/postStyle'
import { appFonts,type FontName } from '../lib/appearance'
type ArchivedPost={id:string;title:string;body:string;shift_date:string;author:string;media?:MediaAsset[];presentation?:{title?:PostColor;text?:PostColor;accent?:PostColor;titleFont?:FontName;textFont?:FontName}}
const dateLabel=(s:string)=>new Date(s+'T12:00:00Z').toLocaleDateString('en-US',{timeZone:'UTC',month:'long',day:'numeric',year:'numeric'})
export function PreshiftArchive({location}:{location:string}){
 const [query,setQuery]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[criteria,setCriteria]=useState({query:'',from:'',to:'',offset:0}),[rows,setRows]=useState<ArchivedPost[]>([]),[total,setTotal]=useState(0),[loading,setLoading]=useState(false),[error,setError]=useState('')
 useEffect(()=>{if(!location)return;let live=true;setLoading(true);setRows([]);setError('');void supabase.rpc('preshift_archive',{p_location_id:location,p_query:criteria.query,p_from:criteria.from||null,p_to:criteria.to||null,p_offset:criteria.offset}).then(r=>{if(!live)return;if(r.error)setError(r.error.message);else{setRows(r.data?.posts??[]);setTotal(r.data?.total??0)}setLoading(false)});return()=>{live=false}},[location,criteria])
 return <section data-design-block="copy.44fb7655a10adc84.1" className="card"><h2 data-design-block="copy.c624398e3cdbb03a.1"><ScreenText id="PreshiftArchive.1cf3c0d3d514cd2c">Past Pre-Shifts</ScreenText></h2><p data-design-block="copy.a5b9593a79e0780e.1"><ScreenText id="PreshiftArchive.9e7f1306b6a47d01">Search words in titles and posts. Past service days move here after the 4 AM rollover.</ScreenText></p><form data-design-block="copy.5c3d6b787209d39b.1" onSubmit={e=>{e.preventDefault();setCriteria({query,from,to,offset:0})}}><div data-design-block="copy.87420c5bbee4dbe9.1" className="form-grid"><label data-design-block="copy.1677dcf32e92d3e9.1"><ScreenText id="PreshiftArchive.a22d3ad37cecef26">Search words</ScreenText><PageInput designId="copy.029c1c53a1c2c76a.1" maxLength={200} value={query} onChange={e=>setQuery(e.target.value)} placeholder="payments, uniform, specials…"/></label><label data-design-block="copy.1677dcf32e92d3e9.2"><ScreenText id="PreshiftArchive.c3c96d1bde2f5b54">From date</ScreenText><input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label data-design-block="copy.1677dcf32e92d3e9.3"><ScreenText id="PreshiftArchive.02a53d5bb2b3426d">Through date</ScreenText><input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></div><button data-design-block="copy.9a053040085618ba.1" disabled={loading}><ScreenText id="PreshiftArchive.3d1ea9c59284d589">Search archive</ScreenText></button><button data-design-block="copy.ce1209c996492f09.1" type="button" disabled={loading} onClick={()=>{setQuery('');setFrom('');setTo('');setCriteria({query:'',from:'',to:'',offset:0})}}><ScreenText id="PreshiftArchive.74edfa7dfa2b3ce7">Clear filters</ScreenText></button></form>{error&&<p data-design-block="copy.4194895f84cf7404.1" role="alert">{error}</p>}{loading?<p data-design-block="copy.9c00b4577ae30dc7.1" role="status"><ScreenText id="PreshiftArchive.7cad8dba38b655f8">Searching…</ScreenText></p>:!error&&<p data-design-block="copy.a5b9593a79e0780e.2">{total}<ScreenText id="PreshiftArchive.e871b6a34ee7d972"> matching pre-shifts</ScreenText></p>}
 {rows.map((p,i)=><div data-design-block="copy.5b4b9cfb137ddc49.1" key={p.id}>{(i===0||p.shift_date.slice(0,7)!==rows[i-1].shift_date.slice(0,7))&&<h3 data-design-block="copy.702a0a0f99a1a4bc.1">{new Date(p.shift_date+'T12:00:00Z').toLocaleDateString('en-US',{timeZone:'UTC',month:'long',year:'numeric'})}</h3>}<details className="feed-card" style={postStyle(p.presentation)}><summary>{dateLabel(p.shift_date)}<PageWord id="copy.fdf33c16c17e0061.1">· </PageWord>{p.title}</summary><h3 data-design-block="copy.8a0941aa943cf74e.1" style={{color:postColors[p.presentation?.title??'brown']?.ink,fontFamily:appFonts[p.presentation?.titleFont??'system']?.css}}>{p.title}</h3><p data-design-block="copy.edd5cca15534373e.1" className="feed-body" style={{color:postColors[p.presentation?.text??'brown']?.ink,fontFamily:appFonts[p.presentation?.textFont??'system']?.css}}>{p.body}</p><PostMedia assets={p.media??[]}/><p data-design-block="copy.a5b9593a79e0780e.3"><ScreenText id="PreshiftArchive.f14b0efb72362272">Posted by </ScreenText>{p.author}</p></details></div>)}
 {!loading&&!error&&total>0&&<div data-design-block="copy.6a3ddff3361837d3.1" className="feed-actions"><button data-design-block="copy.9d33f8ad6742f473.1" disabled={criteria.offset===0} onClick={()=>setCriteria(c=>({...c,offset:Math.max(0,c.offset-25)}))}><ScreenText id="PreshiftArchive.a30ddb94835000dd">Previous</ScreenText></button><span>{criteria.offset+1}<PageWord id="copy.ab63f40c6453fbff.1">–</PageWord>{Math.min(total,criteria.offset+25)}<ScreenText id="PreshiftArchive.6e2d5fa2489c3cb1"> of </ScreenText>{total}</span><button data-design-block="copy.e3f1fb769dfe1de0.1" disabled={criteria.offset+25>=total} onClick={()=>setCriteria(c=>({...c,offset:c.offset+25}))}><ScreenText id="PreshiftArchive.278605cec2eeaa84">Next</ScreenText></button></div>}
 </section>
}
