import { useEffect, useState } from 'react'
import { supabase } from '../lib/supabase'
import { PostMedia, type MediaAsset } from './PostMedia'
import { postStyle,postColors,type PostColor } from '../lib/postStyle'
import { appFonts,type FontName } from '../lib/appearance'
type ArchivedPost={id:string;title:string;body:string;shift_date:string;author:string;media?:MediaAsset[];presentation?:{title?:PostColor;text?:PostColor;accent?:PostColor;titleFont?:FontName;textFont?:FontName}}
const dateLabel=(s:string)=>new Date(s+'T12:00:00Z').toLocaleDateString('en-US',{timeZone:'UTC',month:'long',day:'numeric',year:'numeric'})
export function PreshiftArchive({location}:{location:string}){
 const [query,setQuery]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[criteria,setCriteria]=useState({query:'',from:'',to:'',offset:0}),[rows,setRows]=useState<ArchivedPost[]>([]),[total,setTotal]=useState(0),[loading,setLoading]=useState(false),[error,setError]=useState('')
 useEffect(()=>{if(!location)return;let live=true;setLoading(true);setRows([]);setError('');void supabase.rpc('preshift_archive',{p_location_id:location,p_query:criteria.query,p_from:criteria.from||null,p_to:criteria.to||null,p_offset:criteria.offset}).then(r=>{if(!live)return;if(r.error)setError(r.error.message);else{setRows(r.data?.posts??[]);setTotal(r.data?.total??0)}setLoading(false)});return()=>{live=false}},[location,criteria])
 return <section className="card"><h2>Past Pre-Shifts</h2><p>Search words in titles and posts. Past service days move here after the 4 AM rollover.</p><form onSubmit={e=>{e.preventDefault();setCriteria({query,from,to,offset:0})}}><div className="form-grid"><label>Search words<input maxLength={200} value={query} onChange={e=>setQuery(e.target.value)} placeholder="payments, uniform, specials…"/></label><label>From date<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Through date<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></div><button disabled={loading}>Search archive</button><button type="button" disabled={loading} onClick={()=>{setQuery('');setFrom('');setTo('');setCriteria({query:'',from:'',to:'',offset:0})}}>Clear filters</button></form>{error&&<p role="alert">{error}</p>}{loading?<p role="status">Searching…</p>:!error&&<p>{total} matching pre-shifts</p>}
 {rows.map((p,i)=><div key={p.id}>{(i===0||p.shift_date.slice(0,7)!==rows[i-1].shift_date.slice(0,7))&&<h3>{new Date(p.shift_date+'T12:00:00Z').toLocaleDateString('en-US',{timeZone:'UTC',month:'long',year:'numeric'})}</h3>}<details className="feed-card" style={postStyle(p.presentation)}><summary>{dateLabel(p.shift_date)} · {p.title}</summary><h3 style={{color:postColors[p.presentation?.title??'brown']?.ink,fontFamily:appFonts[p.presentation?.titleFont??'system']?.css}}>{p.title}</h3><p className="feed-body" style={{color:postColors[p.presentation?.text??'brown']?.ink,fontFamily:appFonts[p.presentation?.textFont??'system']?.css}}>{p.body}</p><PostMedia assets={p.media??[]}/><p>Posted by {p.author}</p></details></div>)}
 {!loading&&!error&&total>0&&<div className="feed-actions"><button disabled={criteria.offset===0} onClick={()=>setCriteria(c=>({...c,offset:Math.max(0,c.offset-25)}))}>Previous</button><span>{criteria.offset+1}–{Math.min(total,criteria.offset+25)} of {total}</span><button disabled={criteria.offset+25>=total} onClick={()=>setCriteria(c=>({...c,offset:c.offset+25}))}>Next</button></div>}
 </section>
}
