import { SectionEmployeePicker } from './SectionEmployeePicker'
import { useEffect, useRef, useState } from 'react'
import { supabase } from '../lib/supabase'
import { sectionTime } from './MySections'
export type SectionEdit={id:string;name:string;employee_id:string|null;guest_name:string|null;table_ids:string[];kind:string;starts_at:string|null;ends_at:string|null;shift_id:string|null;version:number|null;published_at:string|null}
export type SectionChanges={source:SectionEdit[];rows:SectionEdit[]}
type Choice={id:string;name:string}
export function PreshiftSections({location,date,disabled,onChange,onLoading}:{location:string;date:string;disabled:boolean;onChange:(value:SectionChanges|null)=>void;onLoading:(busy:boolean)=>void}){
 const [source,setSource]=useState<SectionEdit[]|null>(null),[rows,setRows]=useState<SectionEdit[]>([]),[employees,setEmployees]=useState<Choice[]>([]),[tables,setTables]=useState<Choice[]>([])
 const request=useRef(0)
 const [error,setError]=useState(''),[busy,setBusy]=useState(false)
 useEffect(()=>{setSource(null);setRows([]);setError('');setBusy(false);request.current++;onLoading(false);onChange(null);return()=>{request.current++}},[location,date])
 function edit(id:string,values:Partial<SectionEdit>){const next=rows.map(r=>r.id===id?{...r,...values}:r);setRows(next);if(source)onChange({source,rows:next})}
 async function pull(){const token=++request.current;setBusy(true);onLoading(true);setError('');try{const r=await supabase.rpc('preshift_sections_edit',{p_location_id:location,p_date:date});if(token!==request.current)return;if(r.error)throw r.error;const data=r.data as {rows:SectionEdit[];employees:Choice[];tables:Choice[]};if(!data.rows.length)throw Error('No sections for this date. Create assignments on Floor, then pull them here.');setSource(data.rows);setRows(data.rows.map(s=>({...s,table_ids:[...s.table_ids]})));setEmployees(data.employees);setTables(data.tables);onChange({source:data.rows,rows:data.rows})}catch(e){if(token===request.current)setError(String((e as {message?:string}).message??e))}finally{if(token===request.current){setBusy(false);onLoading(false)}}}
 return <fieldset disabled={disabled||busy}><legend>Sections</legend><p>Pull assignments from Floor, then edit the server, name or tables. Publishing this post saves these assignments to Floor and publishes any included timed drafts. Later Floor changes keep this post as a record.</p><button type="button" onClick={()=>void pull()}>{busy?'Loading…':source?'Reload from Floor':'Pull sections from Floor'}</button>{error&&<p role="alert">{error}</p>}
 {rows.map(row=><fieldset key={row.id}><legend>{row.name}</legend><p>{row.starts_at&&row.ends_at?sectionTime(row.starts_at)+' – '+sectionTime(row.ends_at)+' CT':'Regular shift · timed sections take priority during their window'}{row.kind==='plan'&&!row.published_at?' · Draft':''}</p><label>Section name<input required maxLength={100} value={row.name} onChange={e=>edit(row.id,{name:e.target.value})}/></label><SectionEmployeePicker employees={employees} employeeId={row.employee_id} guestName={row.guest_name??''} onChange={(id,name)=>edit(row.id,{employee_id:id,guest_name:id===null?name:null})}/><details><summary>Tables: {row.table_ids.map(id=>tables.find(t=>t.id===id)?.name??'Unavailable').join(', ')||'Choose tables'}</summary><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(100px,1fr))',gap:8}}>{tables.map(t=><label className="feed-check" key={t.id}><input type="checkbox" checked={row.table_ids.includes(t.id)} onChange={e=>edit(row.id,{table_ids:(e.target.checked?[...row.table_ids,t.id]:row.table_ids.filter(id=>id!==t.id)).sort()})}/>{t.name}</label>)}</div></details></fieldset>)}
 {source&&<p role="status">Sections will save to Floor together with this post. To add sections or change their times, use Floor and reload here.</p>}</fieldset>
}
