// page-designer-instrumented
import { PageWord } from "./PageDesign"
import { useEffect, useState } from 'react'
import { supabase } from '../lib/supabase'
import type { SectionEdit } from './PreshiftSections'
import type { MediaAsset } from './PostMedia'
import type { PostColor } from '../lib/postStyle'
import type { FontName } from '../lib/appearance'
export type PostDraft={id:string;version:number;status:string;publish_at:string|null;last_error:string|null;author:string;editable:boolean;content:{title:string;body:string;shift_date:string;pinned:boolean;media:MediaAsset[];presentation:{title:PostColor;text:PostColor;accent:PostColor;titleFont:FontName;textFont:FontName};source:SectionEdit[]|null;sections:SectionEdit[]|null}}
export function PreshiftDrafts({location,refresh,disabled,onEdit,onChange}:{location:string;refresh:number;disabled:boolean;onEdit:(draft:PostDraft)=>void;onChange:()=>void}){
 const [rows,setRows]=useState<PostDraft[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 useEffect(()=>{if(!location)return;let active=true;const load=async()=>{const r=await supabase.rpc('preshift_drafts_list',{p_location_id:location});if(active){if(r.error)setError(r.error.message);else{setRows(r.data);setError('')}}};void load();const timer=setInterval(()=>{if(document.visibilityState==='visible')void load()},15000);return()=>{active=false;clearInterval(timer)}},[location,refresh])
 async function action(d:PostDraft,remove:boolean){if(!window.confirm(remove?'Delete this draft?':'Publish this saved draft now?'))return;setBusy(true);setError('');try{const r=await supabase.rpc(remove?'preshift_draft_delete':'preshift_draft_publish',{p_location_id:location,p_id:d.id,p_version:d.version});if(r.error)throw r.error;onChange()}catch(e){setError(String((e as {message?:string}).message??e))}finally{setBusy(false)}}
 return <details className="feed-card"><summary><PageWord id="copy.a47872f63d0e0145.1">Drafts and scheduled posts (</PageWord>{rows.length}<PageWord id="copy.e2ae35cad8a5b2cd.1">)</PageWord></summary>{error&&<p data-design-block="copy.6e070cfdf9507389.1" role="alert">{error}</p>}{!rows.length&&!error&&<p data-design-block="copy.9011da5108dbe227.1"><PageWord id="copy.ad32faab22b50a22.1">No saved drafts or scheduled posts.</PageWord></p>}{rows.map(d=><article data-design-block="copy.e6195f1589f23924.1" key={d.id}><h3 data-design-block="copy.be1d642c3f855567.1">{d.content.title||'Untitled draft'}</h3><p data-design-block="copy.9011da5108dbe227.2">{d.status==='failed'?<PageWord id="copy.93ff233a9815d3e1.1">{"Needs review"}</PageWord>:d.status==='scheduled'?<PageWord id="copy.1b032ddfd1dc2995.1">{"Scheduled"}</PageWord>:<PageWord id="copy.20d9f5de8058265d.1">{"Draft"}</PageWord>}<PageWord id="copy.7a979e04a205fc52.1">· </PageWord>{d.author}{d.publish_at&&' · '+new Intl.DateTimeFormat('en-US',{timeZone:'America/Chicago',dateStyle:'medium',timeStyle:'short'}).format(new Date(d.publish_at))+' CT'}</p>{d.last_error&&<p data-design-block="copy.6e070cfdf9507389.2" role="alert"><PageWord id="copy.fe82681be1aed759.1">Not published: </PageWord>{d.last_error}</p>}{d.editable?<div data-design-block="copy.354ca0f0d23e877a.1" className="feed-actions"><button data-design-block="copy.f5f1695eb9df0b09.1" type="button" disabled={disabled||busy} onClick={()=>onEdit(d)}><PageWord id="copy.97daec6f7b6c11bc.1">Edit draft</PageWord></button><button data-design-block="copy.f707476f84fbd189.1" type="button" disabled={disabled||busy} onClick={()=>void action(d,false)}><PageWord id="copy.0f7b81ff8f655dc6.1">Publish now</PageWord></button><button data-design-block="copy.a2a72554beaee77a.1" type="button" disabled={disabled||busy} onClick={()=>void action(d,true)}><PageWord id="copy.91362eb293d503ec.1">Delete draft</PageWord></button></div>:<p data-design-block="copy.9011da5108dbe227.3"><PageWord id="copy.77cada544362ec69.1">Saved by </PageWord>{d.author}<PageWord id="copy.f3baca27d3714db7.1">. This author can edit and publish it.</PageWord></p>}</article>)}</details>
}
