// page-designer-instrumented
import { PageWord } from "./PageDesign"
import { ScreenText } from "./ScreenText"
import { SectionEmployeePicker } from './SectionEmployeePicker'
import { useEffect, useRef, useState } from 'react'
import { supabase } from '../lib/supabase'
import { sectionTime } from './MySections'
export type SectionEdit={id:string;name:string;employee_id:string|null;guest_name:string|null;table_ids:string[];kind:string;starts_at:string|null;ends_at:string|null;shift_id:string|null;version:number|null;published_at:string|null}
export type SectionChanges={source:SectionEdit[];rows:SectionEdit[]}
type Choice={id:string;name:string}
export function PreshiftSections({initial,location,date,disabled,onChange,onLoading}:{initial?:SectionChanges|null;location:string;date:string;disabled:boolean;onChange:(value:SectionChanges|null)=>void;onLoading:(busy:boolean)=>void}){
 const [source,setSource]=useState<SectionEdit[]|null>(null),[rows,setRows]=useState<SectionEdit[]>([]),[employees,setEmployees]=useState<Choice[]>([]),[tables,setTables]=useState<Choice[]>([])
 const request=useRef(0);const initialDate=useRef(date)
 const [error,setError]=useState(''),[busy,setBusy]=useState(false)
 useEffect(()=>{if(initial&&initialDate.current===date){const token=++request.current;setError('');setBusy(false);onLoading(false);setSource(initial.source);setRows(initial.rows);onChange(initial);void supabase.rpc('preshift_sections_edit',{p_location_id:location,p_date:date}).then(r=>{if(token!==request.current)return;if(r.error){setError(r.error.message);return}setEmployees(r.data.employees);setTables(r.data.tables)});return()=>{request.current++}}setSource(null);setRows([]);setError('');setBusy(false);request.current++;onLoading(false);onChange(null);return()=>{request.current++}},[location,date])
 function edit(id:string,values:Partial<SectionEdit>){const next=rows.map(r=>r.id===id?{...r,...values}:r);setRows(next);if(source)onChange({source,rows:next})}
 async function pull(){const token=++request.current;setBusy(true);onLoading(true);setError('');try{const r=await supabase.rpc('preshift_sections_edit',{p_location_id:location,p_date:date});if(token!==request.current)return;if(r.error)throw r.error;const data=r.data as {rows:SectionEdit[];employees:Choice[];tables:Choice[]};if(!data.rows.length)throw Error('No sections for this date. Create assignments on Floor, then pull them here.');setSource(data.rows);setRows(data.rows.map(s=>({...s,table_ids:[...s.table_ids]})));setEmployees(data.employees);setTables(data.tables);onChange({source:data.rows,rows:data.rows})}catch(e){if(token===request.current)setError(String((e as {message?:string}).message??e))}finally{if(token===request.current){setBusy(false);onLoading(false)}}}
 return <fieldset data-design-block="copy.18e843415aa27aea.1" disabled={disabled||busy}><legend><ScreenText id="PreshiftSections.2562281ceb7c4693">Sections</ScreenText></legend><p data-design-block="copy.a57ad2f8a4b008b4.1"><ScreenText id="PreshiftSections.6ea0c1becc1f6c75">Pull assignments from Floor, then edit the server, name or tables. Publishing this post saves these assignments to Floor and publishes any included timed drafts. Later Floor changes keep this post as a record.</ScreenText></p><button data-design-block="copy.a5df1eee6cbea026.1" type="button" onClick={()=>void pull()}>{busy?<PageWord id="copy.73426ceaa6bfa4b5.1">{"Loading…"}</PageWord>:source?<PageWord id="copy.066ab85f1d3f8983.1">{"Reload from Floor"}</PageWord>:<PageWord id="copy.5e670b2c73752c4f.1">{"Pull sections from Floor"}</PageWord>}</button>{error&&<p data-design-block="copy.b13dbee0cb14ae45.1" role="alert">{error}</p>}
 {rows.map(row=><fieldset data-design-block="copy.84728b0bf80fc3fc.1" key={row.id}><legend>{row.name}</legend><p data-design-block="copy.a57ad2f8a4b008b4.2">{row.starts_at&&row.ends_at?sectionTime(row.starts_at)+' – '+sectionTime(row.ends_at)+' CT':<PageWord id="copy.8ce1997ddae15edf.1">{"Regular shift · timed sections take priority during their window"}</PageWord>}{row.kind==='plan'&&!row.published_at?<PageWord id="copy.e762e66b7eae02d1.1">{" · Draft"}</PageWord>:<PageWord id="copy.d8f3c12d84a1d929.1">{""}</PageWord>}</p><label data-design-block="copy.6a68201b99ec2ead.1"><ScreenText id="PreshiftSections.fda003be2ac13b87">Section name</ScreenText><input required maxLength={100} value={row.name} onChange={e=>edit(row.id,{name:e.target.value})}/></label><SectionEmployeePicker employees={employees} employeeId={row.employee_id} guestName={row.guest_name??''} onChange={(id,name)=>edit(row.id,{employee_id:id,guest_name:id===null?name:null})}/><details><summary><ScreenText id="PreshiftSections.fd606679b46c8bc6">Tables: </ScreenText>{row.table_ids.map(id=>tables.find(t=>t.id===id)?.name??'Unavailable').join(', ')||'Choose tables'}</summary><div data-design-block="copy.5e8f140dbfc4886c.1" style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(100px,1fr))',gap:8}}>{tables.map(t=><label data-design-block="copy.cb05fa0c0721ca86.1" className="feed-check" key={t.id}><input type="checkbox" checked={row.table_ids.includes(t.id)} onChange={e=>edit(row.id,{table_ids:(e.target.checked?[...row.table_ids,t.id]:row.table_ids.filter(id=>id!==t.id)).sort()})}/>{t.name}</label>)}</div></details></fieldset>)}
 {source&&<p data-design-block="copy.fa59965700714982.1" role="status"><ScreenText id="PreshiftSections.46b3ee20f5642575">Sections will save to Floor together with this post. To add sections or change their times, use Floor and reload here.</ScreenText></p>}</fieldset>
}
