import { ScreenText } from "./ScreenText"
import { PresetEditorModal } from './PresetEditorModal'
import { SalesTargetPreview } from './SalesTargetPreview'
import { useEffect, useState } from 'react'
import { supabase } from '../lib/supabase'
type Preset={id:string;title:string;category:string;weekday:number|null;body:string;version:number}
type Chunk={key:string;title:string;body:string}
const days=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday']
const categories={hours:'Daily hours',specials:'Daily specials',service:'Service standards',sales:'Sales targets',uniform:'Uniform checks'}
const weekday=(date:string)=>{const n=new Date(date+'T12:00:00Z').getUTCDay();return Number.isFinite(n)?n:0}
export function PreshiftPresetBuilder({location,date,disabled,onInsert}:{location:string;date:string;disabled:boolean;onInsert:(text:string)=>void}){
 const [presets,setPresets]=useState<Preset[]>([]),[chunks,setChunks]=useState<Chunk[]>([]),[day,setDay]=useState(()=>weekday(date)),[category,setCategory]=useState('all'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[edit,setEdit]=useState<Preset|null>(null),[showEdit,setShowEdit]=useState(false)
 const [presetTitle,setPresetTitle]=useState(''),[presetBody,setPresetBody]=useState(''),[presetCategory,setPresetCategory]=useState('service'),[presetDay,setPresetDay]=useState('')
 useEffect(()=>{setDay(weekday(date));setChunks(v=>v.filter(c=>!c.key.startsWith('automatic-sales:')));setShowEdit(false)},[date])
 async function load(){const r=await supabase.rpc('preshift_presets',{p_location_id:location});if(r.error)throw r.error;setPresets(r.data??[])}
 useEffect(()=>{let active=true;setChunks([]);setPresets([]);setError('');void supabase.rpc('preshift_presets',{p_location_id:location}).then(r=>{if(!active)return;if(r.error)setError(r.error.message);else setPresets(r.data??[])});return()=>{active=false}},[location])
 function add(p:Preset){if(chunks.some(c=>c.key===p.id))return;setChunks(v=>[...v,{key:p.id,title:p.title,body:p.body}])}
 function move(index:number,change:number){setChunks(v=>{const next=[...v],target=index+change;if(target<0||target>=next.length)return v;[next[index],next[target]]=[next[target],next[index]];return next})}
 function editor(p:Preset|null){setEdit(p);setShowEdit(true);setPresetTitle(p?.title??'');setPresetBody(p?.body??'');setPresetCategory(p?.category??'service');setPresetDay(p?.weekday==null?'':String(p.weekday));setError('')}
 async function save(){setBusy(true);setError('');try{const r=await supabase.rpc('preshift_preset_save',{p_location_id:location,p_id:edit?.id??null,p_version:edit?.version??null,p_title:presetTitle,p_category:presetCategory,p_weekday:presetDay===''?null:Number(presetDay),p_body:presetBody});if(r.error)throw r.error;await load();setShowEdit(false)}catch(e){setError(String((e as {message?:string}).message??e))}finally{setBusy(false)}}
 async function remove(p:Preset){if(!window.confirm('Remove preset "'+p.title+'"? Published posts and already-added sections stay unchanged.'))return;setBusy(true);setError('');try{const r=await supabase.rpc('preshift_preset_remove',{p_location_id:location,p_id:p.id,p_version:p.version});if(r.error)throw r.error;await load()}catch(e){setError(String((e as {message?:string}).message??e))}finally{setBusy(false)}}
 const locked=disabled||busy
 return <div className="preset-builder"><h3><ScreenText id="PreshiftPresetBuilder.02bcc5390bfc72de">Build with preset sections</ScreenText></h3><p><ScreenText id="PreshiftPresetBuilder.35775100d0250ad2">Pick the pieces you need, edit their wording for this shift, then insert them into your post. Daily hours and specials are starter drafts—confirm today’s details before publishing.</ScreenText></p>
 {error&&!showEdit&&<p role="alert">{error}</p>}
 <details open><summary><ScreenText id="PreshiftPresetBuilder.0aa6e5e7de2fdbff">Preset library</ScreenText></summary><div className="post-color-tools"><label><ScreenText id="PreshiftPresetBuilder.efcda099179f0882">Day</ScreenText><select disabled={locked} value={day} onChange={e=>setDay(Number(e.target.value))}>{days.map((d,i)=><option key={d} value={i}>{d}</option>)}</select></label><label><ScreenText id="PreshiftPresetBuilder.73461b2a185415e5">Category</ScreenText><select disabled={locked} value={category} onChange={e=>setCategory(e.target.value)}><option value="all"><ScreenText id="PreshiftPresetBuilder.fa2dbdfa6b1d9daf">All sections</ScreenText></option>{Object.entries(categories).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label></div>
 {(category==='all'||category==='sales')&&<SalesTargetPreview location={location} date={date} disabled={locked} onAdd={text=>setChunks(v=>[...v.filter(c=>!c.key.startsWith('automatic-sales:')),{key:'automatic-sales:'+date,title:'Sales targets',body:text}])}/>}
 <div style={{display:'grid',gap:8}}>{presets.filter(p=>p.category!=='sales'&&(p.weekday===null||p.weekday===day)&&(category==='all'||p.category===category)).map(p=><div className="feed-card" key={p.id}><strong>{p.title}</strong><details><summary><ScreenText id="PreshiftPresetBuilder.043881a4f90ea4c9">Read preset</ScreenText></summary><p className="feed-body">{p.body}</p></details><div className="feed-actions"><button type="button" disabled={locked||chunks.some(c=>c.key===p.id)} onClick={()=>add(p)}>{chunks.some(c=>c.key===p.id)?'Added':'Add'}</button><button type="button" disabled={locked} onClick={()=>editor(p)}><ScreenText id="PreshiftPresetBuilder.d3907b776d9693a3">Edit preset</ScreenText></button><button type="button" disabled={locked} onClick={()=>void remove(p)}><ScreenText id="PreshiftPresetBuilder.835b90f5d48bf61d">Remove preset</ScreenText></button></div></div>)}</div><button type="button" disabled={locked} onClick={()=>editor(null)}><ScreenText id="PreshiftPresetBuilder.78d7c7fa8f8de7be">Create a preset</ScreenText></button></details>
 {showEdit&&<PresetEditorModal busy={locked} onClose={()=>setShowEdit(false)}><fieldset disabled={locked}><legend id="preset-editor-title">{edit?'Edit reusable preset':'New reusable preset'}</legend>{error&&<p role="alert">{error}</p>}<label><ScreenText id="PreshiftPresetBuilder.a6197e7a25dc4edc">Preset title</ScreenText><input maxLength={100} value={presetTitle} onChange={e=>setPresetTitle(e.target.value)}/></label><label><ScreenText id="PreshiftPresetBuilder.6d79811f584afd71">Category</ScreenText><select value={presetCategory} onChange={e=>setPresetCategory(e.target.value)}>{Object.entries(categories).filter(([key])=>key!=='sales').map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label><ScreenText id="PreshiftPresetBuilder.cb40f387e240177e">Day</ScreenText><select value={presetDay} onChange={e=>setPresetDay(e.target.value)}><option value=""><ScreenText id="PreshiftPresetBuilder.f4c3413f600aa52e">Any day</ScreenText></option>{days.map((d,i)=><option key={d} value={i}>{d}</option>)}</select></label><label><ScreenText id="PreshiftPresetBuilder.05a047b9c63f7395">Reusable wording</ScreenText><textarea rows={5} maxLength={4000} value={presetBody} onChange={e=>setPresetBody(e.target.value)}/></label><p><ScreenText id="PreshiftPresetBuilder.987872b88d50468b">Saving changes the library preset. Existing posts and sections already added to this draft keep their wording.</ScreenText></p><button type="button" disabled={locked||!presetTitle.trim()||!presetBody.trim()} onClick={()=>void save()}><ScreenText id="PreshiftPresetBuilder.5c4326db6fafcb6d">Save preset</ScreenText></button><button type="button" disabled={locked} onClick={()=>setShowEdit(false)}><ScreenText id="PreshiftPresetBuilder.b7ecf032a48fc552">Cancel preset edit</ScreenText></button></fieldset></PresetEditorModal>}
 {chunks.length>0&&<div><h3><ScreenText id="PreshiftPresetBuilder.9fad76583580b96a">Sections for this post</ScreenText></h3>{chunks.map((c,i)=><div className="feed-card" key={c.key}><label><ScreenText id="PreshiftPresetBuilder.1392085b0f85676f">Section heading</ScreenText><input disabled={locked} maxLength={100} value={c.title} onChange={e=>setChunks(v=>v.map(x=>x.key===c.key?{...x,title:e.target.value}:x))}/></label><label><ScreenText id="PreshiftPresetBuilder.c0a05b6c1249b6a2">Wording for this shift</ScreenText><textarea disabled={locked} maxLength={4000} rows={4} value={c.body} onChange={e=>setChunks(v=>v.map(x=>x.key===c.key?{...x,body:e.target.value}:x))}/></label><div className="feed-actions"><button type="button" disabled={locked||i===0} onClick={()=>move(i,-1)}><ScreenText id="PreshiftPresetBuilder.b8706da4ea148687">Move up</ScreenText></button><button type="button" disabled={locked||i===chunks.length-1} onClick={()=>move(i,1)}><ScreenText id="PreshiftPresetBuilder.6facfe40141a8165">Move down</ScreenText></button><button type="button" disabled={locked} onClick={()=>setChunks(v=>v.filter(x=>x.key!==c.key))}><ScreenText id="PreshiftPresetBuilder.ffe01b9208869838">Remove</ScreenText></button></div></div>)}<button type="button" className="primary-button" disabled={locked||chunks.some(c=>!c.body.trim())} onClick={()=>{try{onInsert(chunks.map(c=>[c.title.trim(),c.body.trim()].filter(Boolean).join('\n')).join('\n\n'));setChunks([]);setError('')}catch(e){setError(String((e as Error).message))}}}><ScreenText id="PreshiftPresetBuilder.5d5af424be5bdeb0">Add to post</ScreenText></button></div>}
 </div>
}
