import { ScreenText } from "./ScreenText"
import { useEffect, useState } from 'react'
import { supabase } from '../lib/supabase'
import type { Question } from '../pages/QuizzesPage'
import { quizError } from '../pages/QuizzesPage'
import './QuizQuestionBank.css'
import '../pages/Appearance.css'
type Entry={id:string;source:string;quiz_date:string|null;review:boolean;question:Question}
const normalize=(s:string)=>s.trim().toLocaleLowerCase()
const dateLabel=(s:string)=>s==='Undated'?'Older questions without a date':new Intl.DateTimeFormat('en-US',{timeZone:'UTC',month:'long',day:'numeric',year:'numeric'}).format(new Date(s+'T12:00:00Z'))
export function QuizQuestionBank({location,disabled,questions,onAdd,open,onOpenChange}:{location:string;disabled:boolean;questions:Question[];onAdd:(questions:Question[])=>void;open?:boolean;onOpenChange?:(open:boolean)=>void}) {
 const [expanded,setExpanded]=useState(false)
 const [bank,setBank]=useState<Entry[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[search,setSearch]=useState(''),[category,setCategory]=useState('All'),[day,setDay]=useState('All'),[selected,setSelected]=useState<string[]>([]),[reviewed,setReviewed]=useState(false),[message,setMessage]=useState(''),[refresh,setRefresh]=useState(0)
 const [importDate,setImportDate]=useState(''),[importTitle,setImportTitle]=useState('Pre-Shift Quiz'),[importing,setImporting]=useState(false),[importQuestions,setImportQuestions]=useState<Question[]>([])
 useEffect(()=>{if(!location)return;let live=true;setBusy(true);setError('');setSelected([]);setReviewed(false);void(async()=>{try{const r=await supabase.rpc('quiz_question_bank_by_day',{p_location_id:location});if(r.error)throw r.error;if(live)setBank(r.data??[])}catch(e){if(live)setError(quizError(e))}finally{if(live)setBusy(false)}})();return()=>{live=false}},[location,refresh])
 const existing=new Set(questions.map(q=>normalize(q.prompt))),seen=new Set<string>()
 const chosen=bank.filter(e=>{const key=normalize(e.question.prompt);if(!selected.includes(e.id)||existing.has(key)||seen.has(key))return false;seen.add(key);return true})
 const requiresReview=chosen.some(e=>e.review)
 const filtered=bank.filter(e=>(category==='All'||e.question.category===category)&&(day==='All'||(e.quiz_date??'Undated')===day)&&normalize(e.question.prompt+' '+e.question.category+' '+e.source).includes(normalize(search)))
 const days=[...new Set(bank.map(e=>e.quiz_date??'Undated'))].sort((a,b)=>a==='Undated'?1:b==='Undated'?-1:b.localeCompare(a))
 function add(){if(!chosen.length||chosen.length+questions.length>50||(requiresReview&&!reviewed))return;onAdd(chosen.map(e=>({...e.question,options:[...e.question.options]})));setMessage(`${chosen.length} questions added. Edit them below before publishing.`);setSelected([]);setReviewed(false)}
 async function importFile(file:File){try{if(file.size>1000000)throw new Error('Choose a JSON file smaller than 1 MB.');const parsed=JSON.parse(await file.text());const list=Array.isArray(parsed)?parsed:parsed.questions;if(!Array.isArray(list)||!list.length||list.length>50)throw new Error('The file needs 1 to 50 questions.');const prepared=list.map(q=>({...q,category:q.category??'Pre-Shift',explanation:q.explanation??''}));if(prepared.some(q=>typeof q.prompt!=='string'||!Array.isArray(q.options)||!Number.isInteger(q.correct)))throw new Error('Each question needs prompt, options and a zero-based correct answer.');setImportQuestions(prepared);if(!Array.isArray(parsed)){if(typeof parsed.quiz_date==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(parsed.quiz_date))setImportDate(parsed.quiz_date);if(typeof parsed.title==='string')setImportTitle(parsed.title.slice(0,200))}setError('')}catch(e){setImportQuestions([]);setError(quizError(e))}}
 async function importSet(){setImporting(true);try{const r=await supabase.rpc('quiz_bank_import',{p_location_id:location,p_date:importDate,p_title:importTitle,p_questions:importQuestions});if(r.error)throw r.error;setImportQuestions([]);setMessage('Questions imported under '+dateLabel(importDate)+'.');setRefresh(v=>v+1)}catch(e){setError(quizError(e))}finally{setImporting(false)}}
 return <details className="quiz-bank" open={open??expanded} onToggle={e=>{const next=e.currentTarget.open;setExpanded(next);if(next!==open)onOpenChange?.(next)}}><summary><strong><ScreenText id="QuizQuestionBank.c2266270f6b43e98">＋ Question Bank (</ScreenText>{bank.length}<ScreenText id="QuizQuestionBank.ea96d5e5a2d9fd42">) — by day</ScreenText></strong></summary><p><ScreenText id="QuizQuestionBank.89a1438d47709fa4">Every quiz saved in this app appears under its quiz date. Select one question or the whole day’s set. Copies can be edited before publishing.</ScreenText></p>{busy&&<p role="status"><ScreenText id="QuizQuestionBank.1f9d1106a75d5c62">Loading question bank…</ScreenText></p>}{error&&<p role="alert">{error}</p>}
 <fieldset disabled={disabled||busy||importing||!location} className="quiz-bank-controls"><label><ScreenText id="QuizQuestionBank.eea41b687fbeb818">Search</ScreenText><input type="search" value={search} onChange={e=>setSearch(e.target.value)} /></label><div className="quiz-bank-filters"><label><ScreenText id="QuizQuestionBank.a6306e2dee3beaf3">Quiz day</ScreenText><select value={day} onChange={e=>setDay(e.target.value)}><option><ScreenText id="QuizQuestionBank.75f7596a7a9f4104">All</ScreenText></option>{days.map(d=><option key={d} value={d}>{dateLabel(d)}</option>)}</select></label><label><ScreenText id="QuizQuestionBank.6ebee72f93250359">Category</ScreenText><select value={category} onChange={e=>setCategory(e.target.value)}><option><ScreenText id="QuizQuestionBank.50e544df8c5e981f">All</ScreenText></option>{[...new Set(bank.map(e=>e.question.category))].sort().map(c=><option key={c}>{c}</option>)}</select></label></div>
 <div className="quiz-bank-add-bar"><button type="button" disabled={!chosen.length||chosen.length+questions.length>50||(requiresReview&&!reviewed)} onClick={add}><ScreenText id="QuizQuestionBank.d8778ebf21a3f41d">Add selected (</ScreenText>{chosen.length})</button></div>
 {days.filter(d=>filtered.some(e=>(e.quiz_date??'Undated')===d)).map(d=>{const entries=filtered.filter(e=>(e.quiz_date??'Undated')===d);return <details className="quiz-day-group" key={d}><summary>{dateLabel(d)} · {entries.length}<ScreenText id="QuizQuestionBank.d10e458258825abc"> questions</ScreenText></summary><button type="button" onClick={()=>{setSelected(v=>[...new Set([...v,...entries.filter(e=>!existing.has(normalize(e.question.prompt))).map(e=>e.id)])]);setReviewed(false)}}><ScreenText id="QuizQuestionBank.d4f12e433e8289ab">Select this day’s questions</ScreenText></button>{entries.map(e=>{const added=existing.has(normalize(e.question.prompt));return <article className="quiz-bank-item" key={e.id}><label className="quiz-choice"><input type="checkbox" checked={selected.includes(e.id)&&!added} disabled={added} onChange={()=>{setSelected(v=>v.includes(e.id)?v.filter(id=>id!==e.id):[...v,e.id]);setReviewed(false)}} /><span>{e.question.prompt}{added?' — Already added':''}</span></label><p className="muted">{e.question.category} · {e.source}</p><details><summary><ScreenText id="QuizQuestionBank.2c33d13a364e39b8">Preview choices and answer</ScreenText></summary><ul>{e.question.options.map((o,i)=><li key={i}>{o}{i===e.question.correct?' — Correct':''}</li>)}</ul>{e.question.explanation&&<p>{e.question.explanation}</p>}</details></article>})}</details>})}
 {!busy&&!filtered.length&&<p><ScreenText id="QuizQuestionBank.4206cfb972af9a6e">No matching questions.</ScreenText></p>}{requiresReview&&<label className="quiz-choice"><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)} /><span><ScreenText id="QuizQuestionBank.29432acab14e0dec">I will check these older recipes, prices and policies before publishing.</ScreenText></span></label>}{chosen.length+questions.length>50&&<p role="alert"><ScreenText id="QuizQuestionBank.b5e8b71e76b8daff">Choose fewer questions. The limit is 50 per quiz.</ScreenText></p>}
 <details><summary><ScreenText id="QuizQuestionBank.48aad5738d9c5b36">Import an older quiz from a JSON file</ScreenText></summary><p><ScreenText id="QuizQuestionBank.3721b90fb7c0f755">Use the original questions and correct answers. Importing the same date and title replaces that imported set.</ScreenText></p><label><ScreenText id="QuizQuestionBank.6e2b36f6f5356c07">Quiz date</ScreenText><input type="date" value={importDate} onChange={e=>setImportDate(e.target.value)} /></label><label><ScreenText id="QuizQuestionBank.7f320b8eed13f1bd">Quiz title</ScreenText><input value={importTitle} maxLength={200} onChange={e=>setImportTitle(e.target.value)} /></label><label><ScreenText id="QuizQuestionBank.b9b7485d72361ade">Questions file</ScreenText><input type="file" accept=".json,application/json" onChange={e=>{if(e.target.files?.[0])void importFile(e.target.files[0]);e.target.value=''}} /></label><p>{importQuestions.length}<ScreenText id="QuizQuestionBank.ab6870a996cd92f8"> questions ready</ScreenText></p><button type="button" disabled={!importDate||!importTitle.trim()||!importQuestions.length} onClick={()=>void importSet()}><ScreenText id="QuizQuestionBank.6b34a1b5d05242c8">Import dated set</ScreenText></button></details>
 </fieldset>{message&&<p role="status">{message}</p>}</details>
}

