import { useEffect, useState } from 'react'
import { parseQuizUpload,quizCsvTemplate,quizTextTemplate,type UploadedQuiz } from '../lib/quizUpload'
import '../pages/QuizUpload.css'
export function QuizUpload({disabled,date,onApply}:{disabled:boolean;date:string;onApply:(quiz:UploadedQuiz,append:boolean)=>boolean}){
 const [draft,setDraft]=useState<UploadedQuiz|null>(null),[text,setText]=useState(''),[error,setError]=useState(''),[checked,setChecked]=useState(false),[reading,setReading]=useState(false),[dragging,setDragging]=useState(false),[append,setAppend]=useState(true)
 useEffect(()=>{setChecked(false)},[date])
 function clear(){setDraft(null);setChecked(false);setError('')}
 function parse(value:string,format:'json'|'csv'|'text'){clear();try{setDraft(parseQuizUpload(value,format))}catch(e){setError(String((e as Error).message))}}
 async function fileUpload(file:File){if(disabled||reading)return;setReading(true);clear();try{if(file.size>1024*1024)throw new Error('Choose a quiz file smaller than 1 MB.');const ext=file.name.split('.').pop()?.toLowerCase();if(!['json','csv','txt'].includes(ext??''))throw new Error('Choose a TXT, CSV or JSON file. You can copy text from a document into the paste box.');parse(await file.text(),ext==='txt'?'text':ext as 'json'|'csv')}catch(e){setDraft(null);setError(String((e as Error).message))}finally{setReading(false)}}
 function download(content:string,name:string){const url=URL.createObjectURL(new Blob([content],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 return <section className="quiz-upload"><h2>Paste or upload questions</h2><p>Copy your list of questions, choices and correct answers here, or drop a file. Review first, then add it to the quiz for <strong>{date}</strong>.</p><fieldset disabled={disabled||reading}>
 <label>Paste quiz questions<textarea value={text} maxLength={200000} rows={9} placeholder={quizTextTemplate} onChange={e=>{setText(e.target.value);clear()}} /></label><p className="quiz-upload-hint">Use A., B., C. for choices and “Correct Answer: B” after each question. Up to 50 questions.</p><button type="button" disabled={!text.trim()} onClick={()=>parse(text,'text')}>Preview pasted questions</button>
 <div className={`quiz-file-drop ${dragging?'dragging':''}`} onDragOver={e=>{e.preventDefault();if(!disabled&&!reading)setDragging(true)}} onDragLeave={()=>setDragging(false)} onDrop={e=>{e.preventDefault();setDragging(false);if(disabled||reading)return;if(e.dataTransfer.files.length!==1){clear();setError('Drop one quiz file at a time.');return}void fileUpload(e.dataTransfer.files[0])}}><strong>Drop a quiz file here</strong><span>TXT, CSV or JSON · up to 1 MB</span><label>Or choose a file<input type="file" accept=".json,.csv,.txt,application/json,text/csv,text/plain" onChange={e=>{const file=e.target.files?.[0];if(file)void fileUpload(file);e.target.value=''}} /></label></div>
 <div className="quiz-actions"><button type="button" onClick={()=>download(quizTextTemplate,'quiz-template.txt')}>Text example</button><button type="button" onClick={()=>download(quizCsvTemplate,'quiz-template.csv')}>CSV template</button></div>
 {reading&&<p role="status">Reading quiz…</p>}{error&&<p role="alert">{error}</p>}
 {draft&&<div className="quiz-upload-preview"><h3>{draft.title||'Imported questions'} · {draft.questions.length} questions</h3>{draft.quizDate&&draft.quizDate!==date&&<p role="alert">The file’s date is {draft.quizDate}. These questions will load into {date}. Change the editor date first if needed.</p>}{draft.questions.map((q,i)=><details key={i}><summary>{i+1}. {q.prompt}</summary><ol type="A">{q.options.map((o,n)=><li key={n}>{o}{n===q.correct?' ✓ Correct':''}</li>)}</ol>{q.explanation&&<p>{q.explanation}</p>}</details>)}<label>Import action<select value={append?'append':'replace'} onChange={e=>{setAppend(e.target.value==='append');setChecked(false)}}><option value="append">Add to current questions</option><option value="replace">Replace current questions</option></select></label><label className="quiz-choice"><input type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)} />I reviewed the questions and correct answers.</label><button type="button" className="primary-button" disabled={!checked} onClick={()=>{if(onApply(draft,append)){clear();setText('')}}}>{append?'Add questions':'Replace questions'} for {date}</button><p className="quiz-upload-hint">You can edit everything below before saving or publishing.</p></div>}
 </fieldset></section>
}
