// page-designer-instrumented
import { PageWord, PageOption } from "./PageDesign"
import { ScreenText } from "./ScreenText"
import { useEffect, useState } from 'react'
import { parseQuizUpload,quizCsvTemplate,quizTextTemplate,type UploadedQuiz } from '../lib/quizUpload'
import '../pages/QuizUpload.css'
export function QuizUpload({disabled,date,onApply}:{disabled:boolean;date:string;onApply:(quiz:UploadedQuiz,append:boolean)=>boolean}){
 const [draft,setDraft]=useState<UploadedQuiz|null>(null),[text,setText]=useState(''),[error,setError]=useState(''),[checked,setChecked]=useState(false),[reading,setReading]=useState(false),[dragging,setDragging]=useState(false),[append,setAppend]=useState(true)
 useEffect(()=>{setChecked(false)},[date])
 function clear(){setDraft(null);setChecked(false);setError('')}
 function parse(value:string,format:'json'|'csv'|'text'){clear();try{setDraft(parseQuizUpload(value,format))}catch(e){setError(String((e as Error).message))}}
 async function fileUpload(file:File){if(disabled||reading)return;setReading(true);clear();try{if(file.size>1024*1024)throw new Error('Choose a quiz file smaller than 1 MB.');const ext=file.name.split('.').pop()?.toLowerCase();if(!['json','csv','txt'].includes(ext??''))throw new Error('Choose a TXT, CSV or JSON file. You can copy text from a document into the paste box.');parse(await file.text(),ext==='txt'?'text':ext as 'json'|'csv')}catch(e){setDraft(null);setError(String((e as Error).message))}finally{setReading(false)}}
 function download(content:string,name:string){const url=URL.createObjectURL(new Blob([content],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 return <section data-design-block="copy.f0cc56141218b7cb.1" className="quiz-upload"><h2 data-design-block="copy.b47947f880e36140.1"><ScreenText id="QuizUpload.6b66f804c8d5da9f">Paste or upload questions</ScreenText></h2><p data-design-block="copy.3730497a3c0c8303.1"><ScreenText id="QuizUpload.c75c9cc8c8674e5e">Copy your list of questions, choices and correct answers here, or drop a file. Review first, then add it to the quiz for </ScreenText><strong>{date}</strong><PageWord id="copy.37fa7d8b68c3a1bb.1">.</PageWord></p><fieldset data-design-block="copy.61ad2bcc3662f2bc.1" disabled={disabled||reading}>
 <label data-design-block="copy.7c568c2757cf9c0e.1"><ScreenText id="QuizUpload.7a0f88cbb146920a">Paste quiz questions</ScreenText><textarea value={text} maxLength={200000} rows={9} placeholder={quizTextTemplate} onChange={e=>{setText(e.target.value);clear()}} /></label><p data-design-block="copy.2b1cc690517389dc.1" className="quiz-upload-hint"><ScreenText id="QuizUpload.ed6641ab99463735">Use A., B., C. for choices and “Correct Answer: B” after each question. Up to 50 questions.</ScreenText></p><button data-design-block="copy.e198f59080cbde79.1" type="button" disabled={!text.trim()} onClick={()=>parse(text,'text')}><ScreenText id="QuizUpload.dcd1cdf0be32a316">Preview pasted questions</ScreenText></button>
 <div data-design-block="copy.27a3af2157edde1c.1" className={`quiz-file-drop ${dragging?'dragging':''}`} onDragOver={e=>{e.preventDefault();if(!disabled&&!reading)setDragging(true)}} onDragLeave={()=>setDragging(false)} onDrop={e=>{e.preventDefault();setDragging(false);if(disabled||reading)return;if(e.dataTransfer.files.length!==1){clear();setError('Drop one quiz file at a time.');return}void fileUpload(e.dataTransfer.files[0])}}><strong><ScreenText id="QuizUpload.103e8d87e4c353a3">Drop a quiz file here</ScreenText></strong><span><ScreenText id="QuizUpload.b5bdcd9a74fa92f3">TXT, CSV or JSON · up to 1 MB</ScreenText></span><label data-design-block="copy.7c568c2757cf9c0e.2"><ScreenText id="QuizUpload.5df71b577323e8be">Or choose a file</ScreenText><input type="file" accept=".json,.csv,.txt,application/json,text/csv,text/plain" onChange={e=>{const file=e.target.files?.[0];if(file)void fileUpload(file);e.target.value=''}} /></label></div>
 <div data-design-block="copy.29285450214c67c6.1" className="quiz-actions"><button data-design-block="copy.6babd9b54226f320.1" type="button" onClick={()=>download(quizTextTemplate,'quiz-template.txt')}><ScreenText id="QuizUpload.102b0049c9f7a07f">Text example</ScreenText></button><button data-design-block="copy.153ec0dcf5f757e8.1" type="button" onClick={()=>download(quizCsvTemplate,'quiz-template.csv')}><ScreenText id="QuizUpload.3fbf5326bd0fc001">CSV template</ScreenText></button></div>
 {reading&&<p data-design-block="copy.f1e15a0a0430dbd9.1" role="status"><ScreenText id="QuizUpload.690e1acf410d37df">Reading quiz…</ScreenText></p>}{error&&<p data-design-block="copy.f2dcac9d930793b1.1" role="alert">{error}</p>}
 {draft&&<div data-design-block="copy.422196426feda696.1" className="quiz-upload-preview"><h3 data-design-block="copy.b332f621f586683b.1">{draft.title||'Imported questions'}<PageWord id="copy.aa68a482d0e38cbe.1">· </PageWord>{draft.questions.length}<ScreenText id="QuizUpload.81aa5d96259a023c"> questions</ScreenText></h3>{draft.quizDate&&draft.quizDate!==date&&<p data-design-block="copy.f2dcac9d930793b1.2" role="alert"><ScreenText id="QuizUpload.49e1dfda156b9511">The file’s date is </ScreenText>{draft.quizDate}<ScreenText id="QuizUpload.23dd2f9619534d21">. These questions will load into </ScreenText>{date}<ScreenText id="QuizUpload.2d38034e16a355e5">. Change the editor date first if needed.</ScreenText></p>}{draft.questions.map((q,i)=><details key={i}><summary>{i+1}<PageWord id="copy.37fa7d8b68c3a1bb.2">. </PageWord>{q.prompt}</summary><ol type="A">{q.options.map((o,n)=><li key={n}>{o}{n===q.correct?<PageWord id="copy.380673fe8da90baa.1">{" ✓ Correct"}</PageWord>:<PageWord id="copy.b4bfe1da84d2d26b.1">{""}</PageWord>}</li>)}</ol>{q.explanation&&<p data-design-block="copy.3730497a3c0c8303.2">{q.explanation}</p>}</details>)}<label data-design-block="copy.7c568c2757cf9c0e.3"><ScreenText id="QuizUpload.67a6b697d58ce0a6">Import action</ScreenText><select value={append?'append':'replace'} onChange={e=>{setAppend(e.target.value==='append');setChecked(false)}}><PageOption designId="copy.5a533ace50d96c7b.1" value="append"><ScreenText plain id="QuizUpload.5ec41fa7efaebb4e">Add to current questions</ScreenText></PageOption><PageOption designId="copy.95530ba70c1d865f.1" value="replace"><ScreenText plain id="QuizUpload.01d172ee376e1ed0">Replace current questions</ScreenText></PageOption></select></label><label data-design-block="copy.d2171f5ab3e2db9f.1" className="quiz-choice"><input type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)} /><ScreenText id="QuizUpload.428da7542f469998">I reviewed the questions and correct answers.</ScreenText></label><button data-design-block="copy.6d25bc4101ba9060.1" type="button" className="primary-button" disabled={!checked} onClick={()=>{if(onApply(draft,append)){clear();setText('')}}}>{append?<PageWord id="copy.aa33a1eeda5860d3.1">{"Add questions"}</PageWord>:<PageWord id="copy.95d7a88d7930150f.1">{"Replace questions"}</PageWord>}<ScreenText id="QuizUpload.e64adf90d0e5151f"> for </ScreenText>{date}</button><p data-design-block="copy.2b1cc690517389dc.2" className="quiz-upload-hint"><ScreenText id="QuizUpload.61c23c7b08003abe">You can edit everything below before saving or publishing.</ScreenText></p></div>}
 </fieldset></section>
}
