// page-designer-instrumented
import { PageWord } from "./PageDesign"
import { ScreenText } from "./ScreenText"
import { useEffect, useState } from 'react'
import { supabase } from '../lib/supabase'
import { submissionLabel } from '../lib/submissionTime'
type Staff={user_id:string;name:string;required:boolean;submitted:boolean}
export function QuizRequiredStaff({location,quizId}:{location:string;quizId:string}) {
 const [staff,setStaff]=useState<Staff[]>([]);const [due,setDue]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('')
 useEffect(()=>{let live=true;setBusy(true);setError('');setMessage('');setStaff([]);void supabase.rpc('quiz_manager_roster',{p_location_id:location,p_quiz_id:quizId}).then(({data,error})=>{if(!live)return;if(error)setError(error.message);else{setStaff(data.staff);setDue(data.due_at)}setBusy(false)});return()=>{live=false}},[location,quizId])
 const closed=!!due&&Date.now()>=new Date(due).getTime()
 async function save(){setBusy(true);setError('');setMessage('');try{const {error}=await supabase.rpc('quiz_manager_set_roster',{p_location_id:location,p_quiz_id:quizId,p_users:staff.filter(s=>s.required).map(s=>s.user_id)});if(error)throw error;setMessage('Required staff saved.')}catch(e){setError(String((e as {message?:string}).message??e))}finally{setBusy(false)}}
 return <article data-design-block="copy.8d991332b78ee1e6.1" className="mod-review"><h2 data-design-block="copy.fb8278a7ea822d8f.1"><ScreenText id="QuizRequiredStaff.33a292e2be22e42e">Staff Required to Take This Quiz</ScreenText></h2><p data-design-block="copy.99c11636d537f7a0.1"><ScreenText id="QuizRequiredStaff.cbeee98f60a17d60">Select staff working this day. Only selected staff receive a 10-point deduction if they miss the deadline.</ScreenText></p><p data-design-block="copy.99c11636d537f7a0.2"><ScreenText id="QuizRequiredStaff.e433feea7b154ab8">Deadline: </ScreenText>{submissionLabel(due)}</p><p data-design-block="copy.99c11636d537f7a0.3"><ScreenText id="QuizRequiredStaff.a9847e1e69e60381">Late submission does not remove the missed-quiz deduction. The GM can waive it in Points.</ScreenText></p>{error&&<p data-design-block="copy.18c09048c7866dcf.1" role="alert">{error}</p>}{message&&<p data-design-block="copy.2808db16f96725cb.1" role="status">{message}</p>}{closed&&<p data-design-block="copy.99c11636d537f7a0.4"><ScreenText id="QuizRequiredStaff.347f969be1df5343">The deadline has passed. Point corrections are available to the GM in Points.</ScreenText></p>}<fieldset data-design-block="copy.95111807f3445bd4.1" disabled={busy||closed}>{staff.map(s=><label data-design-block="copy.753840a68efdd2a1.1" key={s.user_id} className="quiz-choice"><input type="checkbox" checked={s.required} onChange={e=>setStaff(rows=>rows.map(r=>r.user_id===s.user_id?{...r,required:e.target.checked}:r))} />{s.name}{s.submitted?<PageWord id="copy.92a24714d9030b57.1">{" · Submitted"}</PageWord>:<PageWord id="copy.b37368d168fc1614.1">{""}</PageWord>}</label>)}<button data-design-block="copy.20afbdc138bd50d8.1" type="button" onClick={()=>void save()}><ScreenText id="QuizRequiredStaff.e76e1c7e28631c9c">Save Required Staff</ScreenText></button></fieldset></article>
}
