import { ScreenText } from "./ScreenText"
import { useEffect, useState } from 'react'
import { parseQuizUpload,quizCsvTemplate,quizTextTemplate,type UploadedQuiz } from '../lib/quizUpload'
import '../pages/QuizUpload.css'
export function QuizUpload({disabled,date,onApply}:{disabled:boolean;date:string;onApply:(quiz:UploadedQuiz,append:boolean)=>boolean}){
 const [draft,setDraft]=useState<UploadedQuiz|null>(null),[text,setText]=useState(''),[error,setError]=useState(''),[checked,setChecked]=useState(false),[reading,setReading]=useState(false),[dragging,setDragging]=useState(false),[append,setAppend]=useState(true)
 useEffect(()=>{setChecked(false)},[date])
 function clear(){setDraft(null);setChecked(false);setError('')}
 function parse(value:string,format:'json'|'csv'|'text'){clear();try{setDraft(parseQuizUpload(value,format))}catch(e){setError(String((e as Error).message))}}
 async function fileUpload(file:File){if(disabled||reading)return;setReading(true);clear();try{if(file.size>1024*1024)throw new Error('Choose a quiz file smaller than 1 MB.');const ext=file.name.split('.').pop()?.toLowerCase();if(!['json','csv','txt'].includes(ext??''))throw new Error('Choose a TXT, CSV or JSON file. You can copy text from a document into the paste box.');parse(await file.text(),ext==='txt'?'text':ext as 'json'|'csv')}catch(e){setDraft(null);setError(String((e as Error).message))}finally{setReading(false)}}
 function download(content:string,name:string){const url=URL.createObjectURL(new Blob([content],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 return <section className="quiz-upload"><h2><ScreenText id="QuizUpload.6b66f804c8d5da9f">Paste or upload questions</ScreenText></h2><p><ScreenText id="QuizUpload.c75c9cc8c8674e5e">Copy your list of questions, choices and correct answers here, or drop a file. Review first, then add it to the quiz for </ScreenText><strong>{date}</strong>.</p><fieldset disabled={disabled||reading}>
 <label><ScreenText id="QuizUpload.7a0f88cbb146920a">Paste quiz questions</ScreenText><textarea value={text} maxLength={200000} rows={9} placeholder={quizTextTemplate} onChange={e=>{setText(e.target.value);clear()}} /></label><p className="quiz-upload-hint"><ScreenText id="QuizUpload.ed6641ab99463735">Use A., B., C. for choices and “Correct Answer: B” after each question. Up to 50 questions.</ScreenText></p><button type="button" disabled={!text.trim()} onClick={()=>parse(text,'text')}><ScreenText id="QuizUpload.dcd1cdf0be32a316">Preview pasted questions</ScreenText></button>
 <div className={`quiz-file-drop ${dragging?'dragging':''}`} onDragOver={e=>{e.preventDefault();if(!disabled&&!reading)setDragging(true)}} onDragLeave={()=>setDragging(false)} onDrop={e=>{e.preventDefault();setDragging(false);if(disabled||reading)return;if(e.dataTransfer.files.length!==1){clear();setError('Drop one quiz file at a time.');return}void fileUpload(e.dataTransfer.files[0])}}><strong><ScreenText id="QuizUpload.103e8d87e4c353a3">Drop a quiz file here</ScreenText></strong><span><ScreenText id="QuizUpload.b5bdcd9a74fa92f3">TXT, CSV or JSON · up to 1 MB</ScreenText></span><label><ScreenText id="QuizUpload.5df71b577323e8be">Or choose a file</ScreenText><input type="file" accept=".json,.csv,.txt,application/json,text/csv,text/plain" onChange={e=>{const file=e.target.files?.[0];if(file)void fileUpload(file);e.target.value=''}} /></label></div>
 <div className="quiz-actions"><button type="button" onClick={()=>download(quizTextTemplate,'quiz-template.txt')}><ScreenText id="QuizUpload.102b0049c9f7a07f">Text example</ScreenText></button><button type="button" onClick={()=>download(quizCsvTemplate,'quiz-template.csv')}><ScreenText id="QuizUpload.3fbf5326bd0fc001">CSV template</ScreenText></button></div>
 {reading&&<p role="status"><ScreenText id="QuizUpload.690e1acf410d37df">Reading quiz…</ScreenText></p>}{error&&<p role="alert">{error}</p>}
 {draft&&<div className="quiz-upload-preview"><h3>{draft.title||'Imported questions'} · {draft.questions.length}<ScreenText id="QuizUpload.81aa5d96259a023c"> questions</ScreenText></h3>{draft.quizDate&&draft.quizDate!==date&&<p role="alert"><ScreenText id="QuizUpload.49e1dfda156b9511">The file’s date is </ScreenText>{draft.quizDate}<ScreenText id="QuizUpload.23dd2f9619534d21">. These questions will load into </ScreenText>{date}<ScreenText id="QuizUpload.2d38034e16a355e5">. Change the editor date first if needed.</ScreenText></p>}{draft.questions.map((q,i)=><details key={i}><summary>{i+1}. {q.prompt}</summary><ol type="A">{q.options.map((o,n)=><li key={n}>{o}{n===q.correct?' ✓ Correct':''}</li>)}</ol>{q.explanation&&<p>{q.explanation}</p>}</details>)}<label><ScreenText id="QuizUpload.67a6b697d58ce0a6">Import action</ScreenText><select value={append?'append':'replace'} onChange={e=>{setAppend(e.target.value==='append');setChecked(false)}}><option value="append"><ScreenText id="QuizUpload.5ec41fa7efaebb4e">Add to current questions</ScreenText></option><option value="replace"><ScreenText id="QuizUpload.01d172ee376e1ed0">Replace current questions</ScreenText></option></select></label><label className="quiz-choice"><input type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)} /><ScreenText id="QuizUpload.428da7542f469998">I reviewed the questions and correct answers.</ScreenText></label><button type="button" className="primary-button" disabled={!checked} onClick={()=>{if(onApply(draft,append)){clear();setText('')}}}>{append?'Add questions':'Replace questions'}<ScreenText id="QuizUpload.e64adf90d0e5151f"> for </ScreenText>{date}</button><p className="quiz-upload-hint"><ScreenText id="QuizUpload.61c23c7b08003abe">You can edit everything below before saving or publishing.</ScreenText></p></div>}
 </fieldset></section>
}
