// page-designer-instrumented
import { PageWord } from "./PageDesign"
import { ScreenText } from "./ScreenText"
import { useEffect,useState } from 'react'
import { Link } from 'react-router-dom'
import { loadSalesTargets } from '../lib/loadSalesTargets'
import { calculateTargets,salesMoney,targetsChunk } from '../lib/salesTargets'
export function SalesTargetPreview({location,date,disabled,onAdd}:{location:string;date:string;disabled:boolean;onAdd:(text:string)=>void}){
 const [data,setData]=useState<Awaited<ReturnType<typeof loadSalesTargets>>|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[refresh,setRefresh]=useState(0)
 useEffect(()=>{let live=true;setData(null);setError('');setLoading(true);void loadSalesTargets(location,date).then(d=>{if(live)setData(d)}).catch(e=>{if(live)setError(String(e.message??e))}).finally(()=>{if(live)setLoading(false)});return()=>{live=false}},[location,date,refresh])
 const t=data?calculateTargets(date,data.inputs,data.shifts):null
 return <section data-design-block="copy.b871cf7e16cb648b.1" className="feed-card"><h3 data-design-block="copy.1f59a2b5d458ad3a.1"><ScreenText id="SalesTargetPreview.1007f835daa57934">Automatic sales targets</ScreenText></h3><p data-design-block="copy.447fa36ea1a90053.1"><ScreenText id="SalesTargetPreview.d50a6366aa174e22">From six matching weekdays and the published 7shifts schedule for </ScreenText>{date}<PageWord id="copy.36757f106e37083c.1">.</PageWord></p><Link to="/settings/sales-targets"><ScreenText id="SalesTargetPreview.73753ccff0f23c9e">Sales target setup →</ScreenText></Link> <button data-design-block="copy.47d8dbeea129b1a5.1" type="button" disabled={loading||disabled} onClick={()=>setRefresh(v=>v+1)}><ScreenText id="SalesTargetPreview.3a79bd01f89f1b9f">Refresh targets</ScreenText></button>{loading&&<p data-design-block="copy.36d6e65e8d13f269.1" role="status"><ScreenText id="SalesTargetPreview.7747bd3454d5fb6b">Loading sales targets…</ScreenText></p>}{error&&<p data-design-block="copy.a8ae5da348ab643f.1" role="alert">{error}</p>}{t&&<><p data-design-block="copy.447fa36ea1a90053.2"><ScreenText id="SalesTargetPreview.2a83e6948fec973b">Team goal: </ScreenText><strong>{salesMoney(t.total)}</strong><ScreenText id="SalesTargetPreview.fc3bf496cb1c89df"> · Bar </ScreenText>{salesMoney(t.bar)}<ScreenText id="SalesTargetPreview.fdf5053e47551e97"> · Floor </ScreenText>{salesMoney(t.floor)}</p>{t.issues.map(issue=><p data-design-block="copy.c374486305137725.1" key={issue} role="alert">{issue}</p>)}<button data-design-block="copy.3741db202e88b2d1.1" type="button" disabled={disabled||!t.ready} onClick={()=>{try{onAdd(targetsChunk(date,data!.inputs,data!.shifts))}catch(e){setError(String((e as Error).message))}}}><ScreenText id="SalesTargetPreview.1ed67c35bc4d51eb">Add calculated sales targets</ScreenText></button><p data-design-block="copy.447fa36ea1a90053.3"><small><ScreenText id="SalesTargetPreview.f7bae67372f735b4">Inserted targets are an editable snapshot for this post. Refresh and add again if the schedule changes before publishing.</ScreenText></small></p></>}</section>
}
