import { ScreenText } from "./ScreenText"
import { SectionEmployeePicker } from './SectionEmployeePicker'
import { useEffect, useRef, useState } from 'react'
import { supabase } from '../lib/supabase'
import { ClockTime } from './ClockTime'
export type SectionPlan={id:string;employee_id:string|null;guest_name:string|null;name:string;table_ids:string[];starts_at:string;ends_at:string;version:number;assignable:boolean;published_at:string|null}
type Table={id:string;table_name:string;seat_count:number}
const zone='America/Chicago'
function parts(value:Date){const p=new Intl.DateTimeFormat('en-CA',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(value);const get=(key:string)=>p.find(x=>x.type===key)?.value;return {date:`${get('year')}-${get('month')}-${get('day')}`,time:`${get('hour')}:${get('minute')}`}}
const label=(value:string)=>new Date(value).toLocaleString('en-US',{timeZone:zone,month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit',hour12:true})
export function SectionSchedule({refreshKey=0,locationId,selectedTableIds,tables,employees,onLoaded,onSelect}:{refreshKey?:number;locationId:string;selectedTableIds:string[];tables:Table[];employees:{id:string;name:string}[];onLoaded:(plans:SectionPlan[],offset:number)=>void;onSelect:(ids:string[])=>void}){
 const [plans,setPlans]=useState<SectionPlan[]>([]),[canManage,setCanManage]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[editing,setEditing]=useState<SectionPlan|null>(null),[show,setShow]=useState(false)
 const [date,setDate]=useState(()=>parts(new Date()).date),[start,setStart]=useState(''),[end,setEnd]=useState(''),[name,setName]=useState(''),[employee,setEmployee]=useState<string|null>(''),[guestName,setGuestName]=useState(''),[notice,setNotice]=useState('')
 const request=useRef(crypto.randomUUID()),callback=useRef(onLoaded);callback.current=onLoaded
 async function load(){const r=await supabase.rpc('floor_schedule_list',{p_location_id:locationId});if(r.error)throw r.error;const rows=(r.data?.plans??[]) as SectionPlan[];setPlans(rows);setCanManage(!!r.data?.can_manage);callback.current(rows,new Date(r.data.server_now).getTime()-Date.now())}
 useEffect(()=>{if(!locationId)return;let active=true;const reload=async()=>{try{const r=await supabase.rpc('floor_schedule_list',{p_location_id:locationId});if(r.error)throw r.error;if(!active)return;const rows=(r.data?.plans??[]) as SectionPlan[];setPlans(rows);setCanManage(!!r.data?.can_manage);setError('');callback.current(rows,new Date(r.data.server_now).getTime()-Date.now())}catch(e){if(active)setError(String((e as {message?:string}).message??e))}};void reload();const timer=window.setInterval(()=>void reload(),30000);const focus=()=>void reload();window.addEventListener('focus',focus);document.addEventListener('visibilitychange',focus);return()=>{active=false;window.clearInterval(timer);window.removeEventListener('focus',focus);document.removeEventListener('visibilitychange',focus)}},[locationId,refreshKey])
 function open(plan:SectionPlan|null){setEditing(plan);setShow(true);setError('');setNotice('');request.current=crypto.randomUUID();setName(plan?.name??'');setEmployee(plan?.employee_id??(plan?.guest_name?null:''));setGuestName(plan?.guest_name??'');setDate(plan?parts(new Date(plan.starts_at)).date:parts(new Date()).date);setStart(plan?parts(new Date(plan.starts_at)).time:'');setEnd(plan?parts(new Date(plan.ends_at)).time:'');if(plan)onSelect(plan.table_ids)}
 async function save(){setBusy(true);setError('');try{const r=await supabase.rpc('floor_schedule_save_person',{p_location_id:locationId,p_id:editing?.id??null,p_version:editing?.version??null,p_name:name.trim(),p_employee_id:employee,p_guest_name:employee===null?guestName.trim():null,p_table_ids:selectedTableIds,p_date:date,p_start:start,p_end:end,p_request_id:request.current});if(r.error)throw r.error;setShow(false);setEditing(null);setNotice('Draft saved. Publish it when staff should see it.');await load()}catch(e){setError(String((e as {message?:string}).message??e))}finally{setBusy(false)}}
 async function cancel(plan:SectionPlan){if(!window.confirm(`Remove ${plan.name} scheduled for ${label(plan.starts_at)}?`))return;setBusy(true);setError('');try{const r=await supabase.rpc('floor_schedule_cancel',{p_location_id:locationId,p_id:plan.id,p_version:plan.version});if(r.error)throw r.error;await load();setNotice('Planned section removed.')}catch(e){setError(String((e as {message?:string}).message??e))}finally{setBusy(false)}}
 async function publish(plan:SectionPlan){setBusy(true);setError('');try{const r=await supabase.rpc('floor_schedule_publish',{p_location_id:locationId,p_id:plan.id,p_version:plan.version,p_publish:!plan.published_at});if(r.error)throw r.error;await load();setNotice(plan.published_at?'Section unpublished.':'Section published for staff.')}catch(e){setError(String((e as {message?:string}).message??e))}finally{setBusy(false)}}
 return <section className="card" aria-label="Scheduled sections"><h2><ScreenText id="SectionSchedule.196da854f649d6cb">Scheduled sections</ScreenText></h2><p><ScreenText id="SectionSchedule.8f62c3eb1cefcd83">Save private drafts by date and time, even before a shift opens. Publish when ready for staff. Editing a published plan returns it to draft until you publish again. Times are New Orleans time. At the end of a window, regular shift assignments resume. Seated parties keep their server.</ScreenText></p>{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 {canManage&&<button type="button" disabled={busy||!selectedTableIds.length} onClick={()=>open(null)}><ScreenText id="SectionSchedule.e7bfe854841871f8">Schedule selected tables</ScreenText></button>}
 {!selectedTableIds.length&&canManage&&<p><ScreenText id="SectionSchedule.cfd10df2281dd979">Select tables on the floor map first.</ScreenText></p>}
 <details><summary><ScreenText id="SectionSchedule.e8bac123398122ab">Current and upcoming plans (</ScreenText>{plans.length})</summary><div style={{display:'grid',gap:10,marginTop:10}}>{plans.map(plan=><article className="card" key={plan.id}><p><strong>{plan.published_at?'Published':'Draft · hidden from staff'}</strong></p><strong>{plan.name} · {plan.guest_name || employees.find(e=>e.id===plan.employee_id)?.name || 'Team member'}</strong>{!plan.assignable&&<p><ScreenText id="SectionSchedule.f306d16c91bb9dee">Employee is inactive. Edit this plan to choose another employee.</ScreenText></p>}<p>{label(plan.starts_at)} – {label(plan.ends_at)}</p><p>{plan.table_ids.map(id=>tables.find(t=>t.id===id)?.table_name??'Unavailable table').join(', ')}</p><button type="button" onClick={()=>onSelect(plan.table_ids)}><ScreenText id="SectionSchedule.a2c3a83e61a1a060">Show tables</ScreenText></button>{canManage&&<><button type="button" disabled={busy} onClick={()=>void publish(plan)}>{plan.published_at?'Unpublish':'Publish'}</button><button type="button" disabled={busy} onClick={()=>open(plan)}><ScreenText id="SectionSchedule.1de30d8950882701">Edit</ScreenText></button><button type="button" disabled={busy} onClick={()=>void cancel(plan)}><ScreenText id="SectionSchedule.ddfd18c59fef293e">Remove plan</ScreenText></button></>}</article>)}</div></details>
 {show&&<form onSubmit={e=>{e.preventDefault();void save()}}><fieldset disabled={busy}><legend>{editing?'Edit scheduled section':'Schedule selected tables'}</legend><p>{selectedTableIds.map(id=>tables.find(t=>t.id===id)?.table_name??id).join(', ')}</p><div className="form-grid"><label><ScreenText id="SectionSchedule.5a73214e5c76440d">Section name</ScreenText><input required maxLength={100} value={name} onChange={e=>setName(e.target.value)} /></label><SectionEmployeePicker employees={employees} employeeId={employee} guestName={guestName} disabled={busy} onChange={(id,name)=>{setEmployee(id);setGuestName(name)}}/><label><ScreenText id="SectionSchedule.c4174443f0091ab9">Date</ScreenText><input required type="date" value={date} onChange={e=>setDate(e.target.value)} /></label><label><ScreenText id="SectionSchedule.fb3f82054aa55dd6">Start</ScreenText><ClockTime required label="Section start" value={start} onChange={setStart}/></label><label><ScreenText id="SectionSchedule.19c1e1516164e177">End</ScreenText><ClockTime required label="Section end" value={end} onChange={setEnd}/></label></div><p><ScreenText id="SectionSchedule.2a88f3060a920546">An end time earlier than start means the next day. Overlapping plans for the same tables are blocked.</ScreenText></p><button disabled={!selectedTableIds.length||busy}>{busy?'Saving…':'Save draft'}</button><button type="button" onClick={()=>{setShow(false);setEditing(null)}}><ScreenText id="SectionSchedule.ce7ffdd48895e09d">Cancel</ScreenText></button></fieldset></form>}
 </section>
}
