import { useEffect, useRef, useState } from 'react'
import { supabase } from '../lib/supabase'
import { ClockTime } from './ClockTime'
export type SectionPlan={id:string;employee_id:string;name:string;table_ids:string[];starts_at:string;ends_at:string;version:number;assignable:boolean}
type Table={id:string;table_name:string;seat_count:number}
const zone='America/Chicago'
function parts(value:Date){const p=new Intl.DateTimeFormat('en-CA',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(value);const get=(key:string)=>p.find(x=>x.type===key)?.value;return {date:`${get('year')}-${get('month')}-${get('day')}`,time:`${get('hour')}:${get('minute')}`}}
const label=(value:string)=>new Date(value).toLocaleString('en-US',{timeZone:zone,month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit',hour12:true})
export function SectionSchedule({locationId,selectedTableIds,tables,employees,onLoaded,onSelect}:{locationId:string;selectedTableIds:string[];tables:Table[];employees:{id:string;name:string}[];onLoaded:(plans:SectionPlan[],offset:number)=>void;onSelect:(ids:string[])=>void}){
 const [plans,setPlans]=useState<SectionPlan[]>([]),[canManage,setCanManage]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[editing,setEditing]=useState<SectionPlan|null>(null),[show,setShow]=useState(false)
 const [date,setDate]=useState(()=>parts(new Date()).date),[start,setStart]=useState(''),[end,setEnd]=useState(''),[name,setName]=useState(''),[employee,setEmployee]=useState(''),[notice,setNotice]=useState('')
 const request=useRef(crypto.randomUUID()),callback=useRef(onLoaded);callback.current=onLoaded
 async function load(){const r=await supabase.rpc('floor_schedule_list',{p_location_id:locationId});if(r.error)throw r.error;const rows=(r.data?.plans??[]) as SectionPlan[];setPlans(rows);setCanManage(!!r.data?.can_manage);callback.current(rows,new Date(r.data.server_now).getTime()-Date.now())}
 useEffect(()=>{if(!locationId)return;let active=true;const reload=async()=>{try{const r=await supabase.rpc('floor_schedule_list',{p_location_id:locationId});if(r.error)throw r.error;if(!active)return;const rows=(r.data?.plans??[]) as SectionPlan[];setPlans(rows);setCanManage(!!r.data?.can_manage);setError('');callback.current(rows,new Date(r.data.server_now).getTime()-Date.now())}catch(e){if(active)setError(String((e as {message?:string}).message??e))}};void reload();const timer=window.setInterval(()=>void reload(),30000);const focus=()=>void reload();window.addEventListener('focus',focus);document.addEventListener('visibilitychange',focus);return()=>{active=false;window.clearInterval(timer);window.removeEventListener('focus',focus);document.removeEventListener('visibilitychange',focus)}},[locationId])
 function open(plan:SectionPlan|null){setEditing(plan);setShow(true);setError('');setNotice('');request.current=crypto.randomUUID();setName(plan?.name??'');setEmployee(plan?.employee_id??'');setDate(plan?parts(new Date(plan.starts_at)).date:parts(new Date()).date);setStart(plan?parts(new Date(plan.starts_at)).time:'');setEnd(plan?parts(new Date(plan.ends_at)).time:'');if(plan)onSelect(plan.table_ids)}
 async function save(){setBusy(true);setError('');try{const r=await supabase.rpc('floor_schedule_save',{p_location_id:locationId,p_id:editing?.id??null,p_version:editing?.version??null,p_name:name.trim(),p_employee_id:employee,p_table_ids:selectedTableIds,p_date:date,p_start:start,p_end:end,p_request_id:request.current});if(r.error)throw r.error;setShow(false);setEditing(null);setNotice('Section schedule saved. It will be used on Floor during its time window.');await load()}catch(e){setError(String((e as {message?:string}).message??e))}finally{setBusy(false)}}
 async function cancel(plan:SectionPlan){if(!window.confirm(`Remove ${plan.name} scheduled for ${label(plan.starts_at)}?`))return;setBusy(true);setError('');try{const r=await supabase.rpc('floor_schedule_cancel',{p_location_id:locationId,p_id:plan.id,p_version:plan.version});if(r.error)throw r.error;await load();setNotice('Planned section removed.')}catch(e){setError(String((e as {message?:string}).message??e))}finally{setBusy(false)}}
 return <section className="card" aria-label="Scheduled sections"><h2>Scheduled sections</h2><p>Plan sections by date and time, even before a shift opens. Times are New Orleans time. At the end of a window, regular shift assignments resume. Seated parties keep their server.</p>{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 {canManage&&<button type="button" disabled={busy||!selectedTableIds.length} onClick={()=>open(null)}>Schedule selected tables</button>}
 {!selectedTableIds.length&&canManage&&<p>Select tables on the floor map first.</p>}
 <details><summary>Current and upcoming plans ({plans.length})</summary><div style={{display:'grid',gap:10,marginTop:10}}>{plans.map(plan=><article className="card" key={plan.id}><strong>{plan.name} · {employees.find(e=>e.id===plan.employee_id)?.name??'Team member'}</strong>{!plan.assignable&&<p>Employee is inactive. Edit this plan to choose another employee.</p>}<p>{label(plan.starts_at)} – {label(plan.ends_at)}</p><p>{plan.table_ids.map(id=>tables.find(t=>t.id===id)?.table_name??'Unavailable table').join(', ')}</p><button type="button" onClick={()=>onSelect(plan.table_ids)}>Show tables</button>{canManage&&<><button type="button" disabled={busy} onClick={()=>open(plan)}>Edit</button><button type="button" disabled={busy} onClick={()=>void cancel(plan)}>Remove plan</button></>}</article>)}</div></details>
 {show&&<form onSubmit={e=>{e.preventDefault();void save()}}><fieldset disabled={busy}><legend>{editing?'Edit scheduled section':'Schedule selected tables'}</legend><p>{selectedTableIds.map(id=>tables.find(t=>t.id===id)?.table_name??id).join(', ')}</p><div className="form-grid"><label>Section name<input required maxLength={100} value={name} onChange={e=>setName(e.target.value)} /></label><label>Employee<select required value={employee} onChange={e=>setEmployee(e.target.value)}><option value="">Choose employee</option>{employees.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label><label>Date<input required type="date" value={date} onChange={e=>setDate(e.target.value)} /></label><label>Start<ClockTime required label="Section start" value={start} onChange={setStart}/></label><label>End<ClockTime required label="Section end" value={end} onChange={setEnd}/></label></div><p>An end time earlier than start means the next day. Overlapping plans for the same tables are blocked.</p><button disabled={!selectedTableIds.length||busy}>{busy?'Saving…':'Save scheduled section'}</button><button type="button" onClick={()=>{setShow(false);setEditing(null)}}>Cancel</button></fieldset></form>}
 </section>
}
