import { ScreenText } from './ScreenText'
import { useEffect, useRef, useState } from 'react'
import { supabase } from '../lib/supabase'
import './StockBoard.css'
type Item={id:string;name:string;version:number;added_by_name:string;added_at:string;restocked_by_name?:string;restocked_at?:string}
type Event={id:number;item_name:string;action:string;actor_name:string;created_at:string;note:string}
export const stockStamp=(value:string)=>new Intl.DateTimeFormat('en-US',{timeZone:'America/Chicago',month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(value))
export function StockBoard({location,readOnly=false,date}:{location:string;readOnly?:boolean;date?:string}){
 const [items,setItems]=useState<Item[]>([]),[events,setEvents]=useState<Event[]>([]),[name,setName]=useState(''),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[loading,setLoading]=useState(true),[history,setHistory]=useState(false)
 const request=useRef<string|null>(null),sequence=useRef(0)
 async function refresh(){const ticket=++sequence.current;try{const r=await supabase.rpc('stock_board_load',{p_location_id:location,p_date:date??null});if(r.error)throw r.error;if(ticket===sequence.current){setItems(r.data.items);setEvents(r.data.events);setError('')}}catch(e){if(ticket===sequence.current)setError(String((e as {message?:string}).message??e))}finally{if(ticket===sequence.current)setLoading(false)}}
 useEffect(()=>{if(!location)return;setItems([]);setEvents([]);setLoading(true);void refresh();const timer=setInterval(()=>{if(document.visibilityState==='visible')void refresh()},15000),focus=()=>void refresh();window.addEventListener('focus',focus);return()=>{sequence.current++;clearInterval(timer);window.removeEventListener('focus',focus)}},[location,date])
 async function add(){if(busy)return;setBusy(true);setError('');setNotice('');request.current??=crypto.randomUUID();try{const r=await supabase.rpc('stock_board_add',{p_location_id:location,p_name:name,p_note:note,p_request_id:request.current});if(r.error)throw r.error;setNotice(r.data.already_active?'This item is already on the 86 board. Your report was recorded.':'Item added to the 86 board.');request.current=null;setName('');setNote('');await refresh()}catch(e){setError(String((e as {message?:string}).message??e))}finally{setBusy(false)}}
 async function restock(item:Item){if(busy||!window.confirm('Mark '+item.name+' restocked? Your name and the time will be recorded.'))return;setBusy(true);setError('');try{const r=await supabase.rpc('stock_board_restock',{p_location_id:location,p_item_id:item.id,p_version:item.version});if(r.error)throw r.error;setNotice(item.name+' marked restocked.');await refresh()}catch(e){await refresh();setError(String((e as {message?:string}).message??e))}finally{setBusy(false)}}
 return <section className="card stock-board"><header><h2><ScreenText id="StockBoard.56d3a0cb7e41332c">86 Items Board</ScreenText></h2><button type="button" onClick={()=>void refresh()} disabled={busy}><ScreenText id="StockBoard.0e91610117029a62">Refresh</ScreenText></button></header><p><ScreenText id="StockBoard.1c5b1b423fe571df">Unavailable items stay here until marked restocked, including after the 4 AM rollover.</ScreenText></p>{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{!readOnly&&<form onSubmit={e=>{e.preventDefault();void add()}}><fieldset disabled={busy||request.current!==null}><label><ScreenText id="StockBoard.652bcc3a47842889">Item</ScreenText><input required maxLength={160} value={name} onChange={e=>setName(e.target.value)} placeholder="Example: Spiked Bread Pudding"/></label><label><ScreenText id="StockBoard.f9b73e1abc37cf5b">Note (optional)</ScreenText><input maxLength={500} value={note} onChange={e=>setNote(e.target.value)}/></label></fieldset><button disabled={busy||!name.trim()}>{busy?'Saving…':request.current?'Retry same item':'Add 86 item'}</button></form>}{loading&&<p role="status"><ScreenText id="StockBoard.cff8975cd1542c9f">Loading board…</ScreenText></p>}{!loading&&!items.some(i=>!i.restocked_at)&&<p><ScreenText id="StockBoard.9f31206faca224bc">No items currently marked 86.</ScreenText></p>}<ul>{items.filter(i=>!i.restocked_at).map(i=><li key={i.id}><div><strong>{i.name}</strong><small><ScreenText id="StockBoard.6a36cd65f13433dd">86’d by </ScreenText>{i.added_by_name} <ScreenText id="StockBoard.a137f17a19a09cbe">· </ScreenText>{stockStamp(i.added_at)}</small></div>{!readOnly&&<button type="button" disabled={busy} onClick={()=>void restock(i)}><ScreenText id="StockBoard.d18c194af1ba8d05">Mark restocked</ScreenText></button>}</li>)}</ul><details><summary><ScreenText id="StockBoard.3fb52baedc244ec4">Restocked items</ScreenText></summary><ul>{items.filter(i=>i.restocked_at).map(i=><li key={i.id}><div><s>{i.name}</s><small><ScreenText id="StockBoard.6a36cd65f13433dd">86’d by </ScreenText>{i.added_by_name} <ScreenText id="StockBoard.a137f17a19a09cbe">· </ScreenText>{stockStamp(i.added_at)}</small><small><ScreenText id="StockBoard.eb1f328e1ea6b8ae">Restocked by </ScreenText>{i.restocked_by_name} <ScreenText id="StockBoard.a137f17a19a09cbe">· </ScreenText>{stockStamp(i.restocked_at!)}</small></div></li>)}</ul></details><button type="button" onClick={()=>setHistory(v=>!v)}>{history?'Hide activity':'View activity'}</button>{history&&<ul>{events.map(e=><li key={e.id}><div><strong>{e.item_name} <ScreenText id="StockBoard.a137f17a19a09cbe">· </ScreenText>{e.action==='restocked'?'Restocked':e.action==='reported'?'86 report':'Marked 86'}</strong><small>{e.actor_name} <ScreenText id="StockBoard.a137f17a19a09cbe">· </ScreenText>{stockStamp(e.created_at)}</small>{e.note&&<p>{e.note}</p>}</div></li>)}</ul>}</section>
}
export function CloseoutStockDetails({location,id}:{location:string;id:string}){const [rows,setRows]=useState<string[]>([]),[error,setError]=useState('');useEffect(()=>{let live=true;void supabase.rpc('stock_closeout_items',{p_location_id:location,p_closeout_id:id}).then(r=>{if(!live)return;if(r.error)setError(r.error.message);else setRows(r.data??[])});return()=>{live=false}},[location,id]);return <div><h4><ScreenText id="StockBoard.cbfe0225c3103494">86 items reported on this closeout</ScreenText></h4>{error?<p role="alert">{error}</p>:rows.length?<ul>{rows.map((n,i)=><li key={i}>{n}</li>)}</ul>:<p><ScreenText id="StockBoard.7137b380511a12cc">No 86 items reported.</ScreenText></p>}</div>}
